blockprotocol/blockprotocol

site/src/_pages/docs/1_developing-blocks.mdx
site/src/components/pages/home/Header.tsx
site/src/components/pages/home/RegistrySection.tsx
site/src/components/pages/home/Section2/index.tsx
site/src/components/pages/home/WhyBlockProtocol2Section.tsx
site/src/pages/spec/[[...specSlug]].page.tsx
site/src/util/mdxComponents.tsx

- Add links which were missing from buttons on the homepage
- Add styling to table elements in MDX files
- Remove margin from the first header in MDX files
- Remove info tooltips from homepage

[SITE] Adding missing links. Fix table and header styling. Remove tooltips

---

site/src/util/mdxComponents.tsx

[SITE] Fix header bleed

---

site/src/pages/_document.page.tsx

Follows #60 
Refs:
- https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started
- https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image
- https://developers.facebook.com/docs/sharing/webmasters/

Improve meta tags

---

registry/@hash/code.json
registry/@hash/divider.json
registry/@hash/embed.json
registry/@hash/header.json
registry/@hash/image.json
registry/@hash/paragraph.json
registry/@hash/person.json
registry/@hash/table.json
registry/@hash/video.json
site/scripts/build-blocks.sh
site/src/pages/[shortname]/[blockSlug].page.tsx
site/src/pages/api/blocks.api.ts

Follows https://github.com/hashintel/dev/pull/432 (private link)

Sync block implementation with the updated spec

---

site/src/components/Button.tsx
site/src/components/FooterBanner.tsx
site/src/components/InfoCard/InfoCard.tsx
site/src/components/InfoCard/InfoCardWrapper.tsx
site/src/components/MDXPageContent.tsx
site/src/components/Navbar.tsx
site/src/components/PageNavLinks.tsx
site/src/components/pages/home/Header.tsx
site/src/components/pages/home/RegistrySection.tsx
site/src/components/pages/home/Section2/index.tsx
site/src/components/theme.ts
site/src/pages/docs/[[...docsSlug]].page.tsx
site/src/pages/spec/[[...specSlug]].page.tsx
site/src/styles/prism.css
site/src/util/mdxComponents.tsx

I did a pass through the site and adjusted a couple of styling bits and pieces. Most of it was just getting the spacing and typography sizes to match the Figma. I made a few new design decisions that differ from the Figma slightly. Always hard to know how things will feel once you get it into the browser.
The only major change I made was to change the max-width on large screens to 1400px instead of 1200px. Our documentation and spec were feeling a bit cramped, so wanted the extra space to give the sidebar and InfoCards more margin.
I went through and adjusted all the other elements on the homepage and docs pages to fix any bugs related to the max-width change. Tried to catch them all, hopefully did.
Other smaller changes:
- Adjusted the colours in our `<pre>` code snippets to match the …

[SITE] Styling tweaks

---

site/src/components/Footer.tsx

This PR adds a button to the footer than prompts visitors to star the project on Github
Previews
Mobile:

[SITE] Add Github Star Button to Footer

---

site/src/components/Footer.tsx
site/src/components/InfoCard/InfoCard.tsx
site/src/components/Navbar.tsx
site/src/components/pages/home/Section2/Steps.tsx
site/src/pages/_document.page.tsx
site/src/util/mdxComponents.tsx

See commit messages for details

[SITE] Fix a few React warnings

---

site/src/components/pages/home/WhyBlockProtocol2Section.tsx

050122_Typo4

---

site/src/components/pages/home/WhyBlockProtocol1Section.tsx

050122_Typo3

---

site/src/components/pages/home/WhyBlockProtocol2Section.tsx

050122_Typo2

---

site/src/components/pages/home/Section2/index.tsx

050122_Typo1

---

README.md

Make everybody happy 🙃 Also flagged by @judeallred

Remove HTML from README.md

---

site/src/components/pages/home/Header/HeaderCard.tsx

This PR staggers the display of "Full Name", "Job Title" and "Image" in the homepage header animation

[SITE] Header animation updates

---

site/README.md
site/package.json
site/src/components/Modal/LoginModal.tsx
site/src/components/Navbar.tsx
site/src/components/Screens/CompleteSignupScreen.tsx
site/src/components/Screens/SendLoginCodeScreen.tsx
site/src/components/Screens/SignupScreen.tsx
site/src/components/Screens/VerificationCodeScreen.tsx
site/src/components/TextField.tsx
site/src/components/hooks/useShortnameTextField.ts
site/src/lib/apiClient.ts
site/src/lib/config.ts
site/src/lib/handler/baseHandler.ts
site/src/lib/middleware/session.middleware.ts
site/src/lib/model/user.model.ts
site/src/pages/_app.page.tsx
site/src/pages/api/completeSignup.api.ts
site/src/pages/api/isShortnameTaken.api.ts
site/src/pages/api/loginWithLoginCode.api.ts
site/src/pages/api/sendLoginCode.api.ts
site/src/pages/api/signup.api.ts
site/src/pages/api/verifyEmail.api.ts
site/src/pages/login.page.tsx
site/src/pages/signup.page.tsx
yarn.lock

This PR implements the signup user flow on the BP site. Additional changes
- replaced `express-session` with `next-session` (resolves session issues locally and in deployment)
Future tasks:
- [suggest usernames based on email](https://app.asana.com/0/1201095311341924/1201652492640268/f)

[SITE] BP site signup UI

---

scripts/sync-algolia-index.ts

Fix typo in Algolia upload script

---

hub/@hash/divider.json

Follows https://github.com/hashintel/hash/pull/310
[Asana task](https://app.asana.com/0/1201707629991380/1201820398013208/f) (internal)
Preview: https://blockprotocol-lu40me1db-hashintel.vercel.app/@hash/divider

Update divider block timestamp

---

hub/@hash/callout.json

Ref: https://github.com/hashintel/hash/pull/308
Preview: https://blockprotocol-le3bey4oa-hashintel.vercel.app/hub
---
- https://app.asana.com/0/0/1201818207965388

Add callout block to hub

---

site/src/pages/[shortname]/blocks/[blockSlug].page.tsx

Shorten visible links on the block pages

---

hub/@hash/code.json

Update Code block to incorporate a fix from https://github.com/hashintel/hash/pull/404

Update Code block

---

hub/@kickstartds/button.json
site/scripts/prepare-blocks.ts

- [Asana task](https://hashintel.slack.com/archives/C02LG39FJAU/p1647453292119069) _(internal)_
- [Slack thread](https://hashintel.slack.com/archives/C02LG39FJAU/p1647453292119069) _(internal)_
- https://github.com/kickstartDS/blocks/issues/1
- https://github.com/kickstartDS/blocks/pull/2

Implement early exit in `prepare-blocks` script on error

---

site/src/components/HiringBanner.tsx
site/src/components/PageLayout.tsx

---
- https://app.asana.com/0/0/1201994881610194

Add "We're hiring" banner to site's footer

---

site/src/_pages/docs/0_index.mdx

**Makes clear the BP API supports dynamic insertion of blocks.** The users of BP-supporting apps can browse and insert previously unseen and untrusted blocks within EAs that choose to allow it.

Minor update to BP Docs overview page

---

hub/@hash/embed.json
site/src/lib/blocks.ts
site/src/pages/[shortname]/[[...profile-tabs]].page.tsx
site/src/pages/hub.page.tsx

Unblocks https://github.com/blockprotocol/blockprotocol/pull/312 (see https://github.com/blockprotocol/blockprotocol/pull/312#discussion_r891453161).
https://blockprotocol-7ipb8tizn-hashintel.vercel.app/hub 🫣
https://blockprotocol-7ipb8tizn-hashintel.vercel.app/@hash/blocks 🫣
https://blockprotocol-7ipb8tizn-hashintel.vercel.app/@hash/blocks/embed 👀

Temporarily hide four blocks from hub

---

site/src/components/footer.tsx

This PR fixes some broken links in the site's footer.

Fix broken footer links

---

site/src/components/pages/home/anyframework.tsx
site/src/components/pages/home/composable-interfaces.tsx
site/src/components/pages/home/interoperable-blocks.tsx
site/src/components/pages/home/registry-section.tsx

https://app.asana.com/0/1202250835094702/1202457331910983

copy tweaks for bp homepage

---

site/README.md

This mentions the need to build blocks in the site as part of the main dev set up instructions.

Update site README

---

site/src/_pages/docs/4_faq.mdx

This PR tweaks the 'what about non-web?' FAQ to mention that messages are passed via events now.
---
- https://app.asana.com/0/0/1202440221235949

Tweak "what about non-web" FAQ

---

site/src/components/navbar/mobile-nav-items.tsx
site/src/components/pages/docs/search/index.tsx
site/src/components/search-nav-button.tsx

This PR makes some code improvements and some other minor fixes to the search modal, including:
- focusing the search input when the component is mounted for desktop devices
- using the `TextField` component instead of a native HTML `input` component, and removing the custom styling
---
- https://app.asana.com/0/0/1202482456346907

Search Modal Improvements

---

site/src/components/pages/docs/search/index.tsx
site/src/components/pages/docs/search/search-list-category.tsx
site/src/components/pages/docs/search/search-list-heading.tsx
site/src/components/pages/docs/search/search-list-item.tsx
site/src/components/pages/docs/search/search-list.tsx

Refactors the assignment of search list item refs introduced in https://github.com/blockprotocol/blockprotocol/pull/396

Suggested change for lb/search-improvements-v2

---

site/package.json
site/src/components/link-button.tsx
site/src/components/pages/docs/search/index.tsx
site/src/components/pages/docs/search/search-list-category.tsx
site/src/components/pages/docs/search/search-list-heading.tsx
site/src/components/pages/docs/search/search-list-item.tsx
site/src/components/pages/docs/search/search-list.tsx

- Fixed a bug when erasing the search query, the search callback would be called after clearing search results and would cause them to show even when the query was empty.
- Fixed a crash when searching for certain strings (for example `a++` or `***`) - [Asana Task](https://app.asana.com/0/1201095311341924/1202487027725394/f)
- Added animations to the search list:
- Added arrow navigation between list items

Search improvements v2

---

rfcs/text/0352-graph-type-system.md

I forgot to add the link to the Discussion in the template

Add discussions link to Graph Type System RFC

---

.github/workflows/algolia-upload-index.yml
.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/publish-npm-packages.yml
.github/workflows/release.yml

This PR is an exact from my WIP Playwright setup. I’ve made a few small tweaks to GitHub workflows and decided to merge them separately to de-risk the main piece of work. See details in comments below.

Cleanup GitHub workflows

---

.github/workflows/ci.yml
site/playwright.config.ts
site/src/components/navbar.tsx
site/tests/universal/homepage.test.ts
site/tests/universal/page-header.test.ts

This PR updates existing playwright projects to use different browser setup.

Update Playwright projects

---

.github/workflows/ci.yml
site/README.md
site/scripts/build.ts
site/scripts/start.ts

---
- https://app.asana.com/0/0/1202644137081309

Document site test coverage, rename CODE_COVERAGE to TEST_COVERAGE

---

hub/@alfie/github-pr-overview.json
hub/@hash/callout.json
hub/@hash/code.json
hub/@hash/divider.json
hub/@hash/embed.json
hub/@hash/header.json
hub/@hash/image.json
hub/@hash/paragraph.json
hub/@hash/person.json
hub/@hash/shuffle.json
hub/@hash/table.json
hub/@hash/video.json
hub/@thehabbos007/calculation.json
hub/@timdiekmann/countdown.json
hub/@timdiekmann/timer.json
hub/@tldraw/drawing.json

This bumps HASH blocks to the latest in the HASH repo.

Bump blocks

---

site/src/lib/blocks.ts

Fix a bug I introduced in #509

Fix block componentId

---

.github/workflows/release.yml

Continues investigation of https://github.com/changesets/action/issues/187, replaces https://github.com/blockprotocol/blockprotocol/pull/536

Use `MACHINE_USER_TOKEN` in `release.yml` → `actions/checkout`

---

packages/mock-block-dock/package.json
packages/mock-block-dock/src/util.ts

Reverts blockprotocol/blockprotocol#564
I will re-submit this PR, but with Changesets file included (forgot about it).

Revert "Remove `lodash` from `mock-block-dock`"

---

.changeset/mbd-lodash.md
packages/mock-block-dock/package.json
packages/mock-block-dock/src/util.ts

Same as blockprotocol/blockprotocol#564, but with Changesets

Remove `lodash` from `mock-block-dock`

---

.changeset/odd-boats-reply.md
.eslintignore
.gitignore
.markdownlintignore
.prettierignore
packages/block-template-custom-element/.gitignore.dist
packages/block-template-html/.gitignore.dist
packages/block-template-react/.gitignore.dist
packages/blockprotocol/cli/commands/publish/find-api-key.js

Although longer, it is less mysterious.

Rename .bprc to .blockprotocolrc

---

site/src/pages/workshop/workshop.md

A lint failure managed to squeak through onto main

Fix linting

---

apps/site/src/components/inline-link.tsx
apps/site/src/components/pages/home/final-cta.tsx
apps/site/src/components/pages/hub/json-editor.tsx
apps/site/src/components/screens/send-login-code-screen.tsx
apps/site/src/components/screens/signup-screen.tsx
apps/site/src/pages/login.page.tsx
apps/site/src/pages/signup.page.tsx
packages/@local/eslint-config/index.js
packages/mock-block-dock/src/debug-view/dev-tools.tsx

https://eslint.org/docs/latest/rules/curly
Using `all` makes code rhythm more consistent which improves cognition.
- [Slack thread](https://hashintel.slack.com/archives/C02TWBTT3ED/p1664887623783489) (internal)
- [Asana task](https://app.asana.com/0/0/1203089470814745) (internal)
- https://github.com/blockprotocol/blockprotocol/pull/655

Configure ESLint `curly` rule

---

apps/site/src/_pages/docs/4_faq.mdx

Improvements to FAQ

---

apps/site/src/lib/api-client.ts

[Asana task](https://app.asana.com/0/1200211978612931/1203176157000692/f) (internal)

Improve error propagation in API client

---

apps/site/src/components/search-nav-button.tsx
apps/site/tests/integration/search-modal.test.ts
apps/site/tests/universal/page-header.test.ts

[Asana task](https://app.asana.com/0/1200211978612931/1203084649340047/f) (internal)

Fix `/` triggering search within input fields

---

.github/workflows/ci.yml

To be reverted when https://github.com/codecov/codecov-action/issues/837 is resolved

Configure `CODECOV_TOKEN`

---

.changeset/fuzzy-readers-jog.md

Adds a changeset to describe Type System package improvements

Update changeset to publish type system

---

.github/workflows/semgrep.yml

Upload Semgrep SARIF files to GitHub. Includes a number of other minor tweaks to bring into parity with `hashintel/hash` repo.

Upload Semgrep SARIF files to GitHub

---

.github/renovate.json

Follows #782, fixes a typo. Related docs:
- https://docs.renovatebot.com/configuration-options/#prconcurrentlimit
- https://docs.renovatebot.com/key-concepts/dashboard/#require-approval-for-all-updates

Require approval from Dependency Dashboard

---

apps/site/src/components/pages/user/overview-card.tsx
apps/site/src/pages/_document.page.tsx
packages/@local/package-chores/scripts/shared/publishable-packages.ts
packages/mock-block-dock/src/debug-view/dev-tools/logs-view.tsx

See https://lgtm.com/projects/g/blockprotocol/blockprotocol
- [Asana task](https://app.asana.com/0/1203193968491715/1203363157432075/f) _(internal)_
Out of scope: addressing 6 × [_Untrusted URL redirection_ ](https://lgtm.com/rules/1979240340/)(to be done separately).
ESLint is not configured for `packages/@local/package-chores` and `packages/@local/script-resources`. We should fix this ([new internal Asana task](https://app.asana.com/0/1203312852763953/1203429129383862/f)).
CI

Address several LGTM issues

---

packages/@local/eslint-config/README.md
packages/@local/package-chores/README.md
packages/@local/tsconfig/README.md

This PR explains the purpose of three local workspace we’ve got.
- [Asana task](https://app.asana.com/0/1203363157432081/1203494829477059/f) _(internal)_
- [Slack thread](https://hashintel.slack.com/archives/C02TWBTT3ED/p1670499445582139) _(internal)_
- #818 _(related)_

Add README.md files to local workspaces

---

apps/site/src/components/pages/wordpress/header.tsx
apps/site/src/components/pages/wordpress/why-develop.tsx

This PR is a follow-up to #837  fixes style issues in the WP Landing Page

WP Landing page improvements

---

apps/site/src/components/pages/wordpress/request-another-application.tsx

Twitter dumb. This fix. Predates Elon. Can't blame him (today).

Tweak link to cache-bust Twitter Open Graph

---

README.md
apps/site/src/components/coming-soon-banner.tsx
apps/site/src/pages/wordpress.page.tsx

- Adds a README cover image
- Tweaks a few bits of copy on the prod site

Mixed minor copy and repo updates

---

apps/site/src/components/page-layout.tsx

This PR hides the BP v0.3 banner in the signup page.
- [Asana task](https://app.asana.com/0/1203363157432087/1203586302001326/f) _(internal)_

Hide BP banner in signup page

---

apps/site/src/components/pages/wordpress/request-another-application.tsx

This PR adds and height transition to the voting section so the card's height doesn't jump when going through the voting flow.
- [Asana task](https://app.asana.com/0/1203363157432087/1203568198115176/f) _(internal)_
Hide whitespace for an easier review

Add animated transition to vote section resizing

---

README.md

- Refactors jumplinks in root README
- Additional improvements to correctness and copy in root README

Refactor jumplinks in root README

---

hub/@alfie/github-pr-overview.json
hub/@hash/callout.json
hub/@hash/code.json
hub/@hash/divider.json
hub/@hash/embed.json
hub/@hash/header.json
hub/@hash/image.json
hub/@hash/paragraph.json
hub/@hash/person.json
hub/@hash/shuffle.json
hub/@hash/table.json
hub/@hash/video.json
hub/@thehabbos007/calculation.json
hub/@timdiekmann/countdown.json
hub/@timdiekmann/timer.json
hub/@tldraw/drawing.json

Increase block versions following https://github.com/hashintel/hash/pull/1764

Bump block versions

---

apps/site/src/_pages/docs/1_developing-blocks.mdx
apps/site/src/_pages/docs/3_using-blocks.mdx
apps/site/src/_pages/docs/5_faq.mdx
apps/site/src/components/pages/home/confined-blocks.tsx
apps/site/src/components/pages/wordpress/voting/now-in-beta.tsx
apps/site/tests/integration/homepage.test.ts

Minor misc/mixed improvements to copy.

Minor improvements to copy

---

apps/site/src/components/screens/signup-screen.tsx

- [Asana task](https://app.asana.com/0/1203623179643281/1203900352088439/f) _(internal)_
Before:
After:

Fix signup page icon size in Firefox

---

libs/@blockprotocol/graph/src/types/ontology/entity-type.ts

They required properties users shouldn't be passing

Fix create and update entity type messages

---

libs/@blockprotocol/core/package.json

#957 didn't work, so I'm trying something else to fix the error described there.

Update 'main' config in package

---

libs/mock-block-dock/src/datastore/traverse.ts

#948 fixed bugs, one was missed in a rebase. This adds it.

Fix graph traversal

---

infra/cloudflare-r2-wrangler/blockprotocol-preview/wrangler.toml
infra/cloudflare-r2-wrangler/blockprotocol/wrangler.toml

Remove the vars in the wrangler file, these override secrets/variables set in CF

Remove defaults for CF worker variables

---

apps/site/src/_pages/docs/3_using-blocks.mdx

Adds a stability notice to the 'Using Blocks' page.

Add stability notice for self-hosted HASH env

---

libs/@blockprotocol/graph/README.md
libs/@blockprotocol/graph/src/types/block-graph.ts
libs/block-template-custom-element/README.md
libs/block-template-html/README.md
libs/block-template-react/README.md
libs/mock-block-dock/README.md

Some basic updates to package READMEs to bring them to up to date for the `0.3` spec.
[Asana task](https://app.asana.com/0/1203543026679380/1203855800580752/f) (internal)

Update package READMEs

---

apps/site/src/components/pages/dashboard/utils.ts
apps/site/src/components/pages/user/tab-panel-contents-with-overview.tsx
apps/site/tests/integration/accountpage.test.ts
apps/site/tests/integration/dashboard.test.ts

Fix a few links to the user's type page and references in copy to 'schemas' -> 'types'

Fix type links

---

libs/@blockprotocol/graph/package.json
libs/block-template-custom-element/src/app.ts
libs/block-template-react/src/app.tsx

Some doc-comments were out of date, and the exports of the graph module package were incorrect.

Small fixes

---

apps/site/src/pages/api/rewrites/block-metadata.api.ts

This PR follows #1014 and sets CORS for the new endpoint
- [Asana task](https://app.asana.com/0/1203623179643287/1204013272276571/f) _(internal)_
- [Slack thread](https://hashintel.slack.com/archives/C022217GAHF/p1677092665674599?thread_ts=1677083995.394479&cid=C022217GAHF) _(internal)_

Set CORS when serving `block-metadata.json`

---

libs/@blockprotocol/type-system/crate/src/ontology/url/error.rs
libs/@blockprotocol/type-system/crate/src/ontology/url/mod.rs

The IDE failed to update from disk, these were missed in #1022

Fix formatting

---

libs/mock-block-dock/dev/test-react-block.tsx
libs/mock-block-dock/src/service-module-callbacks.ts

This PR adds the `createImage` and `completeText` OpenAI methods to MBD.
- [Asana task](https://app.asana.com/0/1203623179643287/1204030283606430/f) _(internal)_
See commits.
Not that I'm aware of.
Manual testing.
1. Run the BP site in your local developer environment with seeded users
2. Create/obtain your BP API key and add it as an `BP_API_KEY` environment variable to your `.env.local`
3. Run the HASH internal API in your local dev environment on the `bw/openai-api` branch
4. Run the  mock-dock-block local developer environment
5. Use the test block to make a request to the openai API

Add OpenAI methods to MBD

---

apps/site/src/lib/api/blocks/s3.ts

We previously wiped the block's source file folder in R2 before uploading the latest version. This has the effect of immediately removing the previous version's source file, which is bad if someone is relying on it (e.g. has stored it in a page somewhere).
This PR stops doing that. While it means there will be an accumulation of old source files, they won't do any harm and anything from the new files that clashes with the old will overwrite them. This doesn't apply to source files as they have a hash in the filename.
This will all become irrelevant when we start persisting previous versions, which will be in the next few weeks.
- [Asana task](https://app.asana.com/0/1203358502199087/1203979552136008/f) _(internal)_

Don't wipe R2 folders when uploading new block files

---

apps/site/public/types/modules/graph/0.3/schema/aggregation-operation.json
apps/site/public/types/modules/graph/0.3/schema/entity-metadata.json
apps/site/public/types/modules/graph/0.3/schema/graph-resolve-depths.json
apps/site/public/types/modules/graph/0.3/schema/link-data.json
apps/site/public/types/modules/graph/0.3/schema/partial-graph-resolve-depths.json
apps/site/public/types/modules/graph/0.3/schema/subgraph.json
apps/site/src/_pages/docs/1_developing-blocks.mdx
apps/site/src/_pages/docs/4_spec/03_hook-module.mdx
apps/site/src/_pages/docs/5_faq.mdx
apps/site/src/components/module-message-list.tsx
libs/@blockprotocol/core/src/types.ts
libs/@blockprotocol/graph/src/graph-module.json

Bundling a few smaller fixes needed for 0.3
See the commits.
---
- https://app.asana.com/0/0/1203701650452070
- https://app.asana.com/0/0/1203946355023398
- https://app.asana.com/0/0/1203978096566296

Docs/spec: update hook service, cover block verification, update metadata type

---

apps/site/src/_pages/docs/1_developing-blocks.mdx

Adds some more guidance on how to call `getEntity` and `queryEntities` as well as a bit more information on the `graphResolveDepths` object.

Improve developing blocks guide

---

apps/site/src/pages/api/external-service-method.api.ts

Improve Axios error parsing from #1054

Further external service error tweaks

---

apps/site/src/lib/api/blocks/get.ts
libs/mock-block-dock/src/version.ts

This PR  updates the featured blocks with a guess on their names, as it depends on upstream work

Correct hub page featured blocks

---

apps/site/src/pages/settings/billing-settings-panel/payment-history-section.tsx

This PR removes the upcoming invoices from the payment history section.
- [Asana task](https://app.asana.com/0/1203623179643287/1204059903170051/f) _(internal)_

Remove upcoming invoice from payment history section

---

apps/site/src/lib/config.ts

This PR removes a console log which was added for debugging purposes, and is no longer needed.

Remove console log

---

vercel.json

This seems to be the setting, which cancels Vercel builds if a subsequential commit was done.
- [Asana task](https://app.asana.com/0/1201095311341924/1203216920361762/f) _(internal)_
- [Vercel Documentation](https://vercel.com/docs/concepts/projects/project-configuration/git-configuration#github.autojobcancelation)

Enable auto-job-cancelation for Vercel

---

.changeset/eight-cherries-fly.md
.changeset/lazy-terms-chew.md

This PR adds a changeset for the `@blockprotocol/service`, generated using `yarn changeset` in the repo root.

Add changeset to `@blockprotocol/service` for release

---

apps/site/src/pages/settings/billing-settings-panel/usage-limit-section.tsx

Makes it clear that the value inputted into this field is specified in USD.
---
- https://app.asana.com/0/0/1204059902060147

Make usage limit input label more specific

---

libs/@blockprotocol/graph/src/non-temporal/stdlib.ts
libs/@blockprotocol/graph/src/shared/stdlib.ts
libs/@blockprotocol/graph/src/shared/stdlib/subgraph/edge/entity-type.ts
libs/@blockprotocol/graph/src/shared/stdlib/subgraph/edge/property-type.ts
libs/@blockprotocol/graph/src/shared/stdlib/subgraph/edge/shared.ts
libs/@blockprotocol/graph/src/shared/types/subgraph/edges/variants/ontology.ts
libs/@blockprotocol/graph/src/temporal/stdlib.ts

This PR adds various helper methods to get ontology types referenced by an ontology type. I've added:
- `getEntityTypesReferencedByEntityType` (edges `InheritsFrom`, `ConstrainsLinksOn` and `ConstrainsLinkDestinationsOn` )
- `getPropertyTypesReferencedByPropertyType` (`edge ConstrainsPropertiesOn`)
- `getDataTypesReferencedByPropertyType` (edge `ConstrainsValuesOn`)
I've separated the edge union to make the 'helper helper' function have more accurate typing: `StrictOntologyOutwardEdge`
These new functions have been exported and use the same "shared" helper to simplify their implementation
- [Asana task](https://app.asana.com/0/1203623179643290/1204128625385540/f) _(internal)_
- See start of description and commits.
- Implementing traversals for these types [Asana …

Add Graph stdlib helper functions for Ontology Type references

---

libs/@blockprotocol/design-system/README.md

Prepares the repository for Vercel project setup, pre-handoff for Storybook setup.
Adds an empty `/libs/@blockprotocol/design-system` directory.

Create `design-system` placeholder dir

---

.changeset/funny-buttons-beam.md
libs/@blockprotocol/hook/README.md
libs/mock-block-dock/.eslintrc.cjs
libs/mock-block-dock/dev/test-custom-element-block.ts

Adds an example of using the Hook Module in a custom element block.
---
- https://app.asana.com/0/0/1204164203672395

Add example of Hook Module usage in custom element block

---

libs/wordpress-plugin/plugin/trunk/block-protocol.php
libs/wordpress-plugin/plugin/trunk/server/block-db-table.php
libs/wordpress-plugin/plugin/trunk/server/data.php

This PR fixes out data reporting not working because of assuming the DB is migrated before the migrations are in place.
I've also adjusted some of the reporting we do to include more information about the DB and DB compatibility
[Asana task](https://github.com/blockprotocol/blockprotocol/pull/1168)

Fix data reporting to work with unmigrated DB

---

apps/site/src/components/modal/create-schema-modal.tsx
apps/site/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page.tsx

We were filtering special chars out of titles for types, and accidentally encoding special characters incorrectly in descriptions of types. This PR fixes that.
- [Asana task](https://app.asana.com/0/0/1204203279638195/f) _(internal)_
- N/A
- Removes `handleSchemaTitleChange` as we parse the schema title and call `slugify` on it anyway, and the spec allows any text within the `title` field.
- Correctly decodes the draft entity type into `utf8` instead of `ascii` which was causing strange errors with special chars.
- Driveby: fixes a bug where you could submit the create entity type modal with an invalid title which would resolve to an empty slug and then crash: [Disallow submission of types with empty slugs](https://github.com/blockprotocol/blockprotocol/pull/1196/commits/e440995107fbfb7081 …

Allow special characters in titles and descriptions of types

---

apps/site/package.json
yarn.lock

Bump version of `@hashintel/type-editor` to bring in bug fixes from https://github.com/hashintel/hash/pull/2196

Bump type editor version

---

apps/site/src/components/pages/user/tab-panel-contents-with-schemas.tsx

🌟 What is the purpose of this PR?
---
This PR fixes the user type list display on mobile
🔗  Related links
---
- [Github](https://github.com/blockprotocol/blockprotocol/issues/1165)
❓How to test this?
---
https://user-images.githubusercontent.com/57623705/226363045-9b8b79e1-f0a2-4a64-acb0-c320d42c12a3.mov
---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.

[BP-1] Fix user type list display on mobile

---

apps/site/public/types/modules/graph/0.3/schema/entity.json

We accidentally used `versioned-url` instead of `base-url`. This fixes it.

Fix schema path in `entity.json`

---

apps/site/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page.tsx
apps/site/src/pages/_app.page.tsx
apps/site/src/styles/table-component.css

🌟 What is the purpose of this PR?
---
This PR fixes the entity type table display on mobile
🔗  Related links
---
- [Github](https://github.com/blockprotocol/blockprotocol/issues/1166)
❓How to test this?
---
https://www.loom.com/share/171b3fd67e0744b98bfd3dce00c8fe04
---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.
---
- https://app.asana.com/0/0/1204147538988935

[BP-3] Fix entity type table display on mobile

---

apps/site/src/components/modal/create-schema-modal.tsx

Fixes a check which crashes on the server.

Check if browser before accessing navigator

---

apps/site/src/_pages/docs/2_types.mdx

Add graph type system link to types docs page

---

apps/site/src/pages/account/api-keys-panel.tsx
apps/site/src/pages/account/api-keys-panel/api-keys-list.tsx
apps/site/src/pages/account/api-keys-panel/api-keys-list/api-key-table-row.tsx
apps/site/src/pages/account/api-keys-panel/api-keys-list/api-keys-memoized-items.tsx
apps/site/src/pages/account/api-keys-panel/api-keys-list/mobile-api-key-item.tsx
apps/site/src/pages/account/api-keys-panel/api-keys-list/shared/use-key-action.ts
apps/site/src/pages/account/api-keys-panel/types.ts

https://user-images.githubusercontent.com/39553853/232823987-64ce2300-556e-4a04-8e5c-e84ea37782fb.mov

Fix performance issue of new api keys page 

---

apps/site/src/_pages/docs/1_blocks/01_environments.mdx
apps/site/src/components/pages/pricing/free-tier-section.tsx
apps/site/src/components/pages/pricing/paid-addons-section.tsx
apps/site/src/components/pages/pricing/paid-tiers-section.tsx
apps/site/src/pages/account/billing-panel/external-service-free-allowance.ts
apps/site/src/pages/account/billing-panel/free-or-hobby-subscription-tier-overview.tsx
apps/site/src/pages/account/billing-panel/pro-subscription-tier-overview.tsx
libs/@local/internal-api-client-generator/typescript/api.ts

This PR adds the GPT-4 monthly free tokens to the existing BP pages.
- [Asana task](https://app.asana.com/0/1204260760205594/1204502471509788/f) _(internal)_
- regenerates the internal API client from the `bw/gpt-4` branch on the internal API repo
This PR:
None
Changes to the pricing page:
Changes to the upgrade page for "free"/"hobby" users:
Changes to the upgrade page for "pro" users:

Add GPT-4 monthly free tokens

---

apps/site/vercel-build.sh
apps/site/vercel-install.sh
apps/site/vercel.json
libs/@blockprotocol/design-system/vercel-build.sh
libs/@blockprotocol/design-system/vercel-install.sh
libs/@blockprotocol/design-system/vercel.json
vercel.json

Similar to what we have at HASH this adds `vercel.json` per project to persist commands in VCS and being able to run different commands per branch. This is a direct follow-up of #1288 and as a result is blocked on it.
- [Asana Task](https://app.asana.com/0/1204315348455207/1204596705932063/f) (_internal_)
- #1288

Provide a `vercel.json` per project

---

libs/@blockprotocol/type-system/crate/src/ontology/entity_type/error.rs
libs/@blockprotocol/type-system/crate/src/ontology/entity_type/links/repr.rs
libs/@blockprotocol/type-system/crate/src/ontology/entity_type/repr.rs
libs/@blockprotocol/type-system/crate/src/ontology/shared/object/repr.rs
libs/@blockprotocol/type-system/crate/tests/data/entity_type/building.json
libs/@blockprotocol/type-system/crate/tests/data/entity_type/church.json
libs/@blockprotocol/type-system/crate/tests/data/entity_type/mod.rs

For a closed entity type it's required to merge an entity type with its parent.
- [Asana task](https://app.asana.com/0/1204315348455207/1204596705932094/f) _(internal)_
- [Slack thread](https://hashintel.slack.com/archives/C03TWBSRT8B/p1684314549509999) _(internal)_
- Add a `merge_parent` method, the function is documented 
This PR:
A documentation for the method was added
- A simple test case has been added

Provide a `repr::EntityType::merge_parent` method

---

.github/renovate.json

Disables auto-update w/ Renovate on those packages where we had it enabled.

Disable Renovate auto-update

---

.github/pull_request_template.md

In the HASH repository we recently changed the pre-merge checklist and it's been a lot easier to write PRs with that PR template. This applies the same changes here and also makes the template a bit more readable by removing some empty l ines.
This PR:

BP-35: Simplify pull request template

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/issue-report.md
.github/ISSUE_TEMPLATE/suggest-an-integration.md

See internal context in H-624.

H-624: Add GitHub issue templates

---

apps/site/src/middleware.page/return-types-as-json.ts

Fixes another bug related to a RegExp update, further to #1330

Update type kind matching logic for new regexp

---

apps/site/vercel-install.sh
libs/@blockprotocol/type-system/crate/.justfile
libs/@blockprotocol/type-system/crate/Cargo.toml
libs/@blockprotocol/type-system/crate/rust-toolchain.toml
libs/@blockprotocol/type-system/crate/src/lib.rs
libs/@blockprotocol/type-system/crate/src/ontology/entity_type/links/raw.rs
libs/@blockprotocol/type-system/crate/src/ontology/mod.rs
libs/@blockprotocol/type-system/crate/src/ontology/url/mod.rs
libs/@blockprotocol/type-system/crate/src/ontology/url/wasm.rs

The toolchain is almost a year old, the crates are outdated, and the linting section should be updated.
The list of enabled lints is taken from the HASH crate configurations.
This PR:

BP-58: Update type-system crates and toolchain

---

apps/site/src/_pages/legal/terms/00_index.mdx

Fixes a number of broken jumplinks in our legal pages.

BP-64: Fix broken jumplinks in ToS

---

apps/site/src/_pages/docs/1_blocks/01_environments.mdx

Just a minor typo fix.
https://blockprotocol.org/docs/blocks/environments#environments

H-2263: Fix typo in `01_environments.mdx`

---

.github/CONTRIBUTING.md

Commit 45fa9a3d8f048bb78423a00c6654ad6fd7580830 moved the licenses files. This PR adjusts sources to changes.
This PR:
-
1.  Checkout the branch / view the deployment
1.  Try X
1.  Confirm that Y

Update license reference

---

.github/renovate.json

BP-113: Extend base BP Renovate config

---

.github/renovate.json

Disables Renovate updates in the BP repo for now.

BP-117: Disable Renovate updates
