- site/src/components/pages/home/Header.tsx
- site/src/pages/_app.page.tsx
- site/src/pages/contact.page.tsx
- Update copy in page title and homepage headers
- Add email and Discord link to the /contact page
> [SITE] Add contact options. Tweak homepage copy and HTML title

- site/src/components/BlockCard.tsx
- site/src/pages/[shortname]/[blockSlug].page.tsx
**Before**  
https://blockprotocol-f6y3xupq0-hashintel.vercel.app/@hello/world
**After**  
https://blockprotocol-bcjr91k7x-hashintel.vercel.app/@hello/world
I noticed this bug when working on #60. Opening https://blockprotocol.org/assets/bp_twitter_cover.png before merging returned 500.
> Fix HTTP 500 for non-existing blocks

- site/src/_pages/spec/0_index.mdx
- site/src/_pages/spec/1_block-types.mdx
- site/src/_pages/spec/2_embedding-application-implementation.mdx
In preparation for launch we updated the slug of Appendix A and this PR corrects old broken links which were resulting in 404s.
> Fix broken links in spec

- site/src/_pages/spec/4_appendix-a-styling.mdx
- site/src/_pages/spec/5_appendix-b-accessibility.mdx
- site/src/_pages/spec/6_appendix-c-internationalization.mdx
This is a boring PR that changes "advanced comments" to "advance comments" in a few places, where there are sections yet to be written and we're soliciting community feedback.
> Fix minor typos in spec

- site/src/components/theme.ts
Previously there were no fallback fonts, so before the fonts are loaded by the browser the user could briefly see a sarif font:
This PR introduces fallback fonts (`"Helvetica"`, `"Arial"` and `sans-serif`) which are now displayed instead whilst the browser is loading the correct fonts:
---
- https://app.asana.com/0/0/1201543651334385
> [SITE] add fallback fonts

- site/src/components/pages/home/Section2/index.tsx
- site/src/components/pages/home/WhyBlockProtocol1Section.tsx
- site/src/components/pages/home/WhyBlockProtocol2Section.tsx
@EllieHoward78 kindly opened a number of PRs (#77, #78, #79, #80 and #81) fixing some typos in our site. These have been merged into an `eh/typo-fixes` branch, and this PR proposes to squash and merge that in into `main`.
> Various copy fixes

- site/src/components/PageSidebar.tsx
- site/src/pages/docs/[[...docsSlug]].page.tsx
- site/src/pages/spec/[[...specSlug]].page.tsx
This PR stops truncating the link text in the `PageSidebar` on the specification/documentation pages:
In addition this PR makes the `PageSidebar` scrollable when its expanded contents exceed the height of the viewport, and it is in the "sticky" state.
---
- https://app.asana.com/0/0/1201588774378622
> [SITE] stop truncating sidebar navigation items, make sidebar scrollable

- registry/@hash/code.json
- registry/@hash/divider.json
- registry/@hash/embed.json
- registry/@hash/header.json
- registry/@hash/image.json
- registry/@hash/paragraph.json
- registry/@hash/person.json
- registry/@hash/table.json
- registry/@hash/video.json
- site/src/_pages/spec/1_block-types.mdx
- site/src/_pages/spec/2_embedding-applications.mdx
- site/src/_pages/spec/3_implementation-approaches.mdx
Some section headers were a little wordy, which was fine for their original doc context, but not when used in a navigation sidebar.
This PR shortens them.
> [SPEC] Update section headers

- site/package.json
- site/scripts/build-blocks.sh
Vercel persists nextjs' cache between builds. That's why I used it to persist block builds, too.
However, vercel provides fresh cache instances for each branch and seems to clear the target branch's
cache when merging. This PR removes all caching functionality and changes the build command so that all blocks get build everytime.
> [tool] build all blocks everytime

- CONTRIBUTING.md
- README.md
- site/next.config.js
- site/src/components/Footer.tsx
- site/src/components/Link.tsx
- site/src/pages/contact.page.tsx
This PR unifies links to Discord our server by creating a new `/discord` redirect endpoint. It is now used both in internal pages and markdowns. Markdown links are absolute, so we need to merge this PR for them to start working.
I was thinking of putting the link to an env variable, but then decided to hardcode it right in `next.config.js`. That’s one less abstraction to think about if a link changes. I don’t think it will happen too often if at all TBH.
[Asana task](https://app.asana.com/0/1201414765539664/1201562956971361/f) (internal link)
> Add redirect from `/discord`

- site/src/_pages/docs/1_developing-blocks.mdx
- site/src/_pages/docs/3_embedding-blocks.mdx
- site/src/_pages/spec/0_index.mdx
- site/src/_pages/spec/1_block-types.mdx
- site/src/_pages/spec/2_embedding-applications.mdx
in #88 I updated section headers without catching a few internal links that referred to the old headers.
This fixes that.
> [SPEC] Update internal links to match new headers

- hub/@hash/code.json
- hub/@hash/divider.json
- hub/@hash/embed.json
- hub/@hash/header.json
- hub/@hash/image.json
- hub/@hash/paragraph.json
- hub/@hash/person.json
- hub/@hash/table.json
- hub/@hash/video.json
- site/scripts/build-blocks.sh
We recently moved source code for our initial blocks from a private repository to [`hash`](https://github.com/hashintel/hash).
As a consequence this PR:
- updates the block config files to point to the new repo
- removes authentication handling from the block build script - auth is no longer required as the source is available publicly.
> Update block metadata + build script for new source repo

- packages/blockprotocol/core.d.ts
- site/src/_pages/spec/1_block-types.mdx
Cleans up the functions described in the spec and typed in the `blockprotocol` package to ensure completeness and consistency: 
- Adds functions described in the spec which were missing from the `blockprotocol` types
- Adds some fields that were missing or inconsistently applied across both, e.g. `accountId`
- Makes optional fields consistently `| null` (since different apps may omit or provide `null`)
**Next steps:**
- Release v0.0.2
- See what breaks in HASH and fix it (this PR should actually apply some of the patches we have there rather than break anything)
> Make fn signatures consistent between spec and blockprotocol

- .eslintrc.js
- site/src/components/Modal.tsx
- site/src/components/Modal/LoginModal.tsx
- site/src/components/Navbar/AccountDropdown.tsx
- site/src/components/Popover.tsx
- site/src/util/muiUtils.tsx
This PR replaces MUI's scroll-lock mechanism which adds a padding to the body to replace the scrollbar which however breaks the layout our case. The solution is to apply different yet equally effective styles to the html element.
How to reproduce: Fire up the site, log in, then press the account button in the top-right corner. The popover should pop over and the menu should no longer shift to the left due to prior body-padding applied by MUI.
> [SITE] Replace mui's troublesome scroll-lock implementation

- site/src/lib/config.ts
We need to know the frontend URL to (a) email links to users to login, and (b) to derive the domain to set for the cookie.
This was configured to prioritise the `NEXT_PUBLIC_VERCEL_URL`, which is fine for preview deployments, but inappropriate for production as it is not the actual domain users are visiting (https://blockprotocol.org), but a different Vercel URL.
This means that users visiting https://blockprotocol.org will have the incorrect domain set on the cookie issued to them on login, and subsequent requests will not be authenticated.
This PR fixes that by prioritising the `FRONTEND_URL` variable (which has been set in Vercel for production to https://blockprotocol.org).
> [SITE] Fix cookie domain in production

- site/README.md
- site/package.json
- site/src/_pages/docs/3_embedding-blocks.mdx
- site/src/pages/api/blocks.api.ts
- yarn.lock
This PR adds a query parameter for filtering blocks by a JSON payload on the query parameter on the `/api/blocks` endpoint.
The added query parameter is `json` and can be used as follows
`https://blockprotocol.org/api/blocks?json={"name":"Bob","email":"bob@test.com"}`
or URL encoded:
`https://blockprotocol.org/api/blocks?json=%7B%20%22name%22%3A%20%22Bob%22,%20%22email%22%3A%20%22bob%40test.com%22%20%7D`
The implementation requires any JSON object to at least supply one value from any block it returns, otherwise blocks that have only optional fields/no fields would always validate and be returned (such as the Divider block.)
> [API] Filter blocks by JSON schema validity

- packages/create-block-app/create-block-app.js
- packages/create-block-app/package.json
- yarn.lock
@CiaranMn could not run `npx create-block-app` on his laptop because of the following error:
```txt
npm ERR! Could not install from "../../../var/folders/lf/yycqw_q52wzc77xg1b9ghf740000gn/T/tmp-55410-lZLZsIF4dliY" as it does not contain a package.json file.
```
It was caused by `npm pack`, which did not support `--destination` in v6. This PR replaces `npm pack` with [`pacote`](https://www.npmjs.com/package/pacote), which allows us to download and extract a package in a single function call.
Because of `pacote`, we have a few more sub-dependencies than before. This is not ideal but tolerable for the time being. When the number of downloads increases, we can replace `pacote` with lower-level calls to NPM registry. They require more edge case handling and testing, so are probably not worth …
> Stop using `npm pack` in `create-block-pack` to support npm v6

- site/src/_pages/spec/1_block-types.mdx
- site/src/pages/docs/[[...docsSlug]].page.tsx
- site/src/pages/spec/[[...specSlug]].page.tsx
Reported in: https://github.com/blockprotocol/blockprotocol/discussions/118 (thanks for spotting this @leswaters 👍)
This has been fixed by changing a link in [Block types → Data transfer](https://blockprotocol.org/spec/block-types#data-transfer).
Before:
- https://blockprotocol-7hzzd9xe6-hashintel.vercel.app/spec/block-types#data-transfer
After: 
- https://blockprotocol-apxv16otf-hashintel.vercel.app/spec/block-types#data-transfer
All non-existing pages under `/docs/*` and `/spec/*` were returning HTTP 500 instead of 404.
Logs (internal link): https://vercel.com/hashintel/blockprotocol/3GwSF5NKh2zaaqjsYyR8QZ9kFR4W/functions
This has been fixed with `try / catch` inside `getStaticProps`. See comments in diff for details.
Before:
- …
> Fix 404 in spec and 500 in spec & docs

- package.json
Turns out that `yarn` does not treat `./path/to/workspace` and `path/to/workspace` equally. Related upstream work:
- https://github.com/yarnpkg/yarn/issues/4791
(same issue as we have)
- https://github.com/yarnpkg/yarn/pull/4654
(introduces `yarn workspace ... remove`, but probably lacks some check)
[Asana Task](https://app.asana.com/0/1201668052739245/1201707629991350/f) _(internal link)_
```sh
yarn workspace blockprotocol remove @types/react
```
```sh
yarn workspace blockprotocol add @types/react
ls packages/blockprotocol/yarn.lock
```
```sh
yarn workspace blockprotocol remove @types/react
```
```sh
yarn workspace blockprotocol add @types/react
ls packages/blockprotocol/yarn.lock
```
> Fix workspace setup

- hub/@hash/header.json
The header block was updated in https://github.com/hashintel/hash/pull/194 in order to add variants, and we now need to update the version on the registry so that users can start using them. Merging this pull request should do that.
> [CHORE] Trigger rebuild of Header block

- site/src/components/Modal/LoginModal.tsx
- site/src/components/Navbar.tsx
- site/src/components/Navbar/AccountDropdown.tsx
- site/src/components/Screens/CompleteSignupScreen.tsx
- site/src/components/UserAvatar.tsx
- site/src/components/pages/authWall.tsx
- site/src/context/UserContext.ts
- site/src/pages/_app.page.tsx
- site/src/pages/dashboard.page.tsx
- site/src/pages/login.page.tsx
- site/src/pages/settings/api-keys.page.tsx
- site/src/pages/signup.page.tsx
This reuses guest redirects in `/dashboard` in `/settings/api-keys`. To avoid repetition, I’ve introduced `withAuthWall`, which we can use onwards in the new pages.
To further reduce repetition, I have replaced `useContext(UserContext)` with `useUser()`, which is a common pattern in React hooks.
When looking at the original logic in `/dashboard`, I noticed a timing bug which was to do with the speed of `/auth/me`. If we rendered the dashboard before `fetch` was resolved, we ended up with an unwanted redirect for logged in users. This is fixed by adding `UserState = SerializedUser | "loading" | undefined`, which allows us to represent reality more accurately.
[Asana task](https://app.asana.com/0/1201095311341924/1201694916711161/f) _(internal link)_
> Hide `/settings/api-keys` for guests, unify auth wall

- packages/block-template/package.json
- packages/blockprotocol/core.d.ts
- packages/blockprotocol/package.json
- site/package.json
- site/src/_pages/spec/1_block-types.mdx
Clean up a few things in the types:
- On links, move `destinationAccountId` from being for single link targets only to also being an optional field when defining a linked aggregation.
- Add optional `sourceAccountId` and `sourceEntityId` when identifying links (`linkId` might not be sufficient/unique)
- Make functions all optional (embedding apps may not provide them)
> [blockprotocol] Add a few missing fields to types

- site/src/components/pages/hub/BlockDataContainer.tsx
- site/src/components/pages/hub/BlockDataTabPanels.tsx
This PR removes the max-width requirement from the `BlockDataContainer`, allowing blocks to take upto 90% of the available space instead. Additionally, the container height is increased to prevent overflow on blocks like the embed block.
> [FE] Remove max-width requirement from block

- hub/@hash/code.json
- hub/@hash/divider.json
- hub/@hash/embed.json
- hub/@hash/image.json
- hub/@hash/paragraph.json
- hub/@hash/person.json
- hub/@hash/table.json
- hub/@hash/video.json
- site/src/components/pages/hub/BlockDataContainer.tsx
This PR is a follow-up to the previous PRs in the hash repo which add examples to various blocks: https://github.com/hashintel/hash/pull/239, https://github.com/hashintel/hash/pull/233 and https://github.com/hashintel/hash/pull/227. The timestamps inside of the block json files have been updated to cause a rebuild of the blocks and render the example.
`initialWidth` is also updated in a place to increase the width the HASH embed starts with.
> [FE] Rebuild blocks on blockprotocol.org

- site/README.md
- site/src/lib/config.ts
We have a variable, `FRONTEND_URL`, which determines various things including:
- cookie domain
- origin of links sent to users
- endpoint that the API client will call
The variable can be set via user-supplied environment variable, and falls back to the Vercel deployment origin if this isn't present. 
For the third use case, the variable needs to reach the client - this requires prefixing it with `NEXT_PUBLIC_`, which the PR does.
> [SITE] Fix API URL reaching client

- packages/block-template/package.json
- packages/mock-block-dock/package.json
- packages/mock-block-dock/src/MockBlockDock.tsx
- site/package.json
- site/src/components/pages/hub/BlockDataContainer.tsx
There were a couple of bugs on the individual block pages which this PR fixes:
1. `MockBlockDock` was not set up for the block it's wrapping to receive new props after the first render - this meant that edits in the 'data source' input were not reflected in the block (you had to use the block's own editing functionality)
2. `BlockDataContainer` (the thing holding the blocks on their page) did not react to users navigating between blocks, e.g. via the carousel.
This PR fixes both of those things by tracking the previous value for (1) the wrapped block's props, and (2) the block being viewed, respectively.
> Fix block page when switching blocks or data source

- site/src/components/pages/home/Header/index.tsx
**Before**
**After**
---
[Slack thread](https://hashintel.slack.com/archives/C02LG39FJAU/p1643305403659149) _(internal link)_
This change was originally implemented as part of https://github.com/blockprotocol/blockprotocol/pull/141, but I extracted it into a separate PR for fast tracking.
> Fix page width overflow because of background animation

- .github/workflows/check-codebase.yml
Follows #165
I thought I added the script to the yaml, but it was in another repo 😅
> Run `yarn lint:dependency-version-consistency` in CI

- package.json
- packages/block-template/README.md
- packages/block-template/package.json
- packages/mock-block-dock/package.json
- site/package.json
This PR should fix #161.
Unlike `postinstall`, `prepare` only runs in development. See https://docs.npmjs.com/cli/v8/using-npm/scripts.
Unfortunately, Yarn [does not automatically run `prepare` in workspaces](https://github.com/yarnpkg/yarn/issues/3911). We cannot use `yarn workspaces run prepare`, but that would require dummy `prepare` scripts in all packages. Alternatively, we can `yarn lerna run prepare`, but it [has not been maintained](https://github.com/lerna/lerna/issues/2703) for some time.
To keep this PR small, I am running `yarn workspace mock-block-dock run prepare` in top-level `package.json` → `prepare`. We can change the approach later, but it should be good enough for now 🙂
Depending on how our repo setup evolves, we might want to replace `prepare` with `prepublishOnly`. …
> Replace `postinstall` with `prepare` in `mock-block-dock`

- .husky/post-commit
We run `yarn install` after `git commit`, which is useful when cherry-picking. Our `prepare` script got beefier in #173, which made commits quite slow because of a git hook.
When we introduce a monorepo-management tool like Turborepo, we’ll be able to remove package builds from `prepare` and bring the hook back.
> Temporarily disable `post-commit` git hook

- .github/workflows/algolia-upload-index.yml
- scripts/sync-algolia-index.ts
- site/src/components/pages/docs/Search/index.tsx
1. This PR fixes the typo in the GitHub Action yaml file, which means the correct secret will get passed down to the script.
2. The index name inside the action and in the app are updated to `blockprotocol`, so both of them use the actual index.
> [FE] Fix typo in Algolia Action and update index name

- .github/workflows/check-codebase.yml
- .husky/post-commit
- package.json
- packages/block-template/package.json
- packages/block-template/webpack-dev-server.config.js
- packages/create-block-app/create-block-app.js
- packages/create-block-app/package.json
- packages/mock-block-dock/dev/webpack.config.js
- packages/mock-block-dock/package.json
- scripts/packages/mock-publish-to-local-registry.ts
- scripts/packages/publish-to-local-registry.ts
- scripts/packages/smoke-test-create-block-app.ts
- scripts/shared/logging.ts
- yarn.lock
This PR helps complete https://github.com/blockprotocol/blockprotocol/pull/168 and also simplifies further work on the npm packages. It introduces a simple smoke test for `npx create-block-app`, which includes `npm install`, `npm run dev`, `npm run lint:tsc` and `npm run build` inside a new block folder.
- Two new scripts:
- `scripts/packages/publish-to-local-registry.ts`
It publishes `block-template`, `blockprotocol`, `create-block-app` and `mock-block-dock` to `http://localhost:4873`.  Registry address is hardcoded to save us from accidental publishing to the real registry (at least for now).
- `scripts/packages/smoke-test-create-block-app.ts`
It pretty much follows the instructions at https://blockprotocol.org/docs/developing-blocks. This script can work against both local and public …
> Smoke-test npm packages

- site/scripts/build-blocks.sh
- site/src/components/pages/hub/BlockDataContainer.tsx
- site/src/lib/blocks.ts
- site/src/pages/[shortname]/[blockSlug].page.tsx
This PR fixes a couple of assumptions we made about the JSON files describing blocks:
1. Better handles a missing `timestamp` 
2. Allows repo URLs that don't end in .git
It also reverts a change made in #171 to change the `entityId` of a block - `MockBlockDock` doesn't handle this properly and more changes are needed there to prevent crashes if the `entityId` of the block entity is changed from outside.
> Better handle block hub JSON files. Fix switching between blocks.

- site/src/_pages/docs/3_embedding-blocks.mdx
The sample data in the `data-protocol` section used user row with ` entityId` of `41` but the related links example used a `sourceEntityId` of `42` which might be confusing since we're trying to show the way to create related links. This change makes the example data consistent by changing the user row to `42`.
Fixes #176
> Made sample data consistent

- package.json
- scripts/sync-algolia-index.ts
- yarn.lock
We were having issues with [Algolia indexing](https://github.com/blockprotocol/blockprotocol/actions/workflows/algolia-upload-index.yml) recently and it was unclear whether it was because of missing or incorrect env vars. This PR introduces [`envalid`](https://www.npmjs.com/package/envalid?activeTab=versions), which improves script feedback. We can add this library to other scripts as needed.
```ts
const env = envalid.cleanEnv({
EMAIL: envalid.email({ default: "hello@example.com" }),
EMAIL_TRANSPORT: envalid.str({ choices: ["aws", "none"], default: "aws", devDefault: "none" }),
PORT: envalid.port({ default: 3000 }),
});
```
```ts
console.log(typeof env.PORT === 3000); // true
// with PORT=-42 → 💥
console.log(env.EMAIL); // always a valid email
console.log(env.EMAIL_TRANSPORT); // "none" …
```
> Add `envalid` to improve script feedback when env vars are missing

- site/README.md
- site/src/pages/api/blocks.api.ts
The existing blocks API allows users to get a list of all available blocks, and filter them based on:
1. `q`: Which filters by the query string on a set of blockData keys.
2. `json`: Which filters based on the structure of json passed in by the user.
This PR allows filtering based on 3 more data points:
1. `author`: Filter blocks based on block author.
2. `name`: Filter blocks based on either `displayName` or the package name.
3. `license`: Filter blocks based on the type of license that they use.
- Checkout the branch
- Call the API locally, mix and match parameters to see how they combine.
> Note: The Asana task mentions that "Query parameters should be composable / combinable". This PR assumes that all filters will be ANDed, and hence, the order of query parameters doesn't matter. 
--- …
> Allow filtering blocks on more parameters

- site/scripts/create-db-indexes.ts
I noticed that user pages were sometimes loading slowly. This is because we didn't have an index on `shortname` in the user collection.
I've already created this in the database directly - this PR adds the index creation to our script so that we can (a) easily see it's present, and (b) have it recreated if for some reason it's ever removed.
> Add shortname index on user collection

- .eslintrc.js
- scripts/sync-algolia-index.ts
- site/.eslintrc.js
- site/package.json
- site/scripts/generate-blocks-data.ts
- site/scripts/generate-sitemap.ts
- site/src/lib/blocks.ts
- site/src/util/mdxUtils.tsx
With `fs-extra` added in https://github.com/blockprotocol/blockprotocol/pull/210, it’d be nice to use this package consistently. This PR replaces `import ... from "fs"` with `import ... from "fs-extra"` and adds a linting rule that reminds us to not use plain `fs`.
We still have two occurrences of `require("fs")` in `create-block-app` and `block-template`. Those cases are not covered by `no-restricted-imports` in ESLint 8. This is good, because we don’t want to introduce `fs-extra` as a dependency of published packages (at least for now). If we decide to restrict certain paths in `require` in the future, we can install `eslint-plugin-node` and configure [`node/no-restricted-require`](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-restricted-require.md).
> Use `fs-extra` consistenlty

- site/src/lib/blocks.ts
This PR fixes a `404` error encountered on each block page in Vercel deployments of the BP site. This involved reverting a runtime import of `fs-extra` back to using `fs` instead.
> BP site fix block page

- site/src/lib/api/model/user.model.ts
This PR fixes an error that is thrown when the `completeSignup` Next API endpoint is called.
> Fix `completeSignup` error

- site/src/components/Screens/CompleteSignupScreen.tsx
- site/src/components/Screens/SendLoginCodeScreen.tsx
- site/src/components/Screens/SignupScreen.tsx
- site/src/components/Screens/VerificationCodeScreen.tsx
- site/src/lib/api/model/user.model.ts
- site/src/lib/apiClient.ts
This PR changes how Next API errors are handled in the `ApiClient`, and which errors are displayed to the user. Changes include:
- modifying the `handleAxiosError` method to stop throwing some errors. Instead all errors are now returned by the `ApiClient` methods, so that these can be handled by the caller.
- for every axios error a default error message is parsed and attached to the error object, so that this logic can be reused by callers of the api client.
- the `CompleteSignupScreen` has been updated to display errors thrown by the `completeSignup` request. Previously when an error occurred it would be stuck in the loading state indefinitely, preventing the user from retrying to submit the form for instance when a network error is encountered.
Other changes made as part of this PR:
- …
> BP site display server errors to user

- package.json
- yarn.lock
Author of `check-dependency-version-consistency` [implemented](https://github.com/bmish/check-dependency-version-consistency/pull/343) my [feature request](https://github.com/bmish/check-dependency-version-consistency/issues/332) 🎉
We are now protected against wrong version numbers for our own packages, a mistake I have made before. Here is the `yarn lint` output if I change `blockprotocol` version to `0.4.2` in `block-template` → `package.json`:
Same PR in the HASH repo: https://github.com/hashintel/hash/pull/318
> Upgrade `check-dependency-version-consistency` to v2

- packages/blockprotocol/core.d.ts
- site/src/components/pages/hub/BlockDataContainer.tsx
- site/src/components/pages/hub/BlockVariantsTabs.tsx
#202 introduced the ability to handle block 'variants' in the block hub.
There were a couple of cases not handled which this PR addresses:
1. Where a block has an empty `variants` array - the index access is now checked
2. When a block has variants, but no example defined for the variant - this now falls back to the root example
We also intend to start using `name` instead of `displayName` for the variant's name. This PR handles blocks that still use the old `displayName` (we can remove it after a while).
> Fix handling of variants/examples combinations in block hub

- site/src/_pages/docs/4_faq.mdx
- site/src/_pages/spec/1_block-types.mdx
This expands the docs to explain the two different types of schema crosswalking we anticipate being necessary when working with blocks & schemas.
The description in the docs should be sufficient to explain the two, so I won't elaborate here. If it isn't, I'll need to expand further.
> Explain different types of schema crosswalking

- site/src/components/BlockCard.tsx
- site/src/components/Footer.tsx
- site/src/components/InfoCard/InfoCard.tsx
- site/src/components/MdxPageContent.tsx
- site/src/components/Navbar.tsx
- site/src/components/pages/hub/BlockDataContainer.tsx
- site/src/components/pages/hub/BlockDataTabs.tsx
- site/src/components/pages/hub/BlockTabsModal.tsx
- site/src/components/pages/hub/BlockVariantsTabs.tsx
- site/src/pages/dashboard.page.tsx
- site/src/pages/docs/[[...docsSlug]].page.tsx
- site/src/pages/hub.page.tsx
- site/src/pages/spec/[[...specSlug]].page.tsx
- site/src/theme/components/dataDisplay/MuiTypographyThemeOptions.ts
- site/src/util/mdxComponents.tsx
This PR makes the following style fixes:
- [BP hub: fix centering of sub-heading](https://app.asana.com/0/1201472294283826/1201768159094211)
- [Remove underline from Footer navigation links and change hover color](https://app.asana.com/0/0/1201781321575581)
- [Ensure bottom padding on pages is at least equal to top (see attached)](https://app.asana.com/0/0/1201589261424242)
- [fix Footer "HASH" button hover color](https://app.asana.com/0/0/1201781321575583)
- [Centre align text on block hub](https://app.asana.com/0/0/1201781323994489)
- [Adjust hover scale size on block cards](https://app.asana.com/0/0/1201781323994492)
- [Fix login button in mobile menu](https://app.asana.com/0/0/1201822597391098)
- [Change link colour in blue callout blocks to …
> BP Site styling tweaks

- scripts/packages/smoke-test-create-block-app.ts
Potentially fixes flaky smoke tests ([example](https://github.com/blockprotocol/blockprotocol/runs/5319952974?check_suite_focus=true))
[Slack thread](https://hashintel.slack.com/archives/C02LG39FJAU/p1645717210124629) & [Asana task](https://app.asana.com/0/1200211978612931/1201883594890019/f) (internal)
> Increase `waitOn` timeout in package smoke tests

- site/src/components/pages/user/UserPageComponent.tsx
[Asana task](https://app.asana.com/0/1200211978612931/1201907149831297/f) (internal)
This PR provides a quick hotfix for the user profile page (`blockprotocol.org/@user`). It removes an ‘infinite `useEffect` loop’ which triggers endless calls to `getServerSideProps`. This resets scroll position via endless `router.push` calls.
Although this PR fixes the above problems, we still need a better fix (I am working on it). Current implementation does not support browser navigation (back & forward) and does not allow us to open tabs in a new window too (by using ctrl+click). I will submit a proper fix a bit later as it requires some refactoring. This PR can help in the meantime.
> Hotfix scrolling and performance issues on profile page

- .eslintrc.js
- hub/@hash/table.json
- packages/blockprotocol/core.d.ts
- packages/mock-block-dock/package.json
- packages/mock-block-dock/src/MockBlockDock.tsx
- packages/mock-block-dock/src/data/entities.ts
- packages/mock-block-dock/src/data/entityTypes.ts
- packages/mock-block-dock/src/useLinkFields.ts
- packages/mock-block-dock/src/useMockDatastore.ts
- packages/mock-block-dock/src/util.ts
- site/package.json
- yarn.lock
This expands `mock-block-dock`'s functionality to include `linkedAggregations`, `aggregateEntities` and `aggregateEntityTypes`. The table block and similar depend on these functions.
It also updates `updateLinks` function to handle how we're currently updated linked aggregations, which are identified by fields other than `linkId` - we intend to change this so that
(a) linked aggregations are in fact identified by a `linkId`, and 
(b) have separate CRUD operations for linked aggregations vs links to single entities, to save the kind of branching seen here.
— so this will change again soon once we've worked through that.
Other changes:
- add mock entity types
- update `no-redeclare` linting rule to the TS version to allow function overloads
- remove obsolete scripts in `package.json`
- …
> Add aggregation handling to mock-block-dock

- site/scripts/prepare-blocks.ts
- site/src/lib/blocks.ts
- site/src/pages/[shortname]/blocks/[blockSlug].page.tsx
The blockprotocol website presently only builds blocks which are in the GitHub URL format, ie, `https://github.com/user/repository`. However, users should be free to add any npm-supported repository link, as long as we can parse it. 
Hence, this PR allows blockprotocol to do just that, by utilizing the `npm/hosted-git-info` package. We use it to get the source URL from any repository URL, and use it to download and build the blocks.
Run `yarn build` locally, or have a look at the CI output below.
---
- https://app.asana.com/0/0/1201934058330698
> Accept all npm-supported repository URLs in blocks

- .github/workflows/algolia-upload-index.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/labeler.yml
- .github/workflows/warm-up-vercel.yml
- site/src/pages/[shortname]/[[...profileTabs]].page.tsx
- site/src/pages/[shortname]/index.page.tsx
This PR speeds up TTFB for pages like `/@hash` or `/types/UUID`. This is done via:
- **Pro-active page warm-ups with a new GitHub workflow**
This trick significantly  reduces TTFB. See diff comment for details. Related discussions:
- https://github.com/vercel/vercel/discussions/6878
- https://github.com/vercel/vercel/discussions/5422
Pipeline example: https://github.com/blockprotocol/blockprotocol/actions/runs/1956402602
Event docs (used in a new GitHub workflow):
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#deployment_status
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
- https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#deployment_status
- **Replacing …
> Speed up profile page on Vercel

- .github/workflows/warm-up-vercel.yml
This PR follows #250. It makes sure that we warm up `blockprotocol.org/*` instead of `blockprotocol-*-hashintel.vercel.app/*` once a PR is merged into `main`.
I have noticed that fetching a permalink domain does not warm up the main domain for some reason. Maybe it was a co-incidence of some sort, but might be worth fixing. ATM, `blockprotocol.org` pages seem to remain cold till they are refetched on schedule.
> Improve how Vercel Lambdas are warmed up

- site/src/components/pages/hub/BlockDataContainer.tsx
- site/src/components/pages/hub/HubUtils.tsx
- site/src/pages/[shortname]/blocks/[blockSlug].page.tsx
We currently assume that:
1. Blocks are React components
2. They are the default export from the entry source file
We should implement support for non-React components as they are submitted – until we decide on a prescribed interface for the component. This PR throws an error if something that definitely isn't a React component is encountered, so that the problem is explicit and can be addressed.
We should also handle non-default exports. This PR does that, at least for (1) named `App` exports, and (2) named exports where they are the only one in the file. Since we can't reliably detect other patterns.
[Asana task](https://app.asana.com/0/1200211978612931/1201955153125192/f) (_internal_)
> Handle non-default block exports, detect non-React

- packages/block-template/package.json
- packages/block-template/webpack-block-metadata-plugin.js
- packages/block-template/webpack-main.config.js
A couple of fixes to `block-template`, which will need publishing after merging:
1. Feed `externals` properly from `peerDependencies` (following on from counterpart https://github.com/hashintel/hash/pull/398)
2. More reliable detection of the main source entry point (there was a false positive on a `main.[hash].js.LICENSE.txt` that ended up in a build)
3. remove `twind` from dependencies
[Asana task](https://app.asana.com/0/1201864704093982/1201953502543830/f) _(internal)_
> Fix block-template externals and main source file detection

- hub/@hash/callout.json
- hub/@hash/code.json
- hub/@hash/divider.json
- hub/@hash/embed.json
- hub/@hash/header.json
- hub/@hash/image.json
- hub/@hash/paragraph.json
- hub/@hash/person.json
- hub/@hash/table.json
- hub/@hash/video.json
- site/scripts/prepare-blocks.ts
This PR updates block commit hashes to publish changes in https://github.com/hashintel/hash/pull/398 and https://github.com/hashintel/hash/pull/399
\+ see a [small bonus](https://github.com/blockprotocol/blockprotocol/pull/258#discussion_r824829920)
> Update HASH blocks

- packages/block-template/package.json
- packages/mock-block-dock/package.json
- site/package.json
- site/src/components/MdxPageContent.tsx
- site/src/components/Modal/CreateSchemaModal.tsx
- site/src/components/PageSidebar.tsx
- site/src/components/entityTypes/SchemaEditor/schemaEditorReducer.ts
- site/src/components/hooks/useVerificationCodeTextField.ts
- site/src/components/pages/docs/Search/index.tsx
- site/src/components/pages/home/Section2/Steps.tsx
- site/src/lib/api/middleware/multipartUploads.middleware.ts
- site/src/lib/api/model/apiKey.model.ts
- site/src/lib/blocks.ts
- site/src/pages/[shortname]/blocks/[blockSlug].page.tsx
- site/src/pages/[shortname]/types/[title].page.tsx
- site/src/pages/spec/[[...specSlug]].page.tsx
- site/src/util/mdxUtils.tsx
- site/tsconfig.json
- tsconfig.base.json
- yarn.lock
The main purpose of this PR is to add [`"noUncheckedIndexedAccess"`](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) to our repo‘s `tsconfig`. I have also upgraded TS from 4.5 to 4.6 given the opportunity. See [release announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-4-6/).
Most cases of unchecked indexes are ‘fixed’ by adding `!`. This means we can still get runtime errors for the existing code, and if we do, we can refactor it case-by-case. Newly written code will be better type-checked from now on. In general, we should avoid `!` as much as possible.
- [Asana task](https://app.asana.com/0/0/1201950599278304) _(internal)_
- [Slack thread](https://hashintel.slack.com/archives/C022217GAHF/p1645736187865989) _(internal)_
- …
> Bump TS to 4.6.2, enable `noUncheckedIndexedAccess`

- .github/workflows/warm-up-vercel.yml
This quick PR is a by-product of https://github.com/vercel/community/discussions/496.
[Asana task](https://app.asana.com/0/1200211978612931/1201962884263629/f) _(internal)_
Although the homepage is static, we see a pretty annoying layout shift in the header because `/api/me` takes ~10 seconds to complete.
↓
Example:
https://user-images.githubusercontent.com/608862/159029217-e4769c0d-89c5-49de-aede-ffe879eab090.mp4
By warming-up `/api/me` like two other pages, we reduce the probability of this issue. We still have plenty of API routes that are not warmed up, but they are less critical. If there’s no luck with https://github.com/vercel/community/discussions/496, we can implement a script that lists files in `site/pages/api` and thus automatically pokes all API routes.
> Add `/api/me` to the list of routes to warm up

- site/src/lib/api/handler/apiKeyRequiredHandler.ts
- site/src/lib/api/handler/baseHandler.ts
This PR does some pre-work for https://github.com/hashintel/hash/pull/407, allowing the BlockProtocol `/blocks` API to be accessible from all clients. This is done so that a client which consumes BlockProtocol blocks with an appropriate API key isn't blocked by CORS errors while trying to fetch the desired data.
An optional `isPublicApi` option is added to `createBaseHandler` [here](https://github.com/blockprotocol/blockprotocol/pull/273/files#diff-bf353d5aba9cfe2a44444fb44f092418bf23327517de62a90af518a061ac1583R32) to optionally allow an API to be accessible from all CORS sources.
---
- https://app.asana.com/0/0/1201997200034318
> Allow APIs to optionally be made public

- packages/block-template/README.md
- packages/block-template/package.json
- yarn.lock
We mention the `yarn serve` command in the `block-template` README, but this command has been lost from the `package.json` scripts somewhere along the way.
This PR restores it. It is useful to serve blocks locally for testing, e.g. in the HASH app.
> Add serve command to block-template

- packages/blockprotocol/core.d.ts
- site/src/lib/blocks.ts
- site/src/pages/[shortname]/blocks/[blockSlug].page.tsx
- site/src/pages/api/blocks.api.ts
This PR is a follow-up to https://github.com/hashintel/hash/pull/407, to fix the temporary solutions defined there. This PR: 
1. Returns absolute URLs for icons.
2. Returns a unique `componentId` for each block.
So that any BlockProtocol client can use these details directly. The icons are used in the clients to display a block's icon, while the `componentId` is used to uniquely identify a block in the hash app, and can also be used as a key for objects storing block data.
Changes described in the GH comments below.
---
- https://app.asana.com/0/0/1201988634400654
- https://app.asana.com/0/0/1202003755787889
- https://app.asana.com/0/0/1201988634400672
> Update Blocks API to return icon URLs and unique IDs 

- hub/@hash/table.json
Set commit to when https://github.com/hashintel/hash/pull/462 was introduced.
Also incorporates fixes from https://github.com/hashintel/hash/pull/413
> Update table block version

- .github/workflows/check-codebase.yml
- scripts/packages/publish-to-local-registry.ts
This PR fixes ‘NPM Packages’ CI which has been failing for about two weeks now.
We define `node-version: 16` in `actions/setup-node@v2`, which gives us the latest Node version. The CI started failing after 16.14.0 got auto-replaced with 16.14.2. These two Node versions come with different NPM versions: 8.3.1 and 8.5.0.
Downgrading NPM from 8.5.0 to 8.4.1 (and 8.3.0, 8.4.0) fixes the problem even without having to downgrade Node itself. Upgrading NPM 8.5.0 to 8.6.0 (the latest at the time of writing) does not fix the issue.
Looking at CI logs, here is one subtle difference that looks a bit odd:
`npm 8.3.1 / 8.4.0 / 8.4.1`
```
=========================================================
Unpublish block-template from local registry (if present) …
```
> Fix ‘NPM Packages’ CI by downgrading NPM to 8.4.1

- packages/block-template/package.json
- packages/blockprotocol/core.d.ts
- packages/blockprotocol/package.json
- packages/mock-block-dock/package.json
- site/package.json
- site/src/_pages/spec/1_block-types.mdx
This corrects an oddity where the `BlockVariant` type required `icon` and `description`, where these are optional in the block metadata as a whole.
Correcting this avoids users of the type relying on the property where it may not exist. The spec has also been updated to clarify.
> Make more block variant types nullable

- .github/workflows/warm-up-vercel.yml
Our [Warm up Vercel](https://github.com/blockprotocol/blockprotocol/actions/workflows/warm-up-vercel.yml) workflow is occasionally failing with the following output:
```
Run cat << EOF > curl-format.txt
https://blockprotocol-mtco3evop-hashintel.vercel.app/@hash
Status code: 200
Time: 19.349816
https://blockprotocol-mtco3evop-hashintel.vercel.app/api/me
Status code: 000
Time: 75.022621  
Error: Process completed with exit code 35.
```
Searching for `curl exit code 35` suggests that this may be to do with TLS or a firewall. Adding `npx `[`retry-cli`](https://www.npmjs.com/package/retry-cli) may help. I’ve used default options, which means 10 retries with `1, 2, 4...` seconds in between. Let’s see what happens, but hopefully we’ll see fewer false alarms in CI. ❌ → ✅
> Use `npx retry-cli` in ‘Warm up Vercel‘ CI

- site/src/_pages/spec/1_block-types.mdx
Introduces `labelProperty` and `configProperties` to the spec as potential additions for entity schemas, and block schemas, respectively.
> Add labelProperty and configProperties to spec

- packages/block-scripts/config/generate-base-webpack-config.cjs
- packages/block-scripts/package.json
- packages/block-scripts/shared/serve-dist.js
- packages/block-template/package.json
- packages/mock-block-dock/package.json
- site/package.json
- yarn.lock
This PR is based off my own experience in https://github.com/hashintel/hash/pull/470.
- Fix `cors` in `yarn serve`
- Produce `main.js` instead of `main.[hash].js` in dev mode to fix built-in `serveDist`
- Add built-in support for CSS and SASS (devs still need to install `sass` package separately [like in Next.js](https://nextjs.org/docs/basic-features/built-in-css-support#sass-support))
- Bump `mock-block-dock` to make sure we are including the latest blockprotocol in the block template
- Allow custom babel plugin via `block-scripts/babel` preset (needs more time to be developed and reviewed)
- Continuous generation of `block-metadata` and `block-schema` in dev
- Make sure exit code is not zero when `yarn build` fails
> Fix a few issues in `block-scripts`

- packages/block-template/package.json
I published `block-template` together with `block-scripts` from #291. Because I forgot to remove some temp CSS, the template accidentally got [`index.css` with green page background](https://unpkg.com/browse/block-template@0.0.10/src/index.css).
I have already published [0.0.11 without this file](https://unpkg.com/browse/block-template@0.0.11/src/), so the fix is out there. This PR makes sure we have the correct latest version in the repo too.
> Bump block-template version

- packages/block-scripts/package.json
- packages/block-template/package.json
#293 made `block-scripts` and `block-template` dependent on a newer version of `mock-block-dock`, but it did not increase their own version numbers.
This PR does that – I will publish a new version of each after merging.
> Bump block-scripts and block-template version numbers

- packages/block-scripts/package.json
- packages/block-scripts/scripts/build.js
- packages/block-scripts/scripts/dev.js
- packages/block-scripts/shared/generate-base-webpack-config.js
- packages/block-scripts/shared/generate-dist-block-metadata.js
- packages/block-scripts/tsconfig.json
- packages/block-template/package.json
Continues #295 
In scope
- Limit number of webpack chunks to 1 to avoid issues with `require()`
- Watch for changes in `block-schema.json`, `package.json`, `public/**/*" and `README.md` in dev
- Add `block-metadata.json` → `builtAt`. We can use this for hot reloading in the embedding apps (alternative suggestions are welcome)
- Check `block-scripts` package with `tsc` (this is possible despite using `*.js`)
> Further improve `block-scripts`

- site/src/components/Screens/CompleteSignupScreen.tsx
#298 updated the casing of API routes, but missed one instance of  `camelCase` in the signup route - this is my bad, I thought I had tested everything in reviewing, but obviously didn't.
Once this is deployed I will email affected users to let them know they can complete sign up.
> Fix complete signup route

- packages/block-scripts/package.json
- packages/block-scripts/scripts/dev.js
- packages/block-scripts/scripts/serve.js
- packages/block-template/package.json
This PR ensures [`Cache-Control: no-store`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#no-store) in `block-scripts`‘s `yarn dev` and `yarn serve`. This improves DX.
`yarn dev`
`yarn serve`
---
- https://app.asana.com/0/0/1202203992095715
> Ensure `Cache-Control: no-store` header in `block-scripts`

- packages/mock-block-dock/src/MockBlockDock.tsx
In the mock data in `mock-block-dock`'s datastore, we currently default to an `accountId` of `"accountId"` if none is provided to the component. 
This could be confusing if a user is supplying their own `initialEntities`, without accountIds, since the block entity will silently gain an `accountId` which doesn't match the entities in the datastore, causing queries for other entities/types to fail if they pass the `accountId` the block is given. 
This change removes the default `accountId` to leave management of the mock `accountId` entirely in the hands of the user.
We could alternatively also give a default `accountId` to any `initialEntities` which require it, but it feels preferable to leave it up to the user, so they can more easily debug/control it. 
N.B. I already published this as …
> Don't add an accountId to mock-block-dock if none is provided

- site/scripts/prepare-blocks.ts
Running `df -h` during Vercel build shows this amount of free disk space:
```
Filesystem      Size  Used Avail Use% Mounted on
overlay          30G   18G   11G  64% /
tmpfs            64M     0   64M   0% /dev
shm             7.7G     0  7.7G   0% /dev/shm
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/nvme1n1     30G   18G   11G  64% /etc/hosts
tmpfs           7.7G     0  7.7G   0% /proc/acpi
tmpfs           7.7G     0  7.7G   0% /sys/firmware
```
After downloading a copy of HASH repo and installing dependencies in it, we end up with significantly less space:
```diff
- overlay          30G   18G   11G  64% /
+ overlay          30G   22G  6.1G  79% /
```
This delta is the size of yarn cache plus the size of the repo contents plus the size of installed node modules.
When we …
> Fix cold Vercel builds

- site/src/pages/[shortname]/blocks/[block-slug].page.tsx
- site/src/pages/hub.page.tsx
- site/src/pages/index.page.tsx
This PR follows https://github.com/blockprotocol/blockprotocol/pull/331 and improves UI consistency. Hidden blocks are no longer shown in `<BlocksSlider />` (both on the home page and on the block page). Hidden blocks are still available via direct URLs and are still embeddable.
> Call `excludeHiddenBlocks()` in two more places

- packages/@blockprotocol/core/package.json
- packages/@blockprotocol/graph/package.json
Related to #333 
This PR replaces all usage of `;` operators with `&&` in the new @blockprotocol/core and @blockprotocol/graph package scripts so they can be run on Windows.
[Asana Task](https://app.asana.com/0/1202250835094699/1202405291899977/f)
> Package scripts fix for Windows

- packages/block-template/src/base.module.scss
In https://github.com/blockprotocol/blockprotocol/pull/342 we set the wrong names for extra large font sizes. These are now `2xl` and `3xl`.
> Fix names of font sizes

- site/src/components/pages/hub/sandboxed-block-demo.tsx
[Asana task](https://app.asana.com/0/1201095311341924/1202435310568394/f) _(internal)_
[The iframe allow attribute on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy#the_iframe_allow_attribute)
1.  Open `@hash/blocks/code` ([main](https://blockprotocol.org/@hash/blocks/code) | [preview](https://blockprotocol-851k5l09n-hashintel.vercel.app/@hash/blocks/code)) in Chrome (FF and Safari work fine already)
1.  Press _Copy_
1.  Before (main): ```app.tsx:120 DOMException: The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.```  
After (preview):  📋 ☑️
> Add `allow="clipboard-write"` to `iframe`

- site/src/components/mdx-page-content.tsx
It fixes weird scrolling behaviour when clicking on a tab under the `/docs` page.
We have custom scrolling logic with some gated conditions to try and handle when to scroll to a given anchor when changing pages. This was implemented in #179. The tabs push a new route to something _without_ an anchor though, which was causing weird scrolling to one of the other headings. 
I've fixed this by adding a new condition (checked first) where if the anchor part of the route is "" (e.g. there's no heading in the URL) **and** the previous logic for deciding if it _should scroll_ is true, then it scrolls to the top of the page (rather than some other incorrect anchor's position).
You can see this problem on the [current site](https://blockprotocol.org/docs/) by clicking on one of the tabs (for …
> Fixing scrolling on docs when clicking on a tab

- packages/blockprotocol/package.json
- packages/react-block-loader/README.md
- packages/react-block-loader/package.json
- site/next.config.js
- site/src/_pages/spec/0_index.mdx
- site/src/_pages/spec/1_core-specification.mdx
- site/src/_pages/spec/2_graph-service-specification.mdx
- site/src/_pages/spec/3_rfcs_and_roadmap.mdx
- yarn.lock
A few small tweaks:
1. redirect `/spec/block-types`, since the path no longer exists
2. add `0.2` to specs and mention why in overview
3. bump `blockprotocol` package (now deprecated) to `0.0.11` to publish with new README
4. move Entity types RFC to correct section
5. Add warning to `react-block-loader`  that it needs updating to 0.2
> Spec tweaks & redirect

- site/src/theme/components/navigation/mui-breadcrumbs-theme-options.ts
- site/src/util/mdx-components.tsx
- site/src/util/mdx-utils.tsx
The docs sidebar is too granular right now. This makes it a bit easier to work with. 
This also fixes the breadcrumbs by removing the max width on them, and also removing the direct linking to h4s.
> Remove h4s from the sitemap

- packages/create-block-app/create-block-app.js
- packages/create-block-app/package.json
`create-block-app` attempts to update bits of metadata in `package.json["blockprotocol"]`, which are then used to generate `block-metadata.json` at build time.
The new HTML template doesn't have automatic `block-metadata.json` creation, and thus doesn't have the `blockprotocol` object in `package.json` – since we only use that as a staging ground for data we pull to create `block-metadata.json` - and this was causing a crash in `create-block-app block --template html`, because the script assumed that `blockprotocol` was present.
This PR fixes that and sets a few bits of metadata for HTML blocks. I've already published the fix.
> Fix metadata updates in create-block-app for html blocks

- hub/@hash/callout.json
- hub/@hash/code.json
- hub/@hash/divider.json
- hub/@hash/embed.json
- hub/@hash/header.json
- hub/@hash/image.json
- hub/@hash/paragraph.json
- hub/@hash/person.json
- hub/@hash/table.json
- hub/@hash/video.json
- hub/@timdiekmann/countdown.json
- hub/@timdiekmann/timer.json
- hub/@tldraw/drawing-canvas.json
This PR updates commits on the HASH blocks so that they get the revised READMEs introduced in https://github.com/hashintel/hash/pull/657 - these READMEs now display on their page on the hub.
> Update block commits

- .github/workflows/algolia-upload-index.yml
- scripts/sync-algolia-index.ts
- site/scripts/sync-algolia-index.ts
The Algolia search indexing assumed that the `spec` would be in its folder, but it's been moved to a subfolder of `docs` in https://github.com/blockprotocol/blockprotocol/pull/365
This PR fixes the Algolia script to account for this.
The script needs more work, particularly to get better search result specificity and highlighting from Algolia - we may want to index individual _sections_ of documents rather than the whole thing. For a future PR.
**Note**: I have already re-indexed the production index to ensure the correct results are showing. This workflow only runs on `main`. To test it, run it locally, amending the index to `blockprotocol-testing`.
> Fix Algolia search indexing

- site/src/components/navbar.tsx
Support for `Object.hasOwn` was only [introduced to Safari in March 2022](https://caniuse.com/mdn-javascript_builtins_object_hasown) in version 15.4. 
This means that blockprotocol.org currently crashes when visited with an older version of Safari.
The PR replaces uses of `Object.hasOwn` to fix this.
> Fix: don't use object.hasOwn

- site/src/_pages/docs/0_index.mdx
- site/src/_pages/docs/1_developing-blocks.mdx
- site/src/_pages/docs/3_spec/0_index.mdx
- site/src/_pages/docs/4_faq.mdx
This PR fixes several broken links in the specification, which relied on a redirect defined in `next.config.js` to work.
> Fix broken links in specification

- hub/@hash/callout.json
- hub/@hash/code.json
- hub/@hash/divider.json
- hub/@hash/embed.json
- hub/@hash/header.json
- hub/@hash/image.json
- hub/@hash/paragraph.json
- hub/@hash/person.json
- hub/@hash/table.json
- hub/@hash/video.json
- hub/@timdiekmann/countdown.json
- hub/@timdiekmann/timer.json
- hub/@tldraw/drawing.json
This is a follow up to #390 bumping all existing blocks to make use of the changed webpack config.
> Bump all HASH blocks

- hub/@hash/callout.json
- hub/@hash/code.json
- hub/@hash/divider.json
- hub/@hash/embed.json
- hub/@hash/header.json
- hub/@hash/image.json
- hub/@hash/paragraph.json
- hub/@hash/person.json
- hub/@hash/table.json
- hub/@hash/video.json
- hub/@thehabbos007/calculation.json
- hub/@timdiekmann/countdown.json
- hub/@timdiekmann/timer.json
- hub/@tldraw/drawing.json
This PR adds the calculation block to the hub. It also bumps other HASH block commit ids to make it easier to search/replace later.
> Add calculation block to the hub

- README.md
- packages/block-template/templates/custom-element/README.md
- packages/block-template/templates/html/README.md
- packages/block-template/templates/react/README.md
- packages/react-block-loader/README.md
- packages/react-block-loader/src/web-component-block.tsx
This PR complements https://github.com/hashintel/hash/pull/722. It addresses [Asana task](https://app.asana.com/0/1202482456346912/1202440221033864) (internal).
> Replace outdated links to `/spec` and `/docs`

- packages/block-template/package.json
I forgot to bump the version of `block-template` in https://github.com/blockprotocol/blockprotocol/pull/405 which is necessary to make `create-block-app` work. This PR fixes that
> Bump block template

- site/scripts/sync-algolia-index.ts
- site/src/lib/sitemap.ts
- site/src/util/mdx-utils.tsx
- [GitHub Action](https://github.com/blockprotocol/blockprotocol/actions/workflows/algolia-upload-index.yml) (recent runs are broken)
- [Slack thread](https://hashintel.slack.com/archives/C02LG39FJAU/p1656959701248679) (internal)
- [Asana task](https://app.asana.com/0/1202482456346915/1202552815181141/f) (internal)
Historically, Þ markdowns have two distinct categories: `docs` and `spec`. Our `sync-algolia-index.ts` script used to process them separately, which added some complexity to the logic. As the structure of the docs were changing, the script received several incremental patches and became quite hard to follow. It broke after https://github.com/blockprotocol/blockprotocol/pull/410 got merged.
This PR simplifies `sync-algolia-index.ts` thus fixing the bug that was causing a crash …
> Fix Algolia indexing

- .github/workflows/release.yml
Follows #420
Fixes https://github.com/blockprotocol/blockprotocol/runs/7235813803?check_suite_focus=true#step:1:35
```
Error: Unable to resolve action `changesets/action@1.3.0`, unable to find version `1.3.0`
```
`v` prefix should help match repo tags at https://github.com/changesets/action/tags. I'm using a pinned version because of:
https://github.com/blockprotocol/blockprotocol/blob/9c38dcd0f8c2f843bd7276bd42e1fea9833b4a2f/.changeset/config.json#L13-L15
> Fix a typo in action version

- site/src/lib/config.ts
- site/src/pages/[shortname]/blocks/[block-slug].page.tsx
We changed Preview Deployment Suffix from `.vercel.app` to `.stage.hash.ai`, which [broke sandbox in preview releases](https://blockprotocol-1jo2v6kgs.stage.hash.ai/@alfie/blocks/github-pr-overview). This PR updates how we generate sandbox URLs, which fixed the issue.
- [Asana task](https://app.asana.com/0/1202542409311090/1202621858687201/f) (internal)
- [Slack thread](https://hashintel.slack.com/archives/C02LG39FJAU/p1658172223332219) (internal)
- [Vercel docs](https://vercel.com/docs/concepts/deployments/generated-urls#url-components) on URL format
- [Demo](https://blockprotocol-8udk0nx99.stage.hash.ai/@hash/blocks/code)  
sandbox host = `blockprotocol-git-ak-fix-block-sandbox-url-in-preview-de-825d26.stage.hash.ai` (note the hash)
There is still a small chance that the new logic will …
> Fix block sandbox URL in preview deployments

- .github/actions/warm-up-repo/action.yml
- .github/workflows/algolia-upload-index.yml
- .github/workflows/ci.yml
- .github/workflows/publish-npm-packages.yml
- .github/workflows/release.yml
- .github/workflows/site-deployment.yml
The goal of this PR is to optimise `yarn install` performance in jobs that don’t involve Playwright (which is the majority of them). `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` is now implicitly  set to `false` by default in all workflows. This is done via a newly introduced GitHub action. The new action also makes sure that workflows are aligned on node version and yarn cache.
Inspired by: https://github.com/hashintel/hash/tree/main/.github/actions/warm-up-repo
> Introduce local `warm-up-repo` action to reliably skip Playwright installs

- .github/workflows/algolia-upload-index.yml
Caused by #440. Example error: https://github.com/blockprotocol/blockprotocol/runs/7408512664?check_suite_focus=true#step:2:1
```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/blockprotocol/blockprotocol/.github/actions/warm-up-repo'.
Did you forget to run actions/checkout before running your local action?
```
I haven’t spotted this issue in the original PR because this workflow only runs for `main`.
> Fix Algolia workflow

- .github/workflows/ci.yml
- patches/playwright-core+1.24.0.patch
- site/package.json
- site/playwright.config.ts
- site/src/components/pages/dashboard/api-key-renderer.tsx
- site/tests/integration/api-key-generation.test.ts
- site/tests/integration/dashboard.test.ts
- site/tests/integration/login-flow.test.ts
- site/tests/shared/fixtures.ts
- site/tests/shared/nav.ts
- yarn.lock
In scope
- Dashboard page accessibility for guests and logged in users
- Dashboard page key elements and links
- API key page key elements
- API key page key generation
- API key page key re-generation
- API key page key modal edge cases
- Reusable API-based login flow that skips UI (to be used in tests)
- Playwright 1.24
Out of scope
- Type generation from the dashboard
> Add integration tests for Dashboard and API key generation

- site/src/_pages/docs/3_spec/1_core-specification.mdx
The markdown for a link in core specification is incorrect. This PR fixes that.
> Fix incorrect link formatting

- site/tests/integration/api-keys.test.ts
In scope:
- Check results of `/api/blocks` with various `x-api-header` values
Out of scope:
- Split one test into two: API key UI & API key endpoints (low priority)
- [Investigate why Þ/site/pages/api/*.api.ts are missing in coverage report](https://app.asana.com/0/1202538466812818/1202652337622582/f) (internal)
> Implement integration tests for /api/blocks

- .github/workflows/ci.yml
- .nycrc.json
- site/package.json
- yarn.lock
I was [documenting](https://app.asana.com/0/1200211978612931/1202644137081309/f) integration tests and noticed two issues with reported coverage. This PR fixes them.
- We used `npx kill-port 3000` in CI, which stopped `next start` with SIGKILL instead of SIGINT. Abrupt process termination meant that the runtime coverage was not reported. I have temporarily replaced `yarn kill-port` with `kill -2` (i.e. SIGKILL with SIGINT). We can switch back when https://github.com/tiaanduplessis/kill-port/issues/48 is closed upstream.
↑ this change **increased** reported code coverage
- We did not have `@istanbuljs/nyc-config-typescript` in `.nycrc.json`, which caused some source files to be missing from the list of all files. In particular, all `site/src/pages/api/**.ts` files were not included into …
> Fix coverage stats

- site/src/components/mdx/mdx-page-content.tsx
- site/src/pages/_app.page.tsx
This fixes the error in console that comes up when
- user navigates to any of the docs page from the footer of a `non-doc` page
- user tries to scroll fast on a long docs page (e.g /docs/developing-blocks)
We have 3 handlers in the docs page that affect scrolling and in some scenarios they might clash, leading to the error.
- Nextjs default scroll to top functionality
- An effect that updates the url as user scrolls down the page
- An effect that detects changes to the url and scrolls to the relevant section where possible. 
This PR fixes the issue by trying to prevent the clashes from happening
Before
https://user-images.githubusercontent.com/16928688/181187538-84cda03f-df1e-4e6a-adf5-5ad41b46d505.mov
After
https://user-images.githubusercontent.com/16928688/181187914-6cd6d1c6-c34b-4719-a1 …
> Fix footer navigation bug

- hub/@alfie/github-pr-overview.json
- hub/@hash/callout.json
- hub/@hash/code.json
- hub/@hash/divider.json
- hub/@hash/embed.json
- hub/@hash/header.json
- hub/@hash/image.json
- hub/@hash/paragraph.json
- hub/@hash/person.json
- hub/@hash/table.json
- hub/@hash/video.json
- hub/@thehabbos007/calculation.json
- hub/@timdiekmann/countdown.json
- hub/@timdiekmann/timer.json
- hub/@tldraw/drawing.json
[#859](https://github.com/hashintel/hash/pull/859) updated blocks in [hash repo](https://github.com/hashintel/hash). This bumps the commit hash of the blocks there
> Bump blocks

- site/src/components/modal/login-modal.tsx
- site/src/components/screens/send-login-code-screen.tsx
- site/tests/integration/login-flow.test.ts
[Asana task](https://app.asana.com/0/1200211978612931/1202629133807661/f) (internal)
The bug was discovered while working on https://github.com/blockprotocol/blockprotocol/issues/452
We hide login modal with a fade-out effect. When we press close, _Email address_ field is unfocused and automatically focused again while the modal is fading. This causes an odd scroll jump in Webkit browsers (both in Playwright and on macOS / iOS).
https://user-images.githubusercontent.com/608862/181071370-436b55f5-9e3f-4161-b167-eb205a31b15c.mp4
Because scrolling the page down hides the top menu, `login-flow` test often fails for Safari and iPhone. It can pass, but only if the header menu is pressed very quickly, before it animates away.
This PR marks the email input field as disabled while the modal is …
> Fix login modal scroll in Webkit

- .changeset/blockprotocol-react-types.md
We upgraded the `@types/react` dependency in `blockprotocol` in #426, but didn't publish a new version of `blockprotocol`. This is leading to type mismatches in https://github.com/hashintel/hash
This PR adds a changeset for `blockprotocol` so we can publish a new version.
> Add blockprotocol changeset for @types/react bump

- .github/workflows/release.yml
The changeset release action has a typo in it which means it does not work - see [here](https://github.com/blockprotocol/blockprotocol/runs/7541374647?check_suite_focus=true).
> Fix typo in changeset release action

- rfcs/text/0430-hook-service.md
We accidentally merged without filling in some of the template
> Fill in Hook Service RFC header

- site/src/pages/api/rewrites/sandboxed-block-demo.api.ts
This PR removes unused code which I’ve accidentally discovered while preparing #477. The `hotfixExternals` function was needed to render the following blocks in conjunction with Þ v0.1:
- https://blockprotocol.org/@jmackie/blocks/quote
- https://blockprotocol.org/@shinypb/blocks/emoji-trading-cards
- https://blockprotocol.org/@kickstartds/blocks/button
The are incompatible with Þ v0.2 and are therefore not displayed on the website. Keeping the patch will make it more tricky to review new versions of these blocks or other blocks.
> Remove `hotfixExternals` (unused code)

- .changeset/mock-block-dock-fix.md
- packages/mock-block-dock/src/mock-block-dock.tsx
A bug that was introduced in #488 where `mock-block-dock` has infinite re-renders when the `readonly` prop is undefined. This PR fixes that
> Fix multiple re-renders bug in `mock-block-dock`

- .changeset/core-service-updates.md
- packages/@blockprotocol/core/src/core-handler.ts
- packages/@blockprotocol/core/src/service-handler.ts
- packages/@blockprotocol/core/src/types.ts
This PR ensures a timestamp is included when messages are sent. While implementing a logs viewer in https://github.com/blockprotocol/blockprotocol/pull/507, the logs were not displaying in the right order because the timestamp was being attached when the event was received as opposed to when it was dispatched. This ensures the right timestamp is set.
> Include `timestamp` when messages are sent

- .github/workflows/release.yml
- [Slack thread](https://hashintel.slack.com/archives/C02LG39FJAU/p1660842753440749) (internal)
- https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-536204092
- `GITHUB_TOKEN` [rules and workarounds in docs](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs)
> When you use the repository’s GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository’s GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.
> Use a repo scoped [Personal Access Token …
> Use custom token in release CI

- site/src/pages/api/rewrites/sandboxed-block-demo.api.ts
Context:
- [Slack thread](https://hashintel.slack.com/archives/C02LG39FJAU/p1661170257710909) (internal)
- [Asana task](https://app.asana.com/0/1202787635216884/1202838684488401/f) (internal)
- Upstream issue: https://github.com/ije/esm.sh/issues/406
> Temporarily pin `mockBlockDockVersion` in sandbox

- codecov.yml
Our test coverage is a bit unstable because of some async code in `useEffect` calls. This triggers false codecov CI failures, e.g. https://github.com/blockprotocol/blockprotocol/pull/512#issuecomment-1220956812.
This PR eases Codecov threshold by changing it to 0 (default) to 1%. This can help us avoid some distraction while we investigate the underlying cause.
The most common source of flakines is `mdx-page-content.tsx`. The relationship between scrolling and `#anchors` is async and settles within 1.5...2 seconds. If Playwright (or a user) scrolls faster than that, some code is skipped. Other cases are similar in nature.
> Set codecov threshold

- scripts/packages/e2e-test-create-block-app.ts
- site/src/pages/api/rewrites/sandboxed-block-demo.api.ts
- site/tests/integration/blockpage.test.ts
- site/tests/integration/docs.test.ts
Reverts blockprotocol/blockprotocol#515
We no longer need to pin MBD because the upstream issue is now resolved: https://github.com/ije/esm.sh/issues/406#issuecomment-1223330666
Extras: see comments
> Switch back to the latest `mockBlockDockVersion` in sandbox

- package.json
- packages/block-template-html/package.json
- packages/create-block-app/package.json
- scripts/packages/e2e-test-create-block-app.ts
- turbo.json
Extracted from #508 to keep PR scope focused. Continues https://github.com/blockprotocol/blockprotocol/pull/525.
- saves us from creating dummy `lint:tsc` in some existing and future packages (requirement of `yarn workspaces`)
- speeds up repeated calls to `yarn lint:tsc`:
```
Tasks:    15 successful, 15 total
Cached:    15 cached, 15 total
Time:    280ms >>> FULL TURBO
```
> Run `lint:tsc` via Turborepo

- .github/workflows/ci.yml
- turbo.json
This change should speed up CI by reusing Turborepo remote cache between builds. Unlike GitHub cache (which is pretty much monolithic), Turborepo cache is more granular and lets us read and write individual keys depending on the state of the packages.
[Docs](https://turborepo.org/docs/ci/github-actions) recommend setting two secrets: `TURBO_TOKEN` and `TURBO_TEAM`. I deviated from this a little and hardcoded `TURBO_TEAM`. Keeping `hashintel` in GitHub secrets will replace this string with `***` in CI output, which we don’t want. I had this in another project and had to remove a trivial string id from secrets to avoid confusion.
This change is an experiment. If we see issues with Turborepo cache, we'll roll this PR back. Otherwise, we’ll use new env vars to other jobs too.
> Enable Turborepo remote cache in CI

- .github/workflows/release.yml
Context: https://github.com/changesets/action/issues/187#issuecomment-1227190958
> Try using custom git credentials in Changesets Action

- packages/@local/eslint-config/index.js
This PR syncs [`no-unused-vars`](https://eslint.org/docs/latest/rules/no-unused-vars) with [`@typescript-eslint/no-unused-vars`](https://typescript-eslint.io/rules/no-unused-vars/) which is [already configured](https://github.com/blockprotocol/blockprotocol/blob/35531b3601bf1e6f1446a25c24f70a3a04807434/packages/%40local/eslint-config/index.js#L404-L418). Syncing two rules helps us maintain the same code style both in js and ts files.
My personal preference is to keep the rule defaults, but I agree with the idea of consistency.
---
- https://app.asana.com/0/0/1202861619533371
> Configure `no-unused-vars`

- site/src/lib/api/blocks/get.ts
Fixes recent failures in Integration tests
- [slack thread](https://hashintel.slack.com/archives/C02LG39FJAU/p1661875861698159) (internal)
- [Asana task](https://app.asana.com/0/0/1202886867026837) (internal)
> Replace import assertion with `fs.readJsonSync`

- crates/type-system/src/ontology/entity_type/repr.rs
An manually overridden type was incorrect and tests do not cover this at the moment (there is a TODO)
> Type System Package Hotfix

- codecov.yml
This PR should suppress CI failures when PR diff coverage is small:
We can switch back to the default behavior when we are more committed to writing tests for new features. Getting used to ❌ makes it harder to pay attention to real issues.
- [codecov docs](https://docs.codecov.com/docs/common-recipe-list#set-non-blocking-status-checks)
- [Asana task](https://app.asana.com/0/0/1202886867026851) (internal)
> Make codecov diff in PRs informational

- rfcs/0000-template.md
We have been opening discussions too early, and ideally we should be discussing _proposals_ on the PR themselves until they have been accepted and then merged. At which point we are to open a discussion to track **implementation**.
> Clarify Discussion Process in RFC

- site/src/lib/api-client.ts
#556 included a change aimed at using relative API routes when running on the client, but instead set relative API routes when running on the server, breaking pages which made server-side calls to the API (e.g. https://blockprotocol.org/@hash).
This PR corrects the condition.
> Fix base url in Axios requests

- site/tests/universal/blockpage.test.ts
Related to [Asana task](https://app.asana.com/0/1202839302145209/1202922733837187/f) (internal) / [Slack thread](https://hashintel.slack.com/archives/C02LG39FJAU/p1662396422497149) (internal)
Properly marking a failing test will keep CI green while we are fixing the bug. Keeping tests as is may lead to more bugs accidentally merged to `main`.
> Skip block properties test

- site/tests/universal/blockpage.test.ts
Reverts blockprotocol/blockprotocol#569. No longer needed after #571 and #572
> Revert "Skip block properties test"

- .changeset/hello.md
- .github/workflows/ci.yml
- package.json
When working on #577, I made a typo in `.chaneset/config.json` but noticed that CI was still passing. This meant that potential issues with [Changesets](https://github.com/changesets/changesets) could remain hidden until merge, thus causing delays in development.
This PR configures `changeset status` as a new linter (`yarn lint:changeset`). [Adding a malformed changeset markdown](https://github.com/blockprotocol/blockprotocol/pull/579/commits/df3236e121e8d4f71642d6bd2c0d4a438caa7a26) makes [CI fail](https://github.com/blockprotocol/blockprotocol/runs/8227047971?check_suite_focus=true#step:4:37), as expected. The same should also happen if `.changeset/config.json` gets broken in future at any point.
---
- …
> Run Changesets as linter

- .github/workflows/ci.yml
- package.json
- yarn.lock
Continues #579, fixes CI failures in _Version Packages_ PRs.
From [docs](https://github.com/changesets/changesets/blob/b062f1c931787363585f815100f69b6fcc71d57e/docs/command-line-options.md#status):
> NOTE: status will fail if you are in the middle of running version or publish. If you want to get changeset status at the time of a version increase and publish, you need to run it immediately before running version.
See [failed run example](https://github.com/blockprotocol/blockprotocol/runs/8232074402?check_suite_focus=true#step:4:23) for https://github.com/blockprotocol/blockprotocol/pull/578
---
**Extra**: I’ve also bumped `@changesets/cli` to get this upstream PR in: https://github.com/changesets/changesets/pull/905
Older versions of `@changesets/cli` use built-in Prettier (v1). It …
> Do not run `changeset` linter in Version Packages PRs

- patches/@changesets+git+1.4.1.patch
This patch follows #579 and is similar to #583. 
Now that we run `yarn changeset status` in pull requests, we get CI failures when a package is changed but a changeset file is missing (see [example run](https://github.com/blockprotocol/blockprotocol/runs/8260602543?check_suite_focus=true#step:5:1) for https://github.com/blockprotocol/blockprotocol/pull/584). This error is fixable by running `yarn changeset add --empty`, but doing so can be annoying each time.
This PR patches `@changesets/git` by ignoring private packages in `yarn changeset status`. When future PRs modify `@local/*` packages or `site`, CI should no longer fail. This can be tested locally by checking out this branch, then changing a file in a private package and finally running `yarn lint:changeset`. Changing publishable …
> Do not require changeset markdowns in private packages

- site/src/components/navbar/mobile-breadcrumbs.tsx
On mobile devices, some of the long breadcrumbs are overflowing from screen, and that looks confusing. This PR enables line-breaks on mobile breadcrumbs, so it does not overflow.
| Before   | After |
|----------|-------------|
| ![](https://user-images.githubusercontent.com/39553853/189288396-026e3f6d-b583-41fa-99ef-d4337063ee9d.png) |  ![](https://user-images.githubusercontent.com/39553853/189288400-c1a3cd60-9d44-478a-a0e0-d27f39ae19db.png) |
---
- https://app.asana.com/0/0/1202787635216896
> Fix overflowing breadcrumbs issue on mobile

- rfcs/text/0352-graph-type-system.md
In [the graph type system RFC](https://github.com/blockprotocol/blockprotocol/blob/main/rfcs/text/0352-graph-type-system.md) various example URIs for link types included `/property-type/` instead of `/link-type/`. This PR fixes these typos.
This was spotted by @thehabbos007 in https://github.com/blockprotocol/blockprotocol/discussions/418#discussioncomment-3170909
> Fix typos in RFC link type URIs

- patches/@changesets+get-dependents-graph+1.3.3.patch
Replaces https://github.com/blockprotocol/blockprotocol/pull/583
The original patch was inspired by https://github.com/changesets/changesets/pull/907. It ignored `devDependencies` when calculating new versions to release, which worked generally well. The solution, however, did not cover block templates, which had `block-scripts` in `devDependencies`.
This PR updates the way we list dependencies in a topological graph. A package is excluded if it is `private`. This should cover existing cases and also work for `block-scripts`.
[Slack thread](https://hashintel.slack.com/archives/C02LG39FJAU/p1662969660652819) (internal)
> Update `@changesets/get-dependents-graph` patch

- site/src/components/service-message-list.tsx
This PR adds a list of links to messages descriptions above the list of full message description, to make it easier to see at once the full list of messages, and go to the one of interest.
> Add list of links to messages on graph spec page

- patches/@changesets+assemble-release-plan+5.2.1.patch
Follows https://github.com/blockprotocol/blockprotocol/pull/600. With this change, we should hopefully see new versions in `block-template-*` when `mock-block-dock` and `block-scripts` are updated.
There is a chance that the PR will break _Version Packages_ completely. If this happens, I’ll revert the PR.
> Bump package version when `devDependencies` update

- .changeset/calm-buttons-sort.md
- packages/block-template-html/package.json
This PR fixes the build script on block-template-html on Windows.
Running yarn build on cmd was removing `block-metadata.json`, `block-schema.json`, `src/*` and `dev/*` because cmd doesn't recognize `;` as a chaining operator. Replaced the `;` operator with `&&`.
[Task](https://app.asana.com/0/1200211978612931/1202768723281652/f)
> Fix block-template-html build script on Windows

- .github/workflows/ci.yml
When working on #565, I had to wait for 23-25 minutes to see if Integration test were failing. We’ve been slowly adding more and more tests since their introduction in https://github.com/blockprotocol/blockprotocol/issues/434, which has contributed to the overall performance of the pipeline.
This PR splits ‘Site integration tests’ into five jobs, one per device (browser). Doing so drops CI wait time to ≈7-9 minutes,which reduces feedback cycle and thus improves DX.
Current approach does not share `next build`, so the app is bundled five times instead of one. This is not ideal, but still quicker than having a separate build job that propagates an artifact to five downstream Playwright jobs. A two-stage setup would require us to have an extra call to `warm-up-repo` (`yarn install`), thus …
> Parallelize integration tests

- .changeset/fast-ducks-scream.md
- packages/create-block-app/create-block-app.js
- packages/create-block-app/package.json
- site/src/_pages/docs/1_developing-blocks.mdx
After creating a block, we tell users they can run 'yarn install && yarn dev' to get started.
Actually they'll need to change into the block dir first. This PR adds that step to the instructions, and a bit of colour.
> Add cd step to post-install instructions

- .changeset/friendly-pumpkins-complain.md
- packages/block-template-react/src/dev.tsx
- packages/mock-block-dock/src/mock-block-dock-ui.tsx
- packages/mock-block-dock/src/mock-block-dock.tsx
The goal of this PR is to optimize sandbox performance. The changes cannot be tested in full until we've released the package on `esm.sh`. Manual smoke-testing testing can be done locally by following these steps:
1. Build MBD  
```sh
cd packages/mock-block-dock
yarn build
```
2. Launch React template   
```sh
cd packages/block-template-react
yarn dev
```
3. Replace `debug` with `hideDebugToggle` in `packages/block-template-react/src/dev.tsx` 
4. Confirm that MBD at http://localhost:63212/ still works
---
- https://app.asana.com/0/0/1202449143008136
> Use `React.lazy` in `mock-block-dock` to optimize MUI loading

- .changeset/rare-teachers-train.md
- packages/mock-block-dock/src/mock-block-dock-ui.tsx
- packages/mock-block-dock/src/mock-block-dock.tsx
- site/src/pages/api/rewrites/sandboxed-block-demo.api.ts
Follows #611 
- Load ESM instead of CJS via esm.sh
- Hide dashed border when `hideDebugToggle`is true
[Asana task](https://app.asana.com/0/1200211978612931/1202449143008136/f) (internal)
> Hotfix mock-block-dock

- site/src/pages/api/rewrites/sandboxed-block-demo.api.ts
Follows #618. Fixes block sandbox by avoiding duplicate react copies.
Recent deployments included these two requests in the network tab ([example](https://blockprotocol-2foqf4ppg.stage.hash.ai/@hash/blocks/code)):
https://esm.sh/stable/react@18.2.0/es2021/react.js
https://esm.sh/stable/react@18.2.0/es2022/react.js
This caused:
```
eact-dom.js:9 TypeError: Cannot read properties of null (reading 'useState')
at n.useState (react.js:2:6785)
at i (use-default-state.js:2:164)
at P (use-mock-block-props.js:2:710)
at W (mock-block-dock.js:2:1420)
at Bi (react-dom.js:7:19481)
```
The error could happen because esm.sh cached `https://esm.sh/mock-block-dock@${mockBlockDockVersion}/dist/esm/index.js?deps=react@${reactVersion}` in a new browser (needing ES2022) and then loaded the result in an older …
> Pin esm.sh target

- site/src/pages/login.page.tsx
This PR fixes the positioning of the Back button on the login page.
[Asana Task](https://app.asana.com/0/1200211978612931/1202936542106234/f)
Before:
After:
> Fix 'back' button on Login page

- .changeset/shiny-mice-protect.md
- packages/mock-block-dock/src/debug-view/header.tsx
- site/src/components/pages/hub/block-data-container.tsx
This does a couple of small things:
1. Allows users to specify the `entityId` in their example entity provided in `block-metadata.json["examples"]`. This is because blocks which rely on an `example-graph.json` which specifies _other_ entities, and _links_ from those other entities to the block example, rely on the block entity having a known `entityId`.
2. Adds a minheight to the MBD debug header, because it can become squashed if the block is very high
it originally added another loading indicator to the Hub, but it was too buggy
> Allow setting entityId in examples object

- .changeset/tricky-wolves-unite.md
- packages/@blockprotocol/hook/README.md
- packages/@blockprotocol/hook/src/react.ts
- packages/@blockprotocol/hook/src/types.ts
The hook service was first introduced without a requirement to specify an `entityId` to identify the entity hook data should be initalised from / saved to. The implicit assumption was that it was always the block entity that hooks should be dealing with – we want the service to handle hooks for _any_ entity.
This PR introduces an `entityId` field to the hook data specified in `@blockprotocol/hook`, so that users of the service are required to specify which entity a hook relates to.
There is follow-on implementation work to do to make this work in embedding applications (e.g. HASH - [task](https://app.asana.com/0/1202953520344821/1203093902519197/f)).
---
- https://app.asana.com/0/0/1202809197795774
> Add entityId requirement to @blockprotocol/hook

- apps/site/playwright.config.ts
Follows #609. Makes sure we collect coverage not only from `yarn workspace @apps/site build` but also during `yarn workspace @apps/site start`. Restores original test coverage levels (≈60% 📉 ≈40% 📈 ≈60%).
#609 was reporting 0% coverage no matter what I tried, see details in https://github.com/blockprotocol/blockprotocol/pull/609#discussion_r989567128.
> Fix ISTANBUL_TEMP_DIR

- .github/renovate.json
Follows #587 
- Set [`stabilityDays`](https://docs.renovatebot.com/configuration-options/#stabilitydays) to 3
- Set [`rebaseWhen`](https://docs.renovatebot.com/configuration-options/#rebasewhen) to `conflicted`. When several PRs are open, each merge triggers update in all Renovate PRs and this clogs CI/CD. Reviews are discarded on rebasing because Renovate force-pushes. Instead of auto rebasing, we can try merging `main` into a PR branch manually just before we are ready to merge. We still want to rebase if there are conflicts (mostly in `yarn.lock`)
- Enable updates for all dependencies in root workspace (`"matchFiles": ["package.json"]`)
- Improve group names by using Title Case there. This can potentially help us distinguish between updates in Groups and updates in individual packages …
> Improve Renovate config

- .changeset/dirty-cooks-exercise.md
- packages/mock-block-dock/dev/test-react-block.tsx
- packages/mock-block-dock/src/util.ts
Fix a bug where mock-block-dock was not handling json paths correctly when deep setting entity properties.
> Fix handling json paths in mock-block-dock set

- .changeset/chilly-parents-kneel.md
- packages/mock-block-dock/src/hook-portals/text.tsx
- packages/mock-block-dock/src/hook-portals/text/toolbar.tsx
This PR fixes a few bugs in mock-block-dock's hook service which only appear when updates to the property the block has called the hook service on are sent from outside the block, either very quickly or as plain text. This was noticed when trying out text blocks in the Hub and typing in the external editor.
Fixes as follows:
1. when a plain string is sent as an update to a property that is currently rich text, the string was not being properly compared to rich text in the block. This PR fixes comparing strings to rich text
2. when resetting the slate editor content in response to external updates, the `onChange` is triggered. This PR stops this sending an update back to the embedding application if the content is the same as the value from props – otherwise, if updates are coming fast, …
> Fix bug in dock text comparison

- apps/site/tests/integration/accountpage.test.ts
- apps/site/tests/integration/api-keys.test.ts
- apps/site/tests/integration/block-publish-npm.test.ts
- apps/site/tests/integration/blockpage.test.ts
- apps/site/tests/integration/dashboard.test.ts
- apps/site/tests/integration/docs.test.ts
- apps/site/tests/integration/hubpage.test.ts
- apps/site/tests/integration/login-flow.test.ts
- apps/site/tests/integration/schema-creation.test.ts
- apps/site/tests/integration/schemapage.test.ts
- apps/site/tests/integration/sign-up-flow.ts
- apps/site/tests/package.json
- apps/site/tests/shared/fixtures.ts
- apps/site/tests/shared/nav.ts
- apps/site/tests/universal/page-header.test.ts
- packages/@blockprotocol/graph/.eslintrc.cjs
- packages/@blockprotocol/hook/.eslintrc.cjs
- packages/@local/eslint-config/generate-workspace-config.cjs
- packages/@local/eslint-config/package.json
- packages/block-template-react/src/app.tsx
- packages/mock-block-dock/dev/dev-app.tsx
- packages/mock-block-dock/dev/test-react-block.tsx
- yarn.lock
Removes `apps/site/tests/package.json` (with `"type": "commonjs"`), unblocks dependency updates such as [`execa@6`](https://github.com/sindresorhus/execa/releases/tag/v6.0.0) (which is needed in https://github.com/blockprotocol/blockprotocol/pull/703 / [internal Asana task](https://app.asana.com/0/1203007126736610/1203225227202716/f))
[Playwright docs on ESM](https://playwright.dev/docs/test-typescript#typescript-with-esm)
CJS to ESM conversion can be expanded to the entire `@apps/site` package in #709.
Also fixes `import/no-unresolved` for ESM imports by adding `"eslint-import-resolver-typescript"`. This can improve linting in other ESM-only packages in the future (`block-scripts` etc.).
> Switch Playwright tests to ESM

- apps/site/playwright.config.ts
- apps/site/tests/integration/api-keys.test.ts
This PR
- Increases the number of retries
- Skip pressing ‘Copy to Clipboard’ in Safari (may prevent internal hanging?)
Used Safari traces from https://github.com/blockprotocol/blockprotocol/actions/runs/3328626488
The test occasionally fails when pressing ‘Go back’ right after pressing ’Copy to Clibpoard’:
This is how a successful click looks like (same run, just further up in the file):
If this PR’s diff does not reduce flakiness, I’ll try something else.
> Reduce Playwright test flakiness

- crates/type-system/src/ontology/data_type/repr.rs
- crates/type-system/src/ontology/entity_type/links/repr.rs
- crates/type-system/src/ontology/entity_type/repr.rs
- crates/type-system/src/ontology/property_type/repr.rs
- crates/type-system/src/ontology/shared/all_of/repr.rs
- crates/type-system/src/ontology/shared/object/repr.rs
- packages/@blockprotocol/type-system-node/dist/index.d.ts
- packages/@blockprotocol/type-system-web/dist/index.d.ts
We had a number of spots in the Type System packages where non-ideal types were being used, strings instead of `VersionedUri` for example, and a few other things.
This PR generally improves the usabilities of the interfaces. 
- [Asana task](https://app.asana.com/0/1201095311341924/1202981263631815/f) _(internal)_
- `DataTypeReference`, `PropertyTypeReference`, and `EntityTypeReference` now has `VersionedUri` instead of `string`
- The `links` object on `EntityType` has been much improved
- A lot of fields have been marked as optional when they were previously required
- `$id` in schemas are correctly typed as `VersionedUri`s
- `BaseUri` is used in more places where it should be
- Some other improvements, see the generated binding file
- The TypeScript bindings act as the doc at the moment …
> Improve TS Types of the Type System Package

- patches/@changesets+cli+2.25.0.patch
This PR prevents CI failures in Renovate PRs that immediately follow ‘Version Packages’.
- [Asana task](https://app.asana.com/0/1203007126736613/1203268787004289/f) _(internal)_
`yarn lint:changeset` (i.e. `yarn changeset status`) no longer fails when no changeset files are found. This avoids CI failures in Renovate PRs, e.g.:
https://github.com/blockprotocol/blockprotocol/actions/runs/3357688943/jobs/5563688194#step:5:1
Disabling the check means that in theory we can forget adding a Changesets entry in a valid case. However, it seems that [the existing check](https://github.com/changesets/changesets/blob/c1401716cf5ee839aaa02ea7ff8f23f8af8bf5b0/packages/cli/src/commands/status/index.ts#L46-L54) only works until the first changeset is added. For example, adding a changeset for package `a` …
> Patch Changesets CLI

- .github/workflows/semgrep.yml
Adds a CI job for Semgrep scanning the repo on proposed merges into `main`, similar to that in use in [`@hashintel/hash`](https://github.com/hashintel/hash).
Once this has been reviewed and we're happy with it, we should update the [corresponding file](https://github.com/hashintel/hash/blob/main/.github/workflows/semgrep.yml) in `@hashintel/hash` to reflect our new understanding of best-practice here (minor modifications only expected).
---
- https://app.asana.com/0/0/1203364310192415
> Add Semgrep GitHub Action

- .github/workflows/ci.yml
This PR supplements https://github.com/blockprotocol/blockprotocol/issues/715. Stopping the DB should prevent changes in `var` while this folder is being uploaded as an artifact. This should reduce the probability of hanged (and therefore cancelled) Playwright jobs, which are now compulsory for PR merging.
- https://github.com/actions/upload-artifact/issues/358
- [Recent failure example](https://github.com/blockprotocol/blockprotocol/actions/runs/3489080330/jobs/5838721922)
> Stop DB in Site integration tests CI

- .github/renovate.json
This PR extends the scope of Renovate, which now covers all dependencies in the repo. As before, new PRs are not created automatically and we need to approve them via Dependency dashboard (#788) first.
- [Asana task](https://app.asana.com/0/1203312852763953/1203464390652052/f) _(internal)_
- https://github.com/hashintel/hash/pull/1535
I’ve removed some package rules as they are no longer needed. We extend from a preset named [`config:base`](https://docs.renovatebot.com/presets-config/#configbase) which in turn includes [monorepo presets](https://docs.renovatebot.com/presets-monorepo/). This means that dependencies within well-known monorepos are grouped together without us having to configure anything. For example, `next` is upgraded with `@next/bundle-analyzer` in a single PR. I’ve kept …
> Reconfigure Renovate (cover all dependencies)

- apps/site/package.json
- crates/type-system/package.json
- packages/@blockprotocol/core/package.json
- packages/@blockprotocol/graph/package.json
- packages/@blockprotocol/hook/package.json
- packages/@blockprotocol/type-system/package.json
- packages/@local/eslint-config/package.json
- packages/@local/package-chores/package.json
- packages/@local/script-resources/package.json
- packages/block-scripts/package.json
- packages/block-template-custom-element/package.json
- packages/block-template-html/package.json
- packages/block-template-react/package.json
- packages/blockprotocol/package.json
- packages/create-block-app/package.json
- packages/mock-block-dock/package.json
This PR makes sure that `yarn lint:eslint` does not exits with 0 if there are unused ESLint disable comments left in the codebase. These comments should be automatically removed on save because we have `reportUnusedDisableDirectives: true`  [in our base ESLint config](https://github.com/blockprotocol/blockprotocol/blob/e5a1e7df730596b0e93e420703ca70cdee314c58/packages/%40local/eslint-config/index.js#L5). However, when we do bulk-edits, unused directives may remain as warnings and not fail the CI.
- [Asana task](https://app.asana.com/0/1203363157432081/1203452982053233/f) (internal)
If there is support for ``reportUnusedDisableDirectives: "error"`` [upstream](https://github.com/eslint/eslint/issues/15466#issuecomment-1339759506), we can remove the CLI option.
I tested the option manually …
> Add `--report-unused-disable-directives` to `lint:eslint`

- apps/site/tests/integration/api-keys.test.ts
This PR aims to fix CI failures which have been frequent since recently.
Example: https://github.com/blockprotocol/blockprotocol/actions/runs/3649530904/jobs/6164329738
```
Running 34 tests using 1 worker
···××T········°·····°·°°·°·····°°°°·
1) [integration-safari] › integration/api-keys.test.ts:5:1 › API key page should generate a valid key 
Test timeout of 30000ms exceeded.
```
Here is what I saw in trace files ([example artifact URL](https://github.com/blockprotocol/blockprotocol/suites/9750206066/artifacts/468109554)):
The issue is with some actions like `locator.click()` which that take about 3 or 6 seconds instead of just a few milliseconds.
Webkit is used both in `iphone` and `safari` tests, but only Safari fails frequently. `iphone` tests I checked took just under 30 seconds so I …
> Increase Playwright test timeout for Webkit to fix CI

- packages/@blockprotocol/graph/src/custom-element.ts
- packages/@blockprotocol/graph/src/types.ts
- packages/@blockprotocol/graph/src/types/block-graph.ts
- packages/@blockprotocol/graph/src/types/entity.ts
- packages/@blockprotocol/graph/src/types/ontology.ts
- packages/@blockprotocol/graph/src/types/ontology/data-type.ts
- packages/@blockprotocol/graph/src/types/ontology/entity-type.ts
- packages/@blockprotocol/graph/src/types/ontology/metadata.ts
- packages/@blockprotocol/graph/src/types/ontology/property-type.ts
- packages/@blockprotocol/graph/src/types/subgraph.ts
- packages/@blockprotocol/graph/src/types/subgraph/edges.ts
- packages/@blockprotocol/graph/src/types/subgraph/edges/kind.ts
- packages/@blockprotocol/graph/src/types/subgraph/edges/outward-edge.ts
- packages/@blockprotocol/graph/src/types/subgraph/graph-resolve-depths.ts
- packages/@blockprotocol/graph/src/types/subgraph/time.ts
- packages/@blockprotocol/graph/src/types/subgraph/vertices.ts
The Block Protocol Graph service is centered around a data abstraction which is represented as a Graph. With the introduction of the Type System there are an increasing variety of elements within this graph, and the previous ways of representing their relationships weren't sufficient in the face of this.
This PR introduces the `Subgraph` type (and its constituent types). The `Subgraph` is likely to replace a lot of the return types for various `get` and `aggregate` queries within the Graph Service, which should allow users to configure how much contextual information they want about the elements they're querying (for example, they should be able to say how deep link entities should be resolved and returned).
It is being designed for the future to support complex EAs which may have …
> Add the `Subgraph` types

- crates/type-system/src/ontology/data_type/mod.rs
- crates/type-system/src/ontology/entity_type/mod.rs
- crates/type-system/src/ontology/mod.rs
- crates/type-system/src/ontology/property_type/mod.rs
- crates/type-system/src/ontology/property_type/repr.rs
- crates/type-system/src/utils.rs
In order to generalize over ontology types and entities in downstream applications (e.g. the HASH Graph API), it's required that the ontology types implements `Serialize` and `Deserialize` because of the orphan rule. 
- Part of [Asana task](https://app.asana.com/0/1203363157432084/1203449432963806/f) _(internal)_
Implements `Deserialize` and `Serialize` for `DataType`, `PropertyType`, and `EntityType`
The current design requires the struct to be cloned. This is unfortunate, but without changing the implementation it's hard to work around this. However, it's better to have those traits implemented in the crate rather than specifying the implementation by hand in downstream crates.
> Expose ontology types of `repr` module

- apps/site/src/components/pages/wordpress/early-access-cta.tsx
Wraps the form for early access WordPress plugin signup in a `form`, enabling 'hit enter to submit'.
Hide whitespace to see the meaningful diff
> Make wordpress signup into a form

- apps/site/sentry.client.config.ts
Follows https://github.com/blockprotocol/blockprotocol/pull/836, fixes e2e tests by not using deprecated options.
```
[warning] [Replay] You are passing `sessionSampleRate` to the Replay integration.
This option is deprecated and will be removed soon.
Instead, configure `replaysSessionSampleRate` directly in the SDK init options, e.g.:
Sentry.init({ replaysSessionSampleRate: 1 })
[warning] [Replay] You are passing `errorSampleRate` to the Replay integration.
This option is deprecated and will be removed soon.
Instead, configure `replaysOnErrorSampleRate` directly in the SDK init options, e.g.:
Sentry.init({ replaysOnErrorSampleRate: 1 })
```
https://github.com/blockprotocol/blockprotocol/actions/runs/3748171788/jobs/6365215227#step:5:164
- [Asana …
> Stop using deprecated config in Sentry Replay

- packages/@blockprotocol/graph/src/stdlib/subgraph/edge/entity-type.ts
- packages/@blockprotocol/graph/src/types/subgraph/edges/outward-edge-alias.ts
This expands the `stdlib` to provide a helper to get all `PropertyType`s referenced by a given `EntityType` by utilising the `Edges` of a `Subgraph`.
- [Asana task](https://app.asana.com/0/1203363157432094/1203662893654909/f) _(internal)_
N/A
See commits, tiny diff
Not to my knowledge
We have a slightly unclear strategy about when to return errors for missing things
N/A
None
We don't currently have tests for the subgraph library, if you want to see it in action you'll need to modify the existing code and use it somewhere
> Add helper function to get property types referenced in an entity type

- apps/site/src/lib/api/mailchimp.ts
- apps/site/src/pages/api/vote-application.api.ts
- yarn.lock
This PR fixes the [error](https://sentry.io/organizations/hashintel/issues/3829279587/?environment=production&project=6603021&query=is%3Aunresolved&referrer=issue-stream) flagged by Sentry: `Cannot set headers after they are sent to the client` when submitting a vote on the BP page fails. 
- [Asana task](https://app.asana.com/0/1203543021352032/1203672578234992/f) _(internal)_
- Removed duplicate error handling for the `vote-application` api method.
1.  Try to vote without any mailchimp env vars (to force it to fail) and check for the error;
2.  Add the mailchimp env vars (DM me if you want to use mine) and test again to check if voting still works.
> Fix vote application error handling

- .github/workflows/ci.yml
- .github/workflows/site-deployment.yml
Extracted from https://github.com/blockprotocol/blockprotocol/pull/680, unblocks #871 and other pending PRs.
I've increased timeout because cold yarn + rust warmup has been causing CI failures: https://github.com/blockprotocol/blockprotocol/actions/runs/3887049425/jobs/6632856500
We are no longer affected by https://github.com/actions/upload-artifact/issues/358 once https://github.com/blockprotocol/blockprotocol/pull/769 has been merged. I've kept a large timeout just in case, but I don't think we need it except for some really rare edge cases.
CI
> Increase pipeline timeout

- .changeset/eight-cups-shave.md
- packages/@blockprotocol/graph/src/stdlib.ts
- packages/create-block-app/create-block-app.js
`npx create-block-app` allows you to specify a `--template`, picking from one of `custom-element`, `react`, and `html` – it will then fetch the appropriate `block-template-[template]` package from npm.
Being able to specify the version or tag of the template to install will be useful to us in development – particularly to be able to do things like `npx create-block-app@canary --template react@canary [blockname]`
This PR enables that by updating a check which would reject values for `--template` that do not exactly match an expected template name.
An alternative approach would be to specify `--tag` or `--version` as an explicit, documented option to `create-block-app`. I did not do this because there may be mismatches between versions of templates and the version of `create-block-app` …
> Enable specifying npm tag/version in create-block-app

- .github/licenses/LICENSE-APACHE.md
- .github/licenses/LICENSE-ELASTIC.md
- .github/licenses/LICENSE-MIT.md
- .gitignore
- .markdownlintignore
- .prettierignore
- libs/@blockprotocol/type-system/crate/LICENSE-APACHE.md
- libs/@local/eslint-config/generate-ignore-patterns.cjs
This PR excludes `LICENSE.md` and `LICENSE-*.md` files from `yarn lint:markdownlint` and `yarn lint:prettier`.
- [Asana task](https://app.asana.com/0/1203193968491715/1203754204131512/f) _(internal)_
- https://github.com/hashintel/hash/pull/1847
> Stop linting license files

- .knip.jsonc
- package.json
Just saw that the knip config contains odd workspace keys. They should be the actual workspaces as defined in `package.json`. Not sure what happened, why it was like this. Anyway, here's a fix.
> Fix workspace dirs in knip config

- hub/@alfie/github-pr-overview.json
- hub/@hash/callout.json
- hub/@hash/code.json
- hub/@hash/divider.json
- hub/@hash/embed.json
- hub/@hash/header.json
- hub/@hash/image.json
- hub/@hash/paragraph.json
- hub/@hash/person.json
- hub/@hash/shuffle.json
- hub/@hash/table.json
- hub/@hash/video.json
- hub/@thehabbos007/calculation.json
- hub/@timdiekmann/countdown.json
- hub/@timdiekmann/timer.json
- hub/@tldraw/drawing.json
Bumps block versions to the latest commit in `hash`.
This will make the Block Hub built off the `0.3` branch have the latest `Code` block, which is updated to 0.3. This will be used to have a serveable block loaded from the Hub for testing in updated embedding applications (HASH, WordPress).
> Bump block versions

- .github/labeler.yml
- .github/workflows/labeler.yml
This PR syncs this repo’s labeler setup with https://github.com/hashintel/hash/pull/1934. In particular, it updates [actions/labeler](https://github.com/actions/labeler) to v4 and applies on top of it: https://github.com/actions/labeler/pull/316. This fixes deprecation warnings caused by [usage of Node 12](https://github.blog/changelog/2021-12-10-github-actions-github-hosted-runners-now-run-node-js-16-by-default/) in v3.
- [Asana task](https://app.asana.com/0/1203543026679373/1203800233887959/f) _(internal)_
- [actions/labeler@v4.0.0 release notes](https://github.com/actions/labeler/releases/tag/v4.0.0)
- CI (linting)
- Monitor label creation once this PR is merged
> Update labeler config

- .gitattributes
- .gitignore
- .markdownlintignore
- .prettierignore
- libs/@blockprotocol/graph/src/codegen/entity-type-to-typescript.ts
- libs/@blockprotocol/graph/src/custom-element.ts
- libs/@blockprotocol/graph/src/graph-block-handler.ts
- libs/@blockprotocol/graph/src/stdlib/subgraph/builder.ts
- libs/block-template-custom-element/src/app.ts
- libs/block-template-custom-element/src/types.gen.ts
- libs/block-template-react/src/app.tsx
- libs/block-template-react/src/types.gen.ts
- libs/create-block-app/create-block-app.js
- yarn.lock
1. Fix some bugs in the block templates (see comments on diff)
2. Commit the auto-generated types for blocks, rather than ignoring them – this removes type generation from an external URI as a dependency in the build process. Types are immutable and should not change. I've set `linguist-generated=true` to collapse them in the diff by default
- [Asana task for committing types](https://app.asana.com/0/1203358502199087/1203774997009906/f) _(internal)_
- [Bug report on block template](https://hashintel.slack.com/archives/C02LG39FJAU/p1674582285578809) _(internal)_
– Update #879 and publish new canary versions
> Fix canary block templates. Commit auto-generated types

- apps/site/src/_pages/docs/5_faq.mdx
- apps/site/src/components/coming-soon-banner.tsx
- apps/site/tests/integration/page-footer.test.ts
- libs/mock-block-dock/src/version.ts
Fixes a test that broke when text in the footer was changed, and some formatting.
Also commits an update to a file storing the latest version of `mock-block-dock`. I think this file exists so that Mock Block Dock's runtime code can refer to its own version without importing from `package.json`. This PR brings it into line.
> Fix footer test, formatting. Commit mock-block-dock version change

- libs/@blockprotocol/graph/src/codegen/entity-type-to-typescript.ts
- libs/@blockprotocol/graph/src/codegen/hardcoded-bp-types.ts
Fix two bugs in the `codegen` code in `@blockprotocol/graph`:
1. The 'object' data type was missing
2. When generating a type name, the schema title was unmodified, meaning that it could begin with a lowercase letter
> Types from schema: add 'object' data type. Handle lowercase schema title

- apps/site/src/components/pages/home/supported-applications.tsx
- apps/site/src/components/pages/home/zero-application-developers.tsx
This PR moves the `GitHub Blocks` button to the `Coming Soon` section and fixes a couple of buttons on mobile screens.
Before:
After:
> Homepage fixes

- libs/@blockprotocol/graph/src/codegen/entity-type-to-typescript.ts
- libs/@blockprotocol/graph/src/codegen/entity-type-to-typescript/type-definition-generators.ts
- libs/@blockprotocol/graph/src/types/entity.ts
- libs/block-template-custom-element/package.json
- libs/block-template-react/package.json
1. Overwrites the default generated type for an opaque object with our own `JsonObject` type
- this involves re-exporting `JsonObject` in `@blockprotocol/graph` to avoid users having to add `@blockprotocol/core` as a separate dependency (and therefore potentially becoming out of sync)
2. Renames `codegen` in templates to `schema` as a temporary measure. The generated type output is non-deterministic (types may appear in a different order), meaning that any run of Turborepo can result in a diff if the template's `codegen` scripts are run (internal Asana [task](https://app.asana.com/0/1203179076056209/1203843256013361/f) to figure out a permanent fix for this)
> Better 'Object' type. Rename codegen script in templates

- .github/workflows/canary-release.yml
Fix an issue with the canary release workflow where it needs a git author set to commit.
> Set git author in canary release workflow

- libs/@blockprotocol/graph/src/codegen/entity-type-to-typescript.ts
- libs/@blockprotocol/graph/src/codegen/shared.ts
- libs/@blockprotocol/graph/src/shared.ts
- libs/@blockprotocol/graph/src/stdlib/bound.ts
- libs/@blockprotocol/graph/src/stdlib/interval.ts
- libs/@blockprotocol/graph/src/stdlib/subgraph/element/entity.ts
- libs/@blockprotocol/graph/src/types.ts
- libs/@blockprotocol/graph/src/types/subgraph.ts
- libs/@blockprotocol/graph/src/types/subgraph/edges.ts
- libs/@blockprotocol/graph/src/types/subgraph/edges/outward-edge.ts
- libs/@blockprotocol/graph/src/types/subgraph/time.ts
- libs/@blockprotocol/graph/src/types/temporal-versioning.ts
As expressed in previous PRs, we intend to add the foundations of support for bitemporal datastores within the BP as part of the 0.3 release. This PR introduces relevant primitives that will be used to expand the `Subgraph` type and associated queries.
Notably, performing queries across a temporal datastore requires a lot of interfacing with `Interval`s of time. That is the focus of this PR.
- [Asana task](https://app.asana.com/0/0/1203765721937276/f) _(internal)_
See commits and in-code documentation, effort has been made to keep them self-contained and explanatory.
- This PR does not expose these types on the package's public API, that will need to be done, and we will need to think about how to appropriately write user documentation to introduce them to these concepts. The stdlib on …
> Introduce primitives for bi-temporal versioning

- .changeset/config.json
`@infra/*` packages are not for publishing, so we don't want them suggested when creating changeset files.
> Ignore @infra/ packages in changesets

- .github/actions/warm-up-repo/action.yml
In various PRs some of the jobs fail as cargo make is supposed to be installed, but it's not. This PR tries to solve this by re-ordering the steps in the CI setup, installing cargo-make before using the Rust cache job.
- https://github.com/hashintel/hash/pull/1977
N/A
> Re-order tooling and rust cache in CI

- .changeset/loud-chicken-count.md
- .changeset/silver-dogs-march.md
- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/error.rs
- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/links/wasm.rs
- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/repr.rs
- libs/@blockprotocol/type-system/crate/tests/data/entity_type/address.json
- libs/@blockprotocol/type-system/crate/tests/data/entity_type/block.json
- libs/@blockprotocol/type-system/crate/tests/data/entity_type/book.json
- libs/@blockprotocol/type-system/crate/tests/data/entity_type/building.json
- libs/@blockprotocol/type-system/crate/tests/data/entity_type/organization.json
- libs/@blockprotocol/type-system/crate/tests/data/entity_type/page.json
- libs/@blockprotocol/type-system/crate/tests/data/entity_type/person.json
- libs/@blockprotocol/type-system/crate/tests/data/entity_type/playlist.json
- libs/@blockprotocol/type-system/crate/tests/data/entity_type/song.json
- libs/@blockprotocol/type-system/test/entity-type.test.ts
Entity types should comprehensively define the contents of an Entity. This should be represented within the schema, but due to an oversight we had omitted specifying `"additionalProperties": false`, this modifies the Type System to enforce it.
The `links` definition inside `EntityType` allowed `| {}` inside it. This meant that TypeScript allowed any fields within the object due to quirks with how it handles the object type. This has also been fixed (see demo below for more explanation).
- [Asana task](https://app.asana.com/0/1202805690238892/1203602044074391/f) _(internal)_
- [Asana task](https://app.asana.com/0/1202805690238892/1203466297702512/f) _(internal)_
N/A
- Requires `"additionalProperties": false` to be present in all Entity Types.
- Updates the parsing logic in the Type System …
> Add `"additionalProperties": false` to Entity Types and fix broken links definition

- libs/@blockprotocol/graph/src/internal/mutate-subgraph.ts
- libs/@blockprotocol/graph/src/shared.ts
- libs/@blockprotocol/graph/src/stdlib/subgraph/edge/entity-type.ts
- libs/@blockprotocol/graph/src/stdlib/subgraph/edge/link-entity.ts
- libs/@blockprotocol/graph/src/stdlib/subgraph/element/data-type.ts
- libs/@blockprotocol/graph/src/stdlib/subgraph/element/entity-type.ts
- libs/@blockprotocol/graph/src/stdlib/subgraph/element/entity.ts
- libs/@blockprotocol/graph/src/stdlib/subgraph/element/property-type.ts
- libs/@blockprotocol/graph/src/types/ontology.ts
- libs/@blockprotocol/graph/src/types/subgraph/edges.ts
- libs/@blockprotocol/graph/src/types/subgraph/edges/outward-edge.ts
- libs/@blockprotocol/graph/src/types/subgraph/edges/variants/knowledge.ts
- libs/@blockprotocol/graph/src/types/subgraph/edges/variants/ontology.ts
- libs/@blockprotocol/graph/src/types/subgraph/element-mappings.ts
- libs/@blockprotocol/graph/src/types/subgraph/vertices.ts
- libs/mock-block-dock/src/datastore/traverse.ts
- libs/mock-block-dock/src/datastore/use-mock-datastore.ts
- libs/mock-block-dock/src/debug-view/dev-tools/datastore-graph-visualization.tsx
- libs/mock-block-dock/src/util.ts
The `Subgraph` object contains correct information about the keys used as identifiers for `vertices` and `edges`. Namely, that elements are identified by the following pairs 
- `(EntityId, TimestampString)`, 
- `(BaseUri, number)`
In an ideal world, this would encapsulate quite a lot more information about a correctly formed `Subgraph`. It would greatly reduce the number of type guards that would need to be called in TS, for example (`isEntityVertex`), as the code path would know if it's dealing with an ontology element or a knowledge-graph one.
Unfortunately, the `number` type confuses the heck out of TypeScript and it actually can cause code to be completely incorrect at the worst of times.
This is because when the `number` type is used as a key in an object, it is inferred as being …
> Fix problematic typings in `Subgraph`

- libs/@blockprotocol/graph/src/types/entity.ts
- libs/mock-block-dock/src/util.ts
Previously the `aggregateEntities` and `aggregateEntityTypes` syntax took a singular string when filtering on a specific field. This wasn't fully specified, and generally only referred to a top-level key within the `properties` of an entity (or the schema of an entity type). Our local implementation within mock-block-dock might have worked if the user had written a nested field as `x.y.z`, but this wasn't fully intended.
This PR updates the `field` parameter to instead be a `string[]` where it takes the path in the JSON as a list of components, e.g. `["x", "y", "z"]`. This now also queries inside an `Entity` or an `EntityTypeWithMetadata`, rather than specifically within the `properties` blob or schema. This means that a user could filter on the type of an entity by using:
`["metadata", …
> Update the aggregation query syntax to take the field in a filter as an array of components

- apps/site/scripts/prepare-blocks.ts
This PR contributes to avoiding errors some Vercel builds, e.g. https://vercel.com/hashintel/blockprotocol/AAPj5Vcj4TrXJEgBkyVDeCtaNksz. It runs `yarn cache clean` between block builds, thus reducing the chances of running out of disk space.
- [Asana task](https://app.asana.com/0/1203623179643281/1203903843802405/f) _(internal)_
- [Slack thread](https://hashintel.slack.com/archives/C02TWBTT3ED/p1675086373319199) _(internal)_
- https://github.com/blockprotocol/blockprotocol/pull/936
CI
Run Vercel build without cache and see if it fails
- [Build with Vercel cache (blocks are ready)](https://vercel.com/hashintel/blockprotocol/5ZzTuYggyQN9KtvbbjQvyfz89n6L)
- [Build without Vercel cache (blocks need preparing)](https://vercel.com/hashintel/blockprotocol/KYS8oT4ohcpxcAY2NTU2gWNoRe2p)
> Hotfix `no space left on device` by cleaning Yarn cache

- libs/@blockprotocol/graph/src/stdlib/subgraph/edge/link-entity.ts
- libs/@blockprotocol/graph/src/stdlib/subgraph/element/entity.ts
- libs/@blockprotocol/graph/src/types/entity.ts
- libs/@blockprotocol/graph/src/types/subgraph.ts
- libs/@blockprotocol/graph/src/types/temporal-versioning.ts
- libs/mock-block-dock/src/datastore/traverse.ts
A few sneaky bugs slipped by in previous PRs that introduced temporal versioning code for the stdlib. As identified in those PRs, testing has been deferred to unblock other work in the immediate term, and we were going to discover bugs through development usage, that has happened, and this PR fixes those bugs.
A follow-up will add a block that will make testing these things more easy, although where to put that block is currently unclear, that in-dev block was used to check that the fixes here were correct.
Furthermore,  previously, when traversing a subgraph, the subgraph lib expected there to be left and right entities for all link entities. This was largely based on the reasoning that it's impossible to create a link entity that does not have a left or right endpoint. However, …
> Fix bugs in the Graph service stdlib

- libs/@blockprotocol/graph/src/types/entity.ts
- libs/@blockprotocol/graph/src/types/ontology/entity-type.ts
- libs/mock-block-dock/src/util.ts
With the introduction of the `Subgraph` type, the previous implementation of paginated results for "aggregate" queries no longer makes sense. 
Paginating a graph is a difficult task, as there isn't a discrete index one can use in a stable-ordered _list_ of items, and a cursor needs to contain a potentially unbounded size of information that is yet to be resolved for future queries.
We intend to revisit this, potentially just allowing cursor-based pagination over the `roots` of a `Subgraph`, although ideally with a different solution that will be better suited to blocks that need control over the message sizes.
- [Asana task](https://app.asana.com/0/1203358502199087/1203919127849757/f) _(internal)_
N/A
- Removes all `page` related fields
- Removes the pagination implementation in …
> Temporarily remove pagination from `aggregate*` methods

- libs/@blockprotocol/core/package.json
- libs/@blockprotocol/core/src/types.ts
I started getting a module import error from `@blockprotocol/core` and I'm checking if it's the new presence of `@blockprotocol/graph` that might cause it (core hasn't changed much otherwise).
> Remove type-system dependency from core

- libs/@blockprotocol/core/package.json
I'm encountering an issue when attempting to run HASH with the latest version of `@blockprotocol/` packages which I think is related to https://github.com/vercel/next.js/issues/39375
#926 introduced `exports` to `@blockprotocol/core` recently.
Adding `default` to see if it makes any difference.
```
[dev:frontend] file:///Users/ciaran/dev/hash/apps/hash-frontend/node_modules/@blockprotocol/hook/dist/hook-block-handler.js:1
[dev:frontend] import { ServiceHandler } from "@blockprotocol/core";
[dev:frontend]          ^^^^^^^^^^^^^^
[dev:frontend] SyntaxError: Named export 'ServiceHandler' not found. The requested module '@blockprotocol/core' is a CommonJS module, which may not support all module.exports as named exports.
[dev:frontend] CommonJS modules can always be imported via the default …
```
> Add default to 'exports' paths in @blockprotocol/core

- libs/@blockprotocol/core/package.json
- libs/@blockprotocol/graph/src/react.ts
- libs/@blockprotocol/hook/src/react.ts
- libs/@local/eslint-config/index.js
#957 describes an issue where NextJS is erroring on attempting to load a file in `@blockprotocol/core`. I think this is because of the addition of `exports` paths in #926, so I'm removing them to see if it fixes it.
Longer-term we should probably update `@blockprotocol/core` to be ESM only (this may have other knock-on effects which is why I don't want to do it now).
> Remove export paths from core

- libs/@blockprotocol/core/package.json
- libs/@blockprotocol/graph/src/react.ts
- libs/@blockprotocol/hook/src/react.ts
- libs/@local/eslint-config/index.js
Reverts blockprotocol/blockprotocol#959 – this did not fix the error described in #957, but adding `@blockprotocol/core` and its dependents to transpiled modules in NextJS for `hash-frontend` did.
The long-term fix is to do one or both of 
(a) make `@blockprotocol/core` an ESM package (i.e. type: "module" and associated updates)
(b) make `hash-frontend` an ESM package
> Revert "Remove export paths from core"

- libs/@blockprotocol/graph/src/stdlib/bound.ts
- libs/mock-block-dock/src/mock-block-dock.tsx
When translating the `compareBounds` implementation from Rust to TS we missed a few cases, this fixes a bug that occurs in an edge-case when the `kind` and `limit`s are the same, but the "type" (start or end) is different.
> Fix `compareBounds`

- libs/@blockprotocol/graph/src/stdlib.ts
- libs/@blockprotocol/graph/src/stdlib/interval.ts
- libs/@blockprotocol/graph/src/stdlib/subgraph/edge/link-entity.ts
- libs/@blockprotocol/graph/src/types/ontology/metadata.ts
- In using the canary versions it became apparent that the library could benefit from hoisting and exposing its interval comparison function.
- the addition of an `ownedById` on ontology type records was an oversight, and doesn't make sense in a lot of contexts in EAs (a type may not be owned by any user of the system.
- `getOutgoingLinkAndTargetEntities` took a `Timestamp` instead of a `TimeInterval`, this was inconsistent with the other methods
> Miscellaneous updates to the Graph service

- libs/@blockprotocol/graph/package.json
- libs/@blockprotocol/graph/rollup.config.js
- libs/@blockprotocol/graph/src/codegen.ts
- libs/mock-block-dock/src/mock-block-dock.tsx
- yarn.lock
Importing the Graph package from a service that runs using `ts-node` turned out to be difficult due to it being ESM. This PR applies a quick fix to produce a CJS bundle similar to how the `type-system` is built. 
It also driveby's a lint failure.
No, `yarn` should work as before
- We can't use the same approach as we did in `/core` to produce two bundles, it can't handle some of the necessary transpilations we need for `cjs` stuff to do with imports, async, and assertions. (relevant issue https://github.com/microsoft/TypeScript/issues/51783)
- Top-level await isn't supported in `cjs` so I had to move some of the functionality in`codegen.ts`
- Publish canary versions
- Generally static code analysis (`yarn lint`, etc.) and testing `mock-block-dock` manually
1. Ensure `yarn` still passes
2. …
> Produce cjs bundle for the Graph

- libs/@blockprotocol/graph/package.json
#975 added a new bundling step for the `@blockprotocol/graph` package which uses rollup. Rollup can be a bit of a memory hog and the [publish job](https://github.com/blockprotocol/blockprotocol/actions/runs/4174329059/jobs/7227752921) failed due to running out of memory on build.
This PR attempts to fix that by doubling the heap size to 4GB (and [GitHub actions machines apparently have 7GB](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)).
If this continues to cause problems we should look into moving to some other lightweight build tool (such as [tsup](https://tsup.egoist.dev/)) for the Graph Package instead of `rollup`. Ideally this will solve the problem in the meantime though.
> Increase build heap size for Graph

- infra/cloudflare-r2-wrangler/blockprotocol-preview/wrangler.toml
- infra/cloudflare-r2-wrangler/blockprotocol/wrangler.toml
- infra/cloudflare-r2-wrangler/index.js
This PR adds statistics reporting to our R2 worker. We still provide aggregate statistics in MongoDB as these are used to show download in the website. The new statistics reporting will be used for internal analytics.
The reporting is disabled until we set the environment variables in the workers control panel on CF.
- [Asana task](https://app.asana.com/0/0/1203657549452631/f) _(internal)_
- Adds disabled-by-default reporting for every block download enriched with specific block metadata.
- None, I had to test by disabling everything to run locally. I tried using [miniflare](https://miniflare.dev/) to mock the storage server, but it isn't ideal still. We should look into setting up a jest test suite that uses miniflare so we can properly test this worker. 
- We can probably also use …
> Add statistics reporting to R2 block downloading

- hub/@tldraw/drawing.json
This PR complements https://github.com/hashintel/hash/pull/2053
- [Asana task](https://app.asana.com/0/0/1203922830586240/f) _(internal)_
- Lack of `BLOCK_PROTOCOL_API_KEY_TLDRAW_PREVIEW` in https://github.com/hashdeps/tldraw-block  
↑ We can configure this later and start with publishing tldraw to prod only first.
Drawing block is stored in R2 and DB
Repeat the same process for other blocks
> Remove drawing block from `/hub`

- infra/cloudflare-r2-wrangler/index.js
This PR fixes a subtle bug in data reporting where the ID would not be set, causing downstream collector not to receive request.
Also added more context in the payload. Requires a redeploy after, sorry!
> CF worker ensure identifier is set

- apps/site/public/types/services/graph/aggregation-operation.json
- libs/@blockprotocol/graph/src/shared.ts
- libs/@blockprotocol/graph/src/types/entity.ts
- libs/@blockprotocol/hook/README.md
- libs/@blockprotocol/hook/src/react.ts
- libs/@blockprotocol/hook/src/types.ts
- libs/mock-block-dock/dev/dev-app.tsx
- libs/mock-block-dock/dev/test-react-block.tsx
- libs/mock-block-dock/src/data/property-types.ts
- libs/mock-block-dock/src/hook-portals.tsx
- libs/mock-block-dock/src/util.ts
#941 modified the aggregations syntax to allow for querying/filtering inside of Entities/Entity Types. However there was an oversight which didn't allow a distinction between array indexing and property access, this fixes it 
by allowing for the path to be expressed as strings or numbers, where strings are property accesses and numbers are array indexing.
It also updates the implementation, and then also reworks the names for the operators as they become unclear now that we aren't just operating over strings (for example you may want to find an array that contains another sub array, similar to how you would want a string that contains a substring).
This also applies the same path component logic to the hook service which was outdated due to similar reasoning.
- [Asana …
> Update aggregations syntax

- hub/@alfie/github-pr-overview.json
This PR complements https://github.com/hashintel/hash/pull/2077 and is similar to https://github.com/blockprotocol/blockprotocol/pull/972
- [Asana task](https://app.asana.com/0/0/1203922830586241/f) _(internal)_
- https://github.com/hashintel/hash/pull/2077
- https://github.com/hashdeps/github-pr-overview
> Remove GitHub PR overview block from `/hub`

- apps/site/src/lib/api/middleware/has-valid-api-key.middleware.ts
- apps/site/src/lib/api/model/api-key.model.ts
- apps/site/src/pages/settings/api-keys.page.tsx
- apps/site/src/util/usage.ts
This PR adds a `lastUsedOrigin` entry in the mongoDB, and adds the origin hostname/client address wherever the key is used.
This will be useful for client and server-side requests made to the BP and should be picked up by any route that uses `createApiKeyRequiredHandler`
- [Asana task](https://app.asana.com/0/1203358502199087/1203921545611157/f) _(internal)_
- Adds MongoDB field for `lastUsedOrigin`
- Adds UI to display the origin in the table for API keys
- Falls back to use IP addresses instead of origin if the origin doesn't exist.
No user-facing API changes.
- Manual testing
Set up local instance, create api key and use it on any endpoint requiring it, for example `localhost:3000/api/blocks`
https://user-images.githubusercontent.com/6988668/219392352-140d2e3b-39ee-43c6-ba1c-6e46d86c960 …
> Add last used origin to API key usage

- libs/@blockprotocol/type-system/crate/src/ontology/data_type/mod.rs
- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/mod.rs
- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/repr.rs
- libs/@blockprotocol/type-system/crate/src/ontology/property_type/mod.rs
- libs/@blockprotocol/type-system/crate/src/ontology/uri/mod.rs
In the HASH Graph Query Layer, we use `VersionedUri` quite often and it's impossible to destructure it into a `BaseUri` and a version.
While not necessarily every combination is valid, any `base_uri` with any `version` is a well-formed `VersionedUri`, it does not need to hold any invariants.
While other languages usually prefer "constructors", "getters", and "setters" (which are also missing), Rust has the concept of borrowing, so it's not possible to partially move out a variable of a struct by a function without consuming the struct. This implies if the `VersionedUri` has to be split into `BaseUri` and `u32`, we need something like
```rust
fn into_base_uri_and_version(self) -> (BaseUri, u32);
```
or 
```rust
fn into_parts(self) -> (BaseUri, u32);
```
which is (a) verbose to write and …
> Make fields in `VersionedUri` public

- apps/site/src/lib/api/blocks/from-tarball.ts
- apps/site/src/lib/api/blocks/s3.ts
- apps/site/src/lib/s3.ts
This PR updates block publishing process. It makes original tarballs available on R3, alongside individual files. This allows us to mirror tarballs between hub instances, thus unblocking the completion of https://github.com/blockprotocol/blockprotocol/pull/936. Uploaded tarballs are especially helpful for local dev and allow us to quickly warm up a local instance with blocks that are already published on blockprotocol.org.
- [Asana task](https://app.asana.com/0/1203358502199087/1203388867587773/f) _(internal)_
- Supplement `block-uploads` key on S3 with `block-contents` (also versioned). We can make the existing `blocks` key redundant after that.
> Upload original tarballs alongside individual block files

- libs/@blockprotocol/type-system/crate/src/ontology/data_type/mod.rs
- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/links/error.rs
- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/links/mod.rs
- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/links/repr.rs
- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/mod.rs
- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/repr.rs
- libs/@blockprotocol/type-system/crate/src/ontology/property_type/mod.rs
- libs/@blockprotocol/type-system/crate/src/ontology/shared/array/mod.rs
- libs/@blockprotocol/type-system/crate/src/ontology/shared/object/repr.rs
- libs/@blockprotocol/type-system/crate/src/ontology/uri/wasm.rs
- libs/@blockprotocol/type-system/crate/src/utils.rs
- libs/@blockprotocol/type-system/crate/tests/data/entity_type/book.json
- libs/@blockprotocol/type-system/test/entity-type.test.ts
Through usage we've discovered a number of small improvements we could make.
- The `VersionedUri` template string encourages people to put an additional slash when adding a `BaseUri`. This is incorrect as a `BaseUri` _must_ already have a trailing slash, as such, one of the slashes in the template string have been removed and the type improved slightly.
- The `default` field in `EntityType` isn't really useful in its current form, ideally users could define defaults on a per-property basis, this will require more thought and development.
- The `requiredLinks` field is now redundant in `EntityType` as there is no longer a choice for `type: "array"` of links. As such, a `required` link can be represented by `minItems: 1`.
- [Asana task](https://app.asana.com/0/1202805690238892/12035221380144 …
> Type System improvements

- libs/mock-block-dock/dev/test-react-block.tsx
- libs/mock-block-dock/src/datastore/use-mock-datastore/non-temporal.ts
- libs/mock-block-dock/src/datastore/use-mock-datastore/temporal.ts
The Graph module's `deleteEntity` message was previously unimplemented. This implements it for non-temporally versioned datastores. Temporally versioned datastores are left for a future implementation due to their increased complexity and further considerations.
- [Asana task](https://app.asana.com/0/1203623179643284/1203984164017387/f) _(internal)_
- Implements `deleteEntity` when `temporal=false` in MBD
- Driveby fixes `createEntity`
N/A
- This implementation does _not _ do any form of validation. If the deleted entity is at an endpoint of a link, then the link is deleted as well. Besides that, this does not check for link constraints such as `minItems` or `maxItems`.
N/A
- None besides `tsc` and `eslint`
- Checkout [Add demonstration of …
> Implement delete entity in MBD for non-temporally-versioned datastores

- apps/site/src/pages/api/types/entity-type/shared/db.ts
- apps/site/src/pages/api/types/property-type/shared/schema.ts
- libs/@blockprotocol/graph/src/non-temporal/main.ts
- libs/@blockprotocol/graph/src/shared/types/ontology/data-type.ts
- libs/@blockprotocol/graph/src/shared/types/ontology/entity-type.ts
- libs/@blockprotocol/graph/src/shared/types/ontology/property-type.ts
- libs/@blockprotocol/graph/src/temporal/main.ts
- libs/block-template-custom-element/package.json
- libs/block-template-custom-element/src/dev.tsx
- libs/block-template-react/package.json
- libs/block-template-react/src/dev.tsx
- libs/mock-block-dock/dev/dev-app.tsx
- libs/mock-block-dock/dev/test-custom-element-block.ts
- libs/mock-block-dock/dev/test-react-block.tsx
- libs/mock-block-dock/package.json
- libs/mock-block-dock/src/data/entities.ts
- libs/mock-block-dock/src/data/entity-types.ts
- libs/mock-block-dock/src/debug-view/dev-tools/entity-switcher.tsx
With the current state of the `0.3` branch almost all usages will require a dependency on the `@blockprotocol/graph` package _and_ the `@blockprotocol/type-system` package. The latter of which has a learning curve due to advanced functionalities that require initialisation of WASM.
This lowers the barrier to entry by re-exporting non-WASM requiring functions and types from the type-system package, so that users can simply add the graph module package as a dependency.
- [Asana task](https://app.asana.com/0/1203358502199087/1203922286227449/f) _(internal)_
N/A
See description
As we refine the new version of the spec we will probably want to help power-users discover the type system package and understand when they may need to import it directly.
N/A
N/A
- `tsc`
- `eslint`
Watch CI
> Re-export central "type-system" elements from the Graph Module package

- apps/site/src/pages/api/types/entity-type/shared/schema.ts
- libs/@blockprotocol/graph/src/non-temporal/custom-element.ts
- libs/@blockprotocol/graph/src/shared/codegen/entity-type-to-typescript.ts
- libs/@blockprotocol/graph/src/temporal/custom-element.ts
- libs/block-template-custom-element/package.json
- libs/block-template-custom-element/src/app.ts
- libs/block-template-custom-element/src/dev.tsx
- libs/block-template-custom-element/src/types.gen.ts
- libs/block-template-react/package.json
- libs/block-template-react/src/app.tsx
- libs/block-template-react/src/dev.tsx
- libs/block-template-react/src/types.gen.ts
1. Start using a generic `Thing` type as the default type in block templates
2. Handle some crashes in the JSON schema -> TS codegen if `allOf` is present but not a populated array
3. Set a default `description` as the entity type metaschema requires it (folllow up: add a description field to form)
4. Remove derived properties from custom element template due to a timing issue with message passing
---
- https://app.asana.com/0/0/1203823571506509
> Update + fix block templates, schema -> TS codegen

- .github/workflows/ci.yml
- apps/site/README.md
- apps/site/scripts/reset-s3-bucket.ts
When publishing block to a local bucket, I noticed that its contents were not available at http://localhost:3000/hub.
Opening direct asset links was showing this error:
It turned out that port 9001 was for MinIO's [web console](https://min.io/docs/minio/linux/administration/minio-console.html#static-vs-dynamic-port-assignment), so I changed port to 9000 in our CI config and docs. However, accessing objects at port `9000` did not help either:
After the investigation, I discovered that bucket permissions for local dev were not configure correctly. This PR fixes that.
- [Asana task](https://app.asana.com/0/1203358502199087/1203388867587773/f) _(internal)_
- https://github.com/blockprotocol/blockprotocol/pull/565
- See diff
- Existing developers need to open  `apps/site/.env.local` and …
> Fix access to block assets in a local S3 instance

- apps/site/src/_pages/docs/1_developing-blocks.mdx
- apps/site/src/components/pages/hub/json-editor.tsx
- apps/site/src/styles/prism.css
- hub/@hash/code.json
1. Fixes docs instructions to specify that you must use `[template]@canary` when running `create-block-app`.
2. Bump code block to get improvements made in https://github.com/hashintel/hash/pull/2107 and https://github.com/hashintel/hash/pull/2108
3. Wraps text in hub JSON editor – now that property keys are URIs, it is pretty difficult to edit the JSON without wrapping
**Before**
**Now**
https://user-images.githubusercontent.com/37743469/220335490-5900aacf-fe95-4eea-94ec-3a7ffa46a989.mp4
> Better hub JSON editing. Bump code block. Docs fixes

- libs/mock-block-dock/dev/test-react-block.tsx
- libs/mock-block-dock/src/debug-view/dev-tools/datastore-graph-visualization.tsx
At some point in the previous changes the datastore visualization was broken in `mock-block-dock`. This PR fixes it, and improves upon the previous implementation by overriding the edge labels to make them more readable.
- [Asana task](https://app.asana.com/0/1203358502199087/1203994531454209/f) _(internal)_
N/A
- Stop using `RecordId` as the ID's of the nodes, instead opting to use `VertexId`
- Improve a lot of the typings to rely on the actual typings of the library
- Improve the display label of edges by using a prettified name of the edge-kind, rather than the exceptionally long ID
- I don't believe so
- This implementation was always a quick addition to add some functionality, there's a fair bit of UX work we can do to improve the component, including configuration options, …
> Fix mock-block-dock datastore visualization

- apps/site/src/pages/api/types/entity-type/shared/schema.ts
`null` is not a valid value for `EntityType["links"]`, but that's what it was being set as in the db if no value for it was provided.
This introduces a fallback to `{}`, which is valid, and prevents nullish fields being set on an `EntityType` to avoid further such traps (unless there is some future reason to allow `null` for any value).
> Fix entity default schema

- hub/@hash/callout.json
- hub/@hash/divider.json
- hub/@hash/header.json
- hub/@hash/paragraph.json
- hub/@hash/table.json
- hub/@timdiekmann/countdown.json
- hub/@timdiekmann/timer.json
This PR removes several blocks from `/hub`. The blocks are re-published via CLI which has been introduced in https://github.com/hashintel/hash/pull/2043
- [Asana task](link) _(internal)_
- Publish job: https://github.com/hashintel/hash/actions/runs/4240967603
When this PR is merged, I will run publish job for production: https://github.com/hashintel/hash/actions/workflows/publish-blocks-to-production.yml
Open preview release and ensure that blocks in the diff are still there.
> Prepare several blocks for republishing

- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/error.rs
- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/repr.rs
- libs/@blockprotocol/type-system/crate/src/ontology/shared/object/error.rs
- libs/@blockprotocol/type-system/crate/src/ontology/shared/object/repr.rs
- libs/@blockprotocol/type-system/crate/tests/data/property_type/contact_information.json
- libs/@blockprotocol/type-system/crate/tests/data/property_type/interests.json
- libs/@blockprotocol/type-system/test/entity-type.test.ts
- libs/@blockprotocol/type-system/test/property-type.test.ts
#937 required "additionalProperties: false" on entity types. This also should be present on property type objects. This PR fixes that.
This crate/package at the moment is treated as the source of truth and spec, the types being updated therefore constitute a change to the docs for now.
N/A
N/A
- Type System crate tests
- Type system node package tests
1.  Checkout the branch / view the deployment
1.  `yarn` should pass, rebuilding the Type System crate
1.  `yarn workspace @blockprotocol/type-system test` should pass
1.  `cargo make test` should pass inside the `type-system/crate` directory 
1.  `cargo make lint` should pass inside the `type-system/crate` directory
> Add `additionalProperties: false` to property type objects

- libs/@blockprotocol/graph/src/temporal/main.ts
A generic was missed when re-exporting a type
> Fix missing generic in export

- apps/site/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page.tsx
The `type-editor` package only deals with `links` and `properties` on an entity type, which means that the consumer is repsonsible for maintaining any other properties on an entity type, e.g. when updating.
The BP site wasn't doing that – this PR fixes that by adding in the existing entity type underneath whatever the type editor is sending as an update.
I am going to separately update the return of `getSchemaFromFormData` in the type editor which is currently a `Partial<EntityType>` to more accurately reflect 'links and properties only'
> Fix entity type updates

- apps/site/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page.tsx
In #1012 I switched to only sending `properties` and `links` from the type editor because I thought that's all it sent. But it also sends `required`. This PR fixes that.
> Fix entity type fix

- libs/mock-block-dock/dev/test-html-block/block.js
- libs/mock-block-dock/src/mock-block-dock.tsx
The HTML block was broken, with #1006 it could be fixed.
- [Asana task](https://app.asana.com/0/1203358502199087/1203866892869243/f) _(internal)_
N/A
- Updates the versions of the dependencies used in the HTML block
- Updates the callbacks to the new ones
- Replaces properties access with BaseURIs
- Driveby fixes ESLint
Not to my knowledge
- There's a chicken and egg problem at the moment where we need to publish a version of the packages before being able to update the HTML block due to using `esm.sh`
- It's quite slow to load, and it's not clear it's trying to load while that happens
N/A
None
Run MBD, check the two HTML block variants work
> Fix HTML block in mock-block-dock

- libs/@blockprotocol/type-system/crate/src/ontology/url/error.rs
- libs/@blockprotocol/type-system/crate/src/ontology/url/mod.rs
- libs/@blockprotocol/type-system/src/native/url.ts
- rfcs/text/0408-versioning-types.md
Various browsers define different max lengths for URLs. We opt to go with the conservative limit of 2048, thus limiting the risk vector of denial-of-service attacks when dealing with regex's that validate URLs.
This updates the functions for validating URLs, and updates the respective RFC.
- [Asana task](https://app.asana.com/0/1203358502199087/1204053055714039/f) _(internal)_
N/A
- Adds a new `TooLong` error variant to the validation functions for URLs
- Returns the error when the length is greater than 2048
- Updates the RFC to refer to this, and the decision to have a trailing slash on Base URIs
- No, it perhaps should be mentioned in the spec (which we are working on imminently)
N/A
N/A
- Type System crate tests
- Type system node package tests
1.  Checkout the branch / view the …
> Set a max-length on URL

- libs/@blockprotocol/core/src/react.ts
- libs/@blockprotocol/graph/src/non-temporal/custom-element.ts
- libs/@blockprotocol/graph/src/non-temporal/graph-embedder-handler.ts
- libs/@blockprotocol/graph/src/non-temporal/main.ts
- libs/@blockprotocol/graph/src/non-temporal/react.ts
- libs/@blockprotocol/graph/src/temporal/custom-element.ts
- libs/@blockprotocol/graph/src/temporal/graph-embedder-handler.ts
- libs/@blockprotocol/graph/src/temporal/main.ts
- libs/@blockprotocol/graph/src/temporal/react.ts
- libs/block-template-react/src/app.tsx
- libs/mock-block-dock/dev/test-react-block.tsx
The block entity subgraph is a fundamental part of a block that works with the graph module. So much so that it seems silly to have it something that the embedding application can choose not to send to the block, which leads to having to check for its existence all over the place, always throwing an error if it doesn't exist because most graph-dependent blocks won't function without it.
This PR makes `blockEntitySubgraph` a required part of the `graph` messages sent to a block.
- [Asana task](https://app.asana.com/0/1203358502199087/1203701650452072/f) _(internal)_
> Make blockEntitySubgraph required in graph properties sent to block

- apps/site/src/middleware.page/return-types-as-json.ts
- apps/site/src/middleware.page/return-types-as-json/hardcoded-types.ts
#1041 removed the `additionalProperties` field. We're currently manually hosting a link type on the prod site, this updates it.
> Patch link type

- apps/site/src/components/pages/user/placeholder-buttons.tsx
- apps/site/src/components/pages/user/placeholder.tsx
- apps/site/src/components/pages/user/tab-panel-contents-with-overview.tsx
- apps/site/src/components/pages/user/tab-panel-contents-with-schemas.tsx
- apps/site/tests/integration/accountpage.test.ts
- apps/site/tests/integration/schema-creation.test.ts
Corrects some copy consistency – rename 'schema' to 'Entity Type' when we are talking about creating entity types.
This also fixes and un-skips one of the tests that were skipped in the `0.3` branch
Also sorts out centering text.
> Correct 'schema' to 'entity type' in copy, fix schema creation test

- apps/site/public/types/modules/graph/0.3/schema/data-type.json
Currently, we use `"$ref"` in the data-type *meta* schema in the `"oneOf"`. This, however, does not make sure, that the expected data type schema is matching the meta schema, but it tries to match the actual data type.
- [Slack discussion](https://hashintel.slack.com/archives/C02LG39FJAU/p1677531751197249) _(internal)_
- [Asana Task](https://app.asana.com/0/1203623179643287/1204068318790075/f) _(internal)_
- Change the `"oneOf"` to fix the `"$id"` property. This is sufficient, that no more data types can be published which are matching the `"https://blockprotocol.org/types/modules/graph/0.3/schema/data-type"` schema.
- Drive-by: Remove unneeded `"type": "string"` in `"$schema"` field 
- The meta schema is part of the documentation
Downstream implementations may rely on the `"oneOf"` …
> Fix `data-type` meta schema definition

- apps/site/public/types/modules/graph/0.3/schema/property-type.json
We have a typo in the `property-type`'s meta schema.
> Fix misspelled `schema` in property type meta schema

- apps/site/src/pages/api/rewrites/sandboxed-block-demo.api.ts
- libs/@blockprotocol/graph/src/non-temporal/main.ts
- libs/block-template-html/dev/index.html
- libs/block-template-html/src/app.js
- libs/mock-block-dock/dev/test-html-block/block.js
We've been using canary versions during development, it's time to upgrade as we're about to release
> Remove canary versions from `esm.sh` links

- apps/site/src/_pages/docs/1_developing-blocks.mdx
We have published the blocks, so we don't need `@canary` anymore
---
- https://app.asana.com/0/0/1204038271168774
> Remove `@canary` from Block development documentation

- apps/site/src/lib/blocks.ts
- apps/site/src/lib/config.ts
Make sure a `verified` status is set on block creation. Lists some starting trusted authors whose blocks are automatically verified. See https://blockprotocol.org/docs/faq#how-does-block-verification-work
> Explicitly set 'verified' status on blocks when created

- apps/site/src/components/pages/hub/sandboxed-block-demo.tsx
- apps/site/src/components/pages/hub/sandboxed-block-demo/service-module-modal.tsx
- apps/site/src/pages/api/rewrites/sandboxed-block-demo.api.ts
Some blocks now call services that incur usage costs (in the form of BP credits or real money if the user is on a paid account and has exhausted their credits). This normally requires an API key, which isn't present in the Block Hub. Those blocks are therefore non-functional for the time being.
This PR shows a modal if a block tries to call an external service informing the user of the fact. 
A follow-up PR tomorrow will offer logged-in users the chance to use their credits (or money) on testing the block.
- [Asana task](https://app.asana.com/0/1203623179643287/1204086167143590) _(internal)_
- Part 2 will offer logged-in users the chance to allow this block to make calls, so they can test it properly.
1.  In the preview deployment, go to a service-calling block's page (e.g. AI Text, AI …
> Handle service module blocks in the hub (part 1)

- apps/site/src/_pages/docs/1_developing-blocks.mdx
See title
- [Slack thread](https://hashintel.slack.com/archives/C02LG39FJAU/p1677682385161489) _(internal)_
- Merge sections, which recommends running `npx create-block-app`
- Mention, that the below sections will assume the `--template react` and mention that being the default
> Improve documentation around block creation

- .github/workflows/ci.yml
GH Actions uses the cache from the same branch and falls back to the base branch. The base branch after creating a PR is the `main` branch, so if the CI is not running on a `push` to main it cannot be created
- [Asana task](https://app.asana.com/0/1203623179643290/1204099711044327/f) _(internal)_
- Run CI on `push` to main
> Create GH cache after merging a Pull Request

- .github/workflows/ci.yml
The CI currently runs only on pull request targeting `0.3` and `main` while the former does not exist anymore.
When stacking PR, it's currently not possible to check linting as the CI does not run at all.
- [Asana task](https://app.asana.com/0/1203623179643290/1204099711044327/f) _(internal)_
- Enable CI runs for all pull request
- Drive-by: Add `merge_group` as target, **this should enable us to use the merge queue**
> Run CI on any Pull Request (or merge queue event)

- .github/actions/warm-up-repo/action.yml
The Rust jobs is the same for all kind of jobs, we can share the cache
> Use shared cache for Rust jobs

- libs/@blockprotocol/type-system/crate/Cargo.toml
- libs/@blockprotocol/type-system/crate/Makefile.toml
- libs/@blockprotocol/type-system/package.json
There is no point in compiling a huge binary to reduce the size of the WASM file by 300 kb, if it's only used locally. This significantly slows down CI times. This PR adjusts the `build` command to not optimize the WASM file. The optimization is still run by the `prepublishOnly` job.
> Use `wasm-opt` from `wasm-pack`

- .github/actions/warm-up-repo/action.yml
Downloading the yarn cache is only by about 20s to 30s faster, however, pollutes the cache we have available on GitHub. Also, uploading that cache takes at least that long, usually longer (the cache currently is about 1.2 GB per yarn cache).
> Disable yarn caching

- .github/workflows/ci.yml
- .github/workflows/site-deployment.yml
We don't need to run CI checks for commits which are outdated.
- [Slack thread](https://hashintel.slack.com/archives/C02TWBTT3ED/p1677854234827139) _(internal)_
> Cancel previous jobs when newer commits were added

- .github/workflows/ci.yml
Especially in the merge queue, I encounter many errors related to this. In HASH we disabled this due to flakiness as well.
> Disable codecov reporting status requirement

- .github/actions/warm-up-repo/action.yml
- libs/@blockprotocol/type-system/crate/Makefile.toml
- libs/@blockprotocol/type-system/package.json
- yarn.lock
Compiling `wasm-pack` is really slow. Instead of compiling it, this will change the behavior of `cargo-make` to download it instead as officially recommended
> Download `wasm-pack` instead of compiling it

- libs/wordpress-plugin/plugin/trunk/block-protocol.php
- libs/wordpress-plugin/plugin/trunk/server/block-db-table.php
- libs/wordpress-plugin/plugin/trunk/server/data.php
This PR adds some information that has been missing from the client error reports we've received. I've also decreased the `view` event to send more regularly as the previous value was too high.
Settings are required/loaded up front so we don't misread the user's telemetry setting or the default.
Also the MariaDB fix wasn't necessary, we just had to add the column name to the foreign key (tested with MariaDB 10.6.12)
These changes together will allow us to better figure out exception reasons in the future.
- #1123
> Better error reporting for the WordPress plugin

- apps/site/src/components/pages/pricing/paid-tiers-section.tsx
- apps/site/src/pages/settings/billing-settings-panel/external-service-free-allowance.ts
- apps/site/src/pages/settings/billing-settings-panel/free-or-hobby-subscription-tier-overview.tsx
- apps/site/src/pages/settings/billing-settings-panel/pro-subscription-tier-overview.tsx
This PR updates copy in the BP site to reflect the updated Mapbox Autofill free allowances:
- 10 sessions for free users
- 25 sessions for Hobby users
- 50 sessions for Pro users
It also re-defines the external service free allowance in a re-usable way, by introducing a `externalServiceFreeAllowance` object. In follow-up we should replace all references to free usage with usages of the `externalServiceFreeAllowance` object.
- [Asana task](https://app.asana.com/0/1203623179643287/1204092897972678/f) _(internal)_
> Update copy regarding Mapbox Autofill free allowance

- libs/wordpress-plugin/plugin/trunk/block-protocol.php
- libs/wordpress-plugin/plugin/trunk/server/block-db-table.php
This PR adds a notice if the database used for WordPress is unsupported in the admin settings - we also totally disable the migrations and admin-part of the post viewing to disable any issues. If the admin can't even make blocks, the user-facing post won't run into errors.
We use a generic message to prevent any abuse in exposing the exact DB version through the notice.
- [Asana task](https://app.asana.com/0/1203623179643290/1204120050952648/f) _(internal)_
- #1123 
- Adds a new check for the DB version using our documented versions
- Adds early bails for admin init and migrations
- Adds `admin_notice` for when the DB version is unsupported
Change docker compose "db" service to 
```yaml
db:
platform: linux/amd64
image: mariadb:10.2.6
ports:
- "3306:3306"
volumes:
- db_data:/var/lib/mysql …
```
> Add unsupported database version notice to WordPress plugin

- infra/docker/wordpress/docker-compose.yml
- libs/wordpress-plugin/README.md
- libs/wordpress-plugin/package.json
This PR moves the `docker-compose.yml` used for developing the wordpress plugin into the `infra/docker/wordpress` directory. I've updated the `package.json` to reflect this and updated the readme as I've removed the `up` from the yarn script.
The change to the yarn script is so we can more easily shut down the server and delete the volume by doing `yarn dev:wordpress down -v`
- [Asana task](https://app.asana.com/0/1203623179643290/1204086165607416/f) _(internal)_
- See PR purpose
- I've updated the README to reflect the `yarn script` being `yarn dev:wordpress up` now
None, this would be part of the dev workflow
Checkout branch, run readme instructions, there should be no change
> Move `docker-compose.yml` for the WordPress plugin to `infra/docker/wordpress`

- apps/site/sentry.client.config.ts
Visiting a block's page in incognito, if you have third-party cookies disabled in incognito, will result in the following error and the iFrame code not working:
```
Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
```
This is because Chrome treats `sessionStorage` access on the same basis as third-party cookies, at least this case (i.e. deny access if third-party cookies are denied).
I [previously thought ](https://github.com/blockprotocol/blockprotocol/pull/768) this was to do with Sentry Replay, but they patched the unchecked access to `sessionStorage`. I'm a bit perplexed now, so this is an attempt to fix. This branch's preview deployment does not have the issue, but then nor does any preview deployment (probably due to the difference in …
> Disable Sentry Replay sticky session

- apps/site/src/components/pages/hub/block-data-container/sandboxed-block-demo/service-module-modal.tsx
- libs/wordpress-plugin/package.json
- libs/wordpress-plugin/plugin/trunk/block/edit-or-preview/edit/service-callbacks.ts
- libs/wordpress-plugin/plugin/trunk/changelog.txt
- libs/wordpress-plugin/plugin/trunk/readme.txt
- libs/wordpress-plugin/yarn.lock
1. Introduce support for ChatGPT BP blocks (and note in changelog)
2. Tweak the WP plugin's error message when exceeding a service's free credits – it previously used the method name, which may not be equivalent to the service. e.g `Davinci` is a service, but the method name is `completeText`, which covers other services (language models, in this case).
3. Update the modal shown to users when trying to use a service-using block in the Hub to include login/signup buttons for anonymous viewers
> WordPress ChatGPT support, tweak usage exceeded error message

- apps/site/src/_pages/legal/terms/1_products.mdx
- apps/site/src/components/pages/pricing/free-tier-section.tsx
- apps/site/src/components/pages/pricing/paid-addons-section.tsx
- apps/site/src/components/pages/pricing/paid-tiers-section.tsx
- apps/site/src/pages/settings/billing-settings-panel/external-service-free-allowance.ts
- apps/site/src/pages/settings/billing-settings-panel/free-or-hobby-subscription-tier-overview.tsx
- apps/site/src/pages/settings/billing-settings-panel/pro-subscription-tier-overview.tsx
This PR adds "GPT-3.5 Turbo" copy to the BP site, informing users of the price and free allowance of the "GPT-3.5 Turbo" OpenAI model.
- [Asana task](https://app.asana.com/0/1203623179643290/1204092897972686/f) _(internal)_
> Add "GPT-3.5 Turbo" copy to the BP site

- apps/site/src/pages/settings/billing-settings-panel/free-or-hobby-subscription-tier-overview.tsx
- apps/site/src/pages/settings/billing/upgrade/index.page.tsx
This PR:
- updates the checkout page to open the "Terms of Service" and "Privacy Statement" links in new tab
- reduces the right margin of the feature lists in the `/settings/billing` page to prevent text from wrapping (see attached screenshot)
- [Asana task](https://app.asana.com/0/1203623179643290/1204144201804771/f) _(internal)_
> Open "Terms of Service" and "Privacy Statement" links in new tab in checkout page + styling tweaks

- apps/site/src/components/pages/hub/hub.tsx
- apps/site/src/pages/hub.page.tsx
This PR adds the verified badge to the blocks listed in the block hub.
- [Asana task](https://app.asana.com/0/1203623179643290/1204086167143859/f) _(internal)_
1.  Checkout the branch / view the deployment
1.  Open block hub
2. Confirm the screenshot below
> Add verified badge to blocks on block hub

- apps/site/package.json
- apps/site/src/components/pages/hub/hub-list-browse.tsx
- apps/site/src/components/pages/hub/hub-utils.tsx
- apps/site/src/components/pages/hub/hub.tsx
- yarn.lock
Improve `/hub` list loading UX using skeleton loaders and staggered fade-in animation
- [Asana task](https://app.asana.com/0/1203179076056186/1204062182948733/f) _(internal)_
- Add `framer-motion` as a dependency
1.  Checkout the branch / view the deployment
1.  Open `/hub`
1. Test the behavior shown in the demo below
https://user-images.githubusercontent.com/39553853/224712447-48ca0910-8ca2-44b2-bbf6-b517e909d01c.mov
> Improved animations & loading on `/hub` page

- .changeset/seven-comics-beam.md
- libs/block-template-custom-element/src/dev.tsx
- libs/block-template-html/dev/index.html
- libs/block-template-react/src/dev.tsx
- libs/mock-block-dock/dev/dev-app.tsx
- libs/mock-block-dock/src/datastore/use-mock-datastore/non-temporal.ts
- libs/mock-block-dock/src/datastore/use-mock-datastore/shared.ts
- libs/mock-block-dock/src/datastore/use-mock-datastore/temporal.ts
- libs/mock-block-dock/src/mock-block-dock.tsx
- libs/mock-block-dock/src/use-mock-block-props.ts
- libs/mock-block-dock/src/util.ts
Delays in responses to methods from an EA can **very easily** result in strange errors in components. Such errors were very difficult to identify during block development because MockBlockDock responded very quickly to requests.
This PR introduces a new prop which allows the user to configure a latency range whereby responses from the Graph Module will delay for a random time in ms from within that range.
- [Asana task](https://app.asana.com/0/1203179076056186/1204144427699229/f) _(internal)_
N/A
- Introduces a `simulateLatency` prop in MBD
- Adjusts the Graph module callbacks to wait for a random time within the given latency range
- Updates the templates to provide the parameter
- I'm unsure if there is documentation about MBD props, I have updated the templates and given an …
> Add latency simulation to `mock-block-dock`

- .changeset/plenty-camels-crash.md
- .changeset/sharp-stingrays-scream.md
- .changeset/sharp-tools-bow.md
- .changeset/swift-countries-arrive.md
- libs/@blockprotocol/core/src/core-block-handler.ts
- libs/block-template-custom-element/package.json
- libs/block-template-react/package.json
- libs/mock-block-dock/package.json
- libs/mock-block-dock/src/block-renderer/custom-element.tsx
- libs/wordpress-plugin/plugin/trunk/block/shared/block-loader/block-renderer/custom-element.tsx
- yarn.lock
Fixes a few issues I noticed while building a custom element block:
1. The `CoreBlockHandler` includes a retry on its `init` message if it doesn't receive an immediate response, but this can cause an infinite loop with rendering custom elements (not while running them in dev mode, but once built). This PR fixes that by moving the retry from a `queueMicrotask` to a `setTimeout`. I chose not to bring a dependency to make it `setImmediate`, which would be a bit quicker middleground, on the basis that for most use cases it isn't vital that init messages are exchanged in the fastest possible time, and avoiding `setImmediate` saves adding another 1KB to every block.
2. The logic for renaming custom element tags was broken – I haven't actually encountered any duplication of custom element tag …
> Fix block message init retry and custom element rendering

- apps/site/src/components/pages/auth-wall.tsx
- apps/site/src/pages/_app.page.tsx
- apps/site/src/pages/settings/billing-settings-panel/subscription-feature-list-item.tsx
- apps/site/src/pages/settings/billing/upgrade/index.page.tsx
- apps/site/src/pages/settings/billing/upgrade/upgrade-page-layout.tsx
- apps/site/src/pages/shared/next-types.ts
This PR adds a custom layout to the upgrade subscription page.
- [Asana task](https://app.asana.com/0/1203623179643290/1203906467538586/f) _(internal)_
- adds support for a `getLayout` function on next pages
Manual testing.
Go to the upgrade subscription page, and observe the new layout (locally or in the preview deployment)
> Add custom upgrade subscription page layout

- .changeset/twelve-spies-whisper.md
- libs/block-template-custom-element/src/dev.tsx
- libs/block-template-html/dev/index.html
- libs/block-template-react/src/dev.tsx
- libs/mock-block-dock/dev/dev-app.tsx
- libs/mock-block-dock/src/mock-block-dock.tsx
- libs/mock-block-dock/src/use-mock-block-props.ts
MockBlockDock ships with sample entities and links to help jump-start block development and experimentation. While this is helpful in a lot of cases (especially when getting started and wanting to follow tutorials), it can prove annoying when trying to focus on block logic to do with entity creation. For example, if working with a block which creates links of `Date`s and `Event`s, the completely unrelated mock-data can get in the way.
As such this PR makes the data configurable through a simple toggle on the props of MBD.
- [Asana task](https://app.asana.com/0/1203358502199087/1204080201525396/f) _(internal)_
- Adds an `includeProvidedMockData` prop on MBD
- Fills that in as `true` by default in block templates
- Unsure if this is mentioned in tutorials or anywhere else.
- This …
> Make the inclusion of mock data optional in MockBlockDock

- libs/wordpress-plugin/plugin/trunk/block/edit-or-preview/edit/block-controls.tsx
We show a form in the WordPress plugin settings sidebar which is generated from the block's schema.
For some blocks, this form is potentially confusing and may lead to the block breaking if properties are edited in unexpected ways when it is in certain states.
The best solution to this is for blocks to be able to specify which properties should be editable externally, so that the plugin needs no knowledge of any particular block, but in the short term this hides the editor for blocks where it may be a problem.
> Hide entity editor for certain blocks in the WordPress plugin

- apps/site/sentry.client.config.ts
Reverts blockprotocol/blockprotocol#1139
I'm confident that this is not the cause of the 'hub errors in incognito issue', which I believe is something to do with esm.sh
> Revert "Disable Sentry Replay sticky session"

- .github/workflows/attach-pr-to-asana-task.yml
Adds the Asana integration which automatically adds PR links to tasks linked in task descriptions.
- [Asana task](https://app.asana.com/0/1204000740778935/1204143704715742/f) _(internal)_
- Asana has been a bit flaky contacting GitHub this week (sometimes PR links cannot be added manually to tasks, sometimes they can).
1.  Confirm that the action worked:
> Add GitHub workflow to attach Pull Request to Asana task

- libs/@blockprotocol/graph/src/non-temporal/stdlib.ts
- libs/@blockprotocol/graph/src/shared/stdlib.ts
- libs/@blockprotocol/graph/src/shared/stdlib/subgraph/builder.ts
- libs/@blockprotocol/graph/src/temporal/stdlib.ts
- libs/mock-block-dock/src/datastore/use-mock-datastore/non-temporal.ts
- libs/mock-block-dock/src/datastore/use-mock-datastore/temporal.ts
This PR changes how we update entities to take into account that edges may need to recompute. It does so by removing all edges and recompute them through the `infer` functions.
- [Asana task](https://app.asana.com/0/1203623179643290/1204145497706392/f) _(internal)_
- Added new `inferSubgraphEdges` helper to recompute all edges of the graph given the vertices
- Delete edges on update
- Recompute the edges on update through `inferSubgraphEdges`
I suggest the following test setup:
- checkout `asa/temp-updateentity-mbd` at commit `5c8668d98716c0431939df090ddb323c7a3dedbd`
- Build `@blockprotocol/graph` and `mock-block-dock`
- `yarn dev` from the block at `blocks/aio-demo` 
Operations on the subgraph through the dev block should result in the right edges being present.
This demo may be hard to …
> Add helper function for fully recomputing edges in Subgraph

- .github/workflows/ci.yml
- package.json
We have a linting step which checks if there are any changes to packages without a changeset being present. The precursor to this step, which pulls `main` of the repo so that the [Changesets CLI](https://github.com/changesets/changesets/blob/main/packages/cli) has access to it, causes occasional errors, which were the initial motivation for investigating it:
We could attempt to fix this (e.g. by specifying a reconciliation strategy), but the linting step seems of questionable value anyway – it only errors if there are changes any packages but no changeset file exists _at all_ in the repo. It does not verify that a changeset file exists for the package that has been changed in a PR, let alone whether it was created as part of the commits in the PR. The presence of any changeset file …
> Remove Changeset linting for the existence of a changeset file

- apps/site/src/components/pages/hub/block-data-container.tsx
- apps/site/src/components/pages/hub/block-data-container/sandboxed-block-demo.tsx
Implement [this PR suggestion](https://github.com/blockprotocol/blockprotocol/pull/1138#discussion_r1129265623) to not persist a user's decision as to whether a block in the hub can call external services in session storage, as it may confuse users if they revisit the block and it doesn't work – instead, store it in component state that resets every time they revisit the block's page.
- [Asana task](https://app.asana.com/0/1203623179643290/1204138539312008/f) _(internal)_
1.  Visit e.g. the AI text block in the preview deployment, use it, see modal, make choice
2. Visit another block, revisit AI text block, see modal again
> Move 'can block call services' decision from session storage to component state

- libs/wordpress-plugin/plugin/trunk/server/data.php
This PR adjusts our Sentry usage so we don't overwrite existing sentry configurations (that are using the Sentry SDK). 
We still catch and report manually instrumented errors (such as DB errors and API errors) because of our `block_protocol_maybe_capture_error` function.
The diff may be a little annoying functions in the file were moved around.
- [Asana task](https://app.asana.com/0/1203358502199087/1204147504869254/f) _(internal)_
- Adds conditional sentry setup (checks if existing config exists with another DSN we don't know about)
- As a fallback we manually/explicitly catch any errors that we instrument with `block_protocol_maybe_capture_error`.
- Add anonymous user identifier as a sentry tag
Testing this is a little convoluted and requires another sentry project to test against
- Set …
> Conditionally enable Sentry error reporting in the WordPress plugin

- .changeset/plenty-files-sneeze.md
- libs/block-scripts/package.json
- libs/block-scripts/shared/webpack-config.js
- libs/block-template-custom-element/.gitignore.dist
- libs/block-template-custom-element/README.md
- libs/block-template-react/.gitignore.dist
- libs/block-template-react/README.md
Adds support for using `.env` files in blocks in development. Helpful now that we accept a `blockProtocolApiKey` in `MockBlockDock` to be able to set this from `process.env`.
- [Asana task](https://app.asana.com/0/1203623179643290/1204089119834164/f) _(internal)_
- README has been updated.
1.  Add a `.env` file to one of the block templates, put something in it
2. Try logging out `process.env.VARIABLE_NAME` in the block
> Add support for .env files in block templates

- apps/site/src/pages/api/rewrites/sandboxed-block-demo.api.ts
- libs/mock-block-dock/src/version.ts
We have an import path for Mock Block Dock in the sandbox iFrame that needs fixing following #1162
> Fix import path for mock block dock in sandbox

- libs/wordpress-plugin/plugin/trunk/server/block-api-endpoints.php
This PR removed a stray `$` that caused the `if` statement to never pass. Perhaps `?:` or `??` would be best here, but this should be fine (tested locally)
> Remove stray `$`

- .github/actions/warm-up-repo/action.yml
- libs/@blockprotocol/type-system/crate/.justfile
- libs/@blockprotocol/type-system/package.json
- libs/@blockprotocol/type-system/scripts/build-wasm.ts
- yarn.lock
We encountered quite a few issues with installing `wasm-pack` through `yarn`.
- [Slack thread](https://hashintel.slack.com/archives/C04SP1PGKC1/p1679054824550009) _(internal)_
- Add `install-tool` recipe to `.justfile`
- Install `wasm-pack` if not already installed or installed with wrong version
- Drive-by: Add check for error before trying to print stdout
> Manually install `wasm-pack`

- apps/site/src/pages/settings/billing-settings-panel/billing-overview.tsx
- apps/site/src/pages/settings/billing-settings-panel/payment-history-section.tsx
This PR enables anyone with an active stripe subscription (including those with a "free" subscription tier) to edit their payment method.
It also fixes an issue where a runtime error is thrown for users with an inactive stripe subscription in the `PaymentHistorySection` component.
- [Update BP site to let user change payment method when they have a "free" account](https://app.asana.com/0/1204000740778935/1204188703131678/f) _(internal)_
- [Catch errors when a user without a subscription loads billing page](https://app.asana.com/0/1204000740778938/1204173853214856/f) _(internal)_
- when a user has an active stripe subscription on the "free" tier, they are not able to use the existing upgrade subscription flow ([asana task](https://app.asana.com/0/0/1204188703131699/f))
Manual testing.
1. …
> Allow "free" users to update payment method

- apps/site/src/components/pages/wordpress/why-install.tsx
Adds missing padding to BP icon on `/wordpress` page.
- [Asana task](https://app.asana.com/0/1204000740778938/1204203279487405/f) _(internal)_
> Add missing padding to BP icon

- apps/site/src/components/navbar.tsx
- apps/site/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page.tsx
- apps/site/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page/entity-type-edit-bar.tsx
The Edit Bar, which displays when you have pending changes to an entity type, can appear out of view. This PR makes it sticky, so it scrolls with the viewport. It also ensures the header doesn't hide when on the entity type editor, to make it easier to know where to position the edit bar, and associated visual changes.
**Importantly, it also changes the URL management for entity types from a push to a replace**, and removes the scroll up. This is to prevent the scroll up when publishing new versions, which wasn't evident before as you had to be scrolled up to access the edit bar anyway. This also prevents history being polluted with previous versions, and matches the behaviour in HASH. There is a minor chance replace may be used instead of push when that isn't desirable – i.e, if you've …
> Edit bar improvements in entity type editor 

- libs/@blockprotocol/design-system/package.json
We have a CI check which publishes packages to a local registry to check that they publish successfully – this is currently [failing](https://github.com/blockprotocol/blockprotocol/actions/runs/4510198147/jobs/7940865428) on a new package, `@blockprotocol/design-system`. 
It's not clear why, but making this package `private: true` until we actually need to publish it to NPM will allow us to defer figuring it out.
> Make @blockprotocol/design-system private temporarily

- .github/labeler.yml
- Removes deprecated label (`area: hub`)
- Renames `area: docs` to `area: copy` and updates matching rules around this
- Implements various new rules including automatic tagging of testing-related changes as `area: testing`
> Update GitHub labeler

- libs/wordpress-plugin/README.md
- libs/wordpress-plugin/plugin/trunk/changelog.txt
- libs/wordpress-plugin/plugin/trunk/readme.txt
- libs/wordpress-plugin/plugin/trunk/server/block-api-endpoints.php
- libs/wordpress-plugin/plugin/trunk/server/block-db-table.php
This PR adds a "native" PHP-based graph traversal function that can be dynamically used at runtime if the database is at version (MySQL 8+|MariaDB 10.2.2+)
I haven't changes the minimum version of MariaDB in this PR as `10.2.7` introduced JSON, at `10.2.2` we have migration errors which hopefully can be addressed/adjusted in a follow-up.
- [Asana task](https://app.asana.com/0/1204000740778938/1204217937089582/f) _(internal)_
- Add new manual graph traversal in PHP
- Dynamically decide what method to use at runtime
- Change version checks in the code to allow checking versions ad-hoc per feature
- The docs can now specify supporting a lower version of MySQL for general usage of the app (Have adjusted)
- MariaDB version requirements are a little unclear at the moment, ideally we'd be able …
> Add better compatibility for older MySQL versions

- libs/mock-block-dock/src/version.ts
- libs/wordpress-plugin/package.json
- libs/wordpress-plugin/plugin/trunk/block-protocol.php
- libs/wordpress-plugin/plugin/trunk/changelog.txt
- libs/wordpress-plugin/plugin/trunk/readme.txt
Version number and changelog amendments in order to release the WordPress plugin at version `0.0.6`.
> Bump WordPress plugin version to 0.0.6

- apps/site/src/pages/api/rewrites/sandboxed-block-demo.api.ts
This PR adds the `openaiCompleteChat` method to the sandbox block demo callbacks.
Go to the deployment, and try to use the AI Chat block at https://blockprotocol-jjalmoq9x.stage.hash.ai/@hash/blocks/ai-chat
> Add `openaiCompleteChat` method to sandbox callbacks

- apps/site/public/types/modules/graph/0.3/schema/property-type.json
The constraint for the minimum number of properties inside a property type object was in the incorrect place, it also was using the incorrect keyword (`minimumProperties` as opposed to `minProperties`). This fixes this mistake, and removes an `$id` in a sub-schema which seems to cause problems for local `$ref` resolution. The type has been checked with `ajv` and it seems to pass validation now.
Despite this being a breaking change to the schema, we are not treating these sorts of changes as breaking changes to the specification, as its omission was a bug and schemas made which do not satisfy these changes would be considered invalid as opposed to outdated. Importantly, the type-system crate (which is currently treated as the source of truth in usage) had these constraints appropriately …
> Fix Property Type metaschema

- apps/site/src/components/pages/hub/block-data-container.tsx
Fixes a bug in the Block Hub whereby if a block has an empty `examples` array (e.g. FAQ, Address), we would throw an error:
```
`Unable to create a new entity for block ${metadata.name} from its \`examples\` or \`variants\` as it doesn't have an associated schema`,
```
This is because there was an assumption that if the examples array was present, it would contain an example object. This PR handles empty examples array and defaults to an empty properties object.
- [Slack report ](https://hashintel.slack.com/archives/C02LG39FJAU/p1681809011296369)(internal)
This PR:
1.  View the FAQ and Address block on the staging deployment
> Handle blocks with schemas and missing example

- apps/site/src/components/screens/verification-code-screen.tsx
- apps/site/src/pages/signup.page.tsx
This PR fixes an issuse in the signup screen where a verification code passed in the URL from a magic link is submitted multiple times. This caused signup to fail sometimes, because concurrent requests were each given their own session id in response (i.e. given a new cookie value for `blockprotocol-session-id`), and unless the successful request was the last processed by the browser the user would be left with an unauthenticated session.
While the possibility of submitting the verification code multiple times looks to have been present for a good while, it's possible that this issue has only become an issue recently due to:
1. Recent changes to state / rendering of the signup page and verification code screen causing the 'submit code from url' effect to run more times than it was …
> Fix repeated submissions of verification codes from magic links

- libs/wordpress-plugin/package.json
- libs/wordpress-plugin/plugin/trunk/block-protocol.php
- libs/wordpress-plugin/plugin/trunk/changelog.txt
- libs/wordpress-plugin/plugin/trunk/readme.txt
- libs/wordpress-plugin/plugin/trunk/server/block-db-table.php
Bumps the WordPress plugin version to `0.0.8`, to introduce the new onboarding experience, and re-running migrations for users with older dbs that installed the plugin prior to older db support being introduced.
It also fixes an issue in checking MariaDB version number – MariaDB prefixes its version number with `5.5.5-` as a hack (apparently for [Oracle support](https://www.php.net/manual/en/mysqli.begin-transaction.php#122775)). This is stripped by clients but apparently not in all circumstances – try e.g. a instawp.xyz site, which will report an incompatible MariaDB version number for the plugin despite being compatible, because it appears as 5.5.5-10etc.
This PR therefore updates the check to query the db for its version, which is the approach used by WordPress – see …
> Increase WordPress plugin version to 0.0.8, fix MariaDB version checking

- .changeset/lemon-peas-shout.md
- libs/@blockprotocol/graph/src/codegen/initialize/traverse/fetch.ts
In some circumstances codegen would fail when trying to fetch a type, these failures were intermittent and introduced flakiness. This adds some simple retry logic around `fetchTypeAsJson` to mitigate ones that are spurious.
N/A
N/A
- Adds retry logic
This PR:
No
N/A
N/A
- `codegen` in the templates should fail if this breaks things
Try regenerating some types
CI
> Add retry logic to `fetchTypeAsJson`

- .changeset/heavy-pears-speak.md
- apps/site/package.json
- blocks/feature-showcase/package.json
- libs/block-template-custom-element/package.json
- libs/block-template-react/package.json
- yarn.lock
A new patch version for `@types/react-is` `17.0.4` was released 2 days ago that causes compilation issues in the block templates – see e.g. [this action run](https://github.com/blockprotocol/blockprotocol/actions/runs/4828042358/jobs/8601409864). Probably because it removed `next.d.ts` for some reason, as part of releasing a new `18.2.0` version.
Because the templates don't come with a lock file, they pick up this latest patch version (the first in 2 years) and `tsc` fails in them. This is true of any blocks created now, and means that all CI runs are failing. This was not picked up in CI because it is related to a broken patch version of a dependency being released (or at least one that breaks when used in this context).
This PR fixes the issue by specifying the version of …
> Specify @types/react-is version in block templates

- apps/site/src/lib/api/blocks/db.ts
- apps/site/src/lib/api/blocks/get.ts
- apps/site/src/lib/blocks.ts
We have code that aggregates a weekly download count for blocks when a block is requested (either as part of the list of all blocks, or as a single block). We aren't using this and it's adding unnecessary db work (and therefore slowing down queries). 
We can introduce and optimize it when we want to use it (it needs indices adding).
- [Asana task](https://app.asana.com/0/1203358502199087/1203922830586244/f) _(internal)_
This PR:
1.  Check that the block hub and an individual block page work
> Remove weekly block download aggregation

- apps/site/public/types/modules/graph/0.3/schema/entity-type.json
To allow more than just the predefined `link` type the constraint on `allOf` needs to be removed.
- [Asana task](https://app.asana.com/0/1204274556967336/1204588404823943/f) _(internal)_
This PR:
> Remove `const` field in `allOf` in entity type meta schema

- .github/vercel.install.sh
- apps/site/vercel.install.sh
Vercel limits the length of the install script to 256 characters. To install multiple dependencies, we easily hit the limit. This adds a script, which does the install step
- #1286 
This PR:
---
- https://app.asana.com/0/0/1204596705932049
> Provide a vercel-install script

- .github/actions/warm-up-repo/action.yml
- package.json
- yarn.lock
It's likely to be rate-limited in CI when running `just-install`. This manually installs just instead.
- [Asana task](https://app.asana.com/0/1204274556967336/1204486732268406/f) _(internal)_
This PR:
> Manually install `just` instead of using `just-install`

- .changeset/tasty-kids-enjoy.md
- libs/block-scripts/package.json
- libs/mock-block-dock/package.json
- libs/mock-block-dock/src/version.ts
- yarn.lock
The recent `7.22` release of Babel removed some plugin dependencies that we were relying on, which broke new block installs and thus CI in this repo, because the block templates don't come with a `yarn.lock` file and were getting the latest release (this isn't a problem running blocks inside the repo because Babel is locked to `7.21`).
This PR adds the missing dependencies.
- [Example failed CI run](https://github.com/blockprotocol/blockprotocol/actions/runs/5111441235/jobs/9188404775?pr=1255) 
This PR:
- [x modifies an **npm**-publishable library and **I have added a changeset file(s)**
- Merge the Version Packages PR once it is created
- CI: NPM Packages
> Add missing Babel plugin dependencies

- libs/@blockprotocol/type-system/crate/src/ontology/data_type/repr.rs
- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/repr.rs
- libs/@blockprotocol/type-system/crate/src/ontology/property_type/repr.rs
- libs/@blockprotocol/type-system/crate/src/ontology/shared/all_of/repr.rs
- libs/@blockprotocol/type-system/crate/src/ontology/shared/array/repr.rs
Some structs, which derive `Deserialize`, don't properly deserialize if the field is missing. `serde_json` and `serde_yaml` default to this behavior on `Option`, but other crates may/do not.
- [Discussion](https://www.notion.so/Using-WebAssembly-for-a-Portable-Single-Source-of-Truth-1dffefa1565c4c0e87e1f83786eff398?d=707d1e562630451fa5df041058e6247f&pvs=4#1ceaf8d05d75468a8f428e0f8ce82f56) _(internal)_
This PR:
> Add missing `default` attributes

- apps/site/src/components/page-sidebar.tsx
🌟 What is the purpose of this PR?
---
Correct header scroll position on spec, docs, roadmap, etc pages
---
🔗  Related links
---
- [Client Issue Link](https://github.com/blockprotocol/blockprotocol/issues/1276)
- Here is the GitStart Ticket for this pull request: [BP-OSS-1276](https://developers.gitstart.com/client/blockprotocol-oss/ticket/BP-OSS-1276)
❓How to test this?
---
https://www.loom.com/share/044308e8737041c497afba7318452db6
---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.
> [BP-22] Ensure correct header scroll position on spec, docs, roadmap, etc pages

- .changeset/soft-years-help.md
- blocks/feature-showcase/src/types/generated/block-entity.ts
- blocks/feature-showcase/src/types/generated/company.ts
- blocks/feature-showcase/src/types/generated/person.ts
- blocks/feature-showcase/src/types/generated/shared.ts
- libs/@blockprotocol/graph/src/codegen/shared.ts
- libs/block-template-custom-element/src/types/generated/block-entity.ts
- libs/block-template-react/src/types/generated/block-entity.ts
When generating TypeScript types from ontology type schemas, we want to avoid giving identical names to different types.
Because an entity type and a data type did not have any suffix on their name in the existing code, entity types and data types with identical titles (e.g. `Text`) could end up with identical type names.
This PR fixes that by giving a `DataType` suffix to data types, e.g. `TextDataType`.
This PR:
> Add suffix to name of auto-generated data types

- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/repr.rs
In [#1296](https://github.com/blockprotocol/blockprotocol/pull/1291) `repr::EntityType::merge_parent` was added but an important bit is missing: recursive merging. E.g. if `A` inherits from `B` and `B` inherits from `C` calling `A.merge_parent(B)` should add C to the `allOf` field.
This PR:
> BP-34: Fix `allOf` not being extended when entity type is merged with parent

- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/links/repr.rs
- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/repr.rs
- libs/@blockprotocol/type-system/crate/src/ontology/property_type/repr.rs
- libs/@blockprotocol/type-system/crate/src/ontology/shared/object/repr.rs
For implementing entity type inheritance it's required to have access to the underlying structure of the schema.
This PR:
> BP-31: Make fields in `entity_type::repr` module public

- .github/renovate.json
Following https://github.com/hashintel/hash/pull/2993, superseded by changes in https://github.com/hashintel/hash/pull/2997/files#diff-f82f7d36a61d22f640c25bdb8b0435bf9cb38679d99d5f460753fa668ee7cdb3, we now pin GitHub Actions to their SHAs. For security reasons we want to do the same here in the Þ repo.
Makes minor other updates for consistency with the Renovate config in the HASH repo.
- Will help address [CWE-1357](https://cwe.mitre.org/data/definitions/1357.html) when corresponding GitHub Actions are then updated.
> BP-54: Pin GitHub Action SHAs

- apps/site/src/middleware.page.ts
- apps/site/src/middleware.page/return-types-as-json.ts
The block sandbox on block pages (e.g. https://blockprotocol.org/@hash/blocks/code) has stopped working because of a redirect loop. This PR adds some logs to try and figure out what's going on.
> Debug block sandbox redirect loop

- apps/site/src/middleware.page.ts
- apps/site/src/middleware.page/return-types-as-json.ts
Remove debug logs added in #1329 – the issue was a redirect on the domain rather than anything in the application logic. Block pages are working again.
Also fixes a RegExp check which was updated in the same PR to avoid false positives on NextJS 'JSON for page' fetches, but missed a check.
> Remove debug logs, fix type RegExp check

- apps/site/src/middleware.page.ts
- apps/site/src/middleware.page/return-types-as-json.ts
#1330 attempted to share logic with the site's middleware to avoid a bug that crept in previously, but this introduced another bug (and was why the logic wasn't shared originally): the function to share imported a package which includes WASM, which is not allowed in the middleware function.
> Fix site middleware

- apps/site/next.config.js
Sets `poweredByHeader` to false in the Block Protocol website's `next.config.js` file.
- [poweredByHeader](https://nextjs.org/docs/app/api-reference/next-config-js/poweredByHeader) in the `Next.js` docs
> GEN-101: Set `poweredByHeader` to `false`

- .changeset/hungry-pears-cough.md
- libs/@blockprotocol/graph/src/codegen/initialize/traverse-and-collate-schemas.ts
- libs/@blockprotocol/graph/src/codegen/parameters.ts
- libs/@blockprotocol/graph/src/non-temporal/stdlib.ts
- libs/@blockprotocol/graph/src/shared/stdlib/subgraph/edge/link-entity.ts
This PR refactors several non-temporal BP methods to always have non-temporal return types, even when they are passed temporal subgraphs. This fixes blocks that are using non-temporal methods when they receive temporal subgraph from their EA.
This PR also adds previous HASH app patches to the `@blockprotocol/graph` package.
- H-1345
- adds a `forceNonTemporal` optional parameter to the 5 functions in `link-entity.ts`, and sets these to true in `non-temporal/stdlib.ts`
- adds a `rewriteTypeId` parameter to the codegen script (previously patched in the HASH App)
- handles edges with no temporal intersection gracefully in `getIncomingLinksForEntity`/`getOutgoingLinksForEntity` (previously patched for `getOutgoingLinksForEntity` in the HASH app)
This PR:
The changes in …
> H-1345: Refactor non-temporal BP methods to always have non-temporal returns

- libs/@blockprotocol/type-system/crate/src/ontology/data_type/mod.rs
- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/error.rs
- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/links/mod.rs
- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/mod.rs
- libs/@blockprotocol/type-system/crate/src/ontology/entity_type/raw.rs
- libs/@blockprotocol/type-system/crate/src/ontology/mod.rs
- libs/@blockprotocol/type-system/crate/src/ontology/property_type/mod.rs
- libs/@blockprotocol/type-system/crate/src/ontology/shared/all_of/mod.rs
- libs/@blockprotocol/type-system/crate/src/ontology/shared/object/mod.rs
As a quick solution to distinguish between format validation and content validation, the raw module should be made private and the serde implementation should use that internally. This greatly improves the DX around the types.
- Make the `raw` module internal
- move `merge_parent` from `raw::EntityType` to `EntityType`
- Implement `Serialize` and `Deserialize` on `DataType`, `PropertyType`, and `EntityType` via the `raw::` representation
- Make the inheritance field public as this is required downstream. I expect to also make the other fields public but not in this PR as the downstream PR for this PR is already big enough.
- Remove the bound on `ValidateUrl` to read the properties and required field on `Object`
This PR:
> BP-70, BP-59: Implement (de)serialize directly on ontology types

- libs/@blockprotocol/graph/src/non-temporal/stdlib.ts
- libs/@blockprotocol/graph/src/shared/stdlib/subgraph/edge/link-entity.ts
The `@blockprotocol/graph` packages exposes 'temporal' and default functions. The temporal functions are meant to be for consumers who need to know about temporal versioning.
In #1349 we updated some functions to force them to behave internally as if the subgraph was not a temporal one, but for _some_ of these functions the distinction is important, because the temporal subgraph has a different edge shape to the non-temporal ones. The only function that needs to be forced into 'non-temporal' mode is the one where the return shape depends on whether it's temporal or not, which these don't (apart from missing some fields on the entity internally, which is fine).
This PR:
> BP-72: Fix non-temporal `stdlib` functions

- libs/wordpress-plugin/package.json
- libs/wordpress-plugin/plugin/trunk/block/edit-or-preview/edit/service-callbacks.tsx
- libs/wordpress-plugin/yarn.lock
This PR removes `completeText` from the wordpress plugin service module, by upgrading `@blockprotocol/service` to the latest version.
- H-1868
This PR:
> H-1868: Remove `completeText` from the wordpress plugin

- apps/site/src/_pages/roadmap/00_index.mdx
- apps/site/src/_pages/spec/00_index.mdx
- apps/site/src/pages/roadmap/[[...roadmap-slug]].page.tsx
- apps/site/src/util/mdx-utils.tsx
Drive-by simplifications and clean-ups prior to moving the Block Protocol docs to be co-located on [hash.dev](https://hash.dev/)
> H-1981: Simplification of docs

- .changeset/tall-otters-push.md
- libs/@blockprotocol/graph/src/shared/types/ontology/entity-type.ts
Adds two optional new fields to the metadata for Entity Types:
1. `icon`: a `string` representing the entity type's icon. either an emoji or a URL to an image file
2. `labelProperty`: a `BaseUrl` representing the property on an entity of the type that should be used to label it for display
This PR:
Once merged, publish a new version of the library, and handle `labelProperty` in the type editor.
> BP-79: Add 'icon' and 'labelProperty' to entity type metadata

- apps/site/src/_pages/docs/1_blocks/01_environments.mdx
- apps/site/src/_pages/docs/3_services.mdx
- apps/site/src/components/pages/home/supported-applications.tsx
Following the end of GitHub Next's `GitHub Blocks` experiment, planned support from the Block Protocol has been scrapped.
> H-2305: Remove `GitHub Blocks` from planned environments

- .changeset/gorgeous-horses-pull.md
- libs/@blockprotocol/graph/src/shared/stdlib/subgraph/element/entity.ts
- libs/mock-block-dock/src/version.ts
Account for an entity potentially being keyed by an entityId that has a suffix indicating it's a draft – part of ongoing evolution of the spec to be reflected back into docs once stable. 
- Used in https://github.com/hashintel/hash/pull/4166
This PR:
> H-2387: Fix `@blockprotocol/graph` to account for draftIds

- .nvmrc
- apps/site/.nvmrc
- libs/@blockprotocol/design-system/.nvmrc
Makes `fnm` and other Node version managers function correctly, while correcting the existing declaration (16 gallium -> 18 hydrogen) for the BP root, user-facing website, and design system.
> BP-106: Update and add `.nvmrc` files

- apps/site/public/types/modules/graph/0.3/schema/data-type.json
- apps/site/public/types/modules/graph/0.3/schema/entity-type.json
- apps/site/public/types/modules/graph/0.3/schema/property-type.json
The ontology types are outdated. This updates the schemas so it reflects a more up-to-date state.
**Entity type**:
- Make `description` required
- Change `allOf` from `maxItems` to `minItems` (if specified we want at least one element, and we don’t limit the upper limit)
- Add `titlePlural`
- Add `labelProperty`
- Add `icon`
- Add `inverse: { title, titlePlural }`
- Remove `ordered`
**Property type**:
- Make `description` required
**Data type**:
- Make `description` required
- Add `ValueConstraint` (required type as enum)
- Add `oneOf` over `ValueConstraint` or `anyOf: ValueConstraint[]`
- Add `allOf`
> BP-110: Update ontology type meta-schemas

- apps/site/public/types/modules/graph/0.3/schema/data-type.json
https://github.com/blockprotocol/blockprotocol/pull/1427 had a typo and `string` was specified twice. Instead, `object` was missing.
> GEN-110: Fix data type schema
